//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from openai.yml
//  OpenAPI spec version: 3.1.0

final class CreateFineTuningJobRequestIntegrationsTypeVariant1 {const CreateFineTuningJobRequestIntegrationsTypeVariant1._(this.value);

factory CreateFineTuningJobRequestIntegrationsTypeVariant1.fromJson(String json) { return switch (json) {
  'wandb' => wandb,
  _ => CreateFineTuningJobRequestIntegrationsTypeVariant1._(json),
}; }

static const CreateFineTuningJobRequestIntegrationsTypeVariant1 wandb = CreateFineTuningJobRequestIntegrationsTypeVariant1._('wandb');

static const List<CreateFineTuningJobRequestIntegrationsTypeVariant1> values = [wandb];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is CreateFineTuningJobRequestIntegrationsTypeVariant1 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'CreateFineTuningJobRequestIntegrationsTypeVariant1($value)'; } 
 }
/// A value that is one of: `CreateFineTuningJobRequestIntegrationsTypeVariant1`.
sealed class CreateFineTuningJobRequestIntegrationsType {const CreateFineTuningJobRequestIntegrationsType();

factory CreateFineTuningJobRequestIntegrationsType.fromJson(Map<String, dynamic> json) {   return CreateFineTuningJobRequestIntegrationsType$Unknown(json); }

/// The underlying raw value.
Object? get value;
Object? toJson() { return value; } 
 }
final class CreateFineTuningJobRequestIntegrationsTypeCreateFineTuningJobRequestIntegrationsTypeVariant1 extends CreateFineTuningJobRequestIntegrationsType {const CreateFineTuningJobRequestIntegrationsTypeCreateFineTuningJobRequestIntegrationsTypeVariant1(this._value);

final CreateFineTuningJobRequestIntegrationsTypeVariant1 _value;

@override CreateFineTuningJobRequestIntegrationsTypeVariant1 get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is CreateFineTuningJobRequestIntegrationsTypeCreateFineTuningJobRequestIntegrationsTypeVariant1 && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'CreateFineTuningJobRequestIntegrationsType.createFineTuningJobRequestIntegrationsTypeVariant1($_value)'; } 
 }
/// An unknown variant not defined in the OpenAPI spec.
final class CreateFineTuningJobRequestIntegrationsType$Unknown extends CreateFineTuningJobRequestIntegrationsType {const CreateFineTuningJobRequestIntegrationsType$Unknown(this._value);

final Object? _value;

@override Object get value { return _value ?? ''; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is CreateFineTuningJobRequestIntegrationsType$Unknown && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'CreateFineTuningJobRequestIntegrationsType.unknown($_value)'; } 
 }
