//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from openai.yml
//  OpenAPI spec version: 3.1.0

/// The event type, must be `transcription_session.update`.
final class RealtimeClientEventTranscriptionSessionUpdateType {const RealtimeClientEventTranscriptionSessionUpdateType._(this.value);

factory RealtimeClientEventTranscriptionSessionUpdateType.fromJson(String json) { return switch (json) {
  'transcription_session.update' => transcriptionSessionUpdate,
  _ => RealtimeClientEventTranscriptionSessionUpdateType._(json),
}; }

static const RealtimeClientEventTranscriptionSessionUpdateType transcriptionSessionUpdate = RealtimeClientEventTranscriptionSessionUpdateType._('transcription_session.update');

static const List<RealtimeClientEventTranscriptionSessionUpdateType> values = [transcriptionSessionUpdate];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RealtimeClientEventTranscriptionSessionUpdateType && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'RealtimeClientEventTranscriptionSessionUpdateType($value)'; } 
 }
