//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from openai.yml
//  OpenAPI spec version: 3.1.0

import 'inline_object86.dart';/// Enables tracing and sets default values for tracing configuration options. Always `auto`.
/// 
final class InlineObject85 {const InlineObject85._(this.value);

factory InlineObject85.fromJson(String json) { return switch (json) {
  'auto' => auto,
  _ => InlineObject85._(json),
}; }

static const InlineObject85 auto = InlineObject85._('auto');

static const List<InlineObject85> values = [auto];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject85 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject85($value)'; } 
 }
/// A value that is one of: `InlineObject85`, `InlineObject86`.
sealed class RealtimeSessionCreateResponseGaTracing {const RealtimeSessionCreateResponseGaTracing();

factory RealtimeSessionCreateResponseGaTracing.fromJson(Map<String, dynamic> json) {   if (InlineObject86.canParse(json)) {
    return RealtimeSessionCreateResponseGaTracingInlineObject86(InlineObject86.fromJson(json));
  }
  return RealtimeSessionCreateResponseGaTracing$Unknown(json); }

/// The underlying raw value.
Object? get value;
Object? toJson() { return value; } 
 }
final class RealtimeSessionCreateResponseGaTracingInlineObject85 extends RealtimeSessionCreateResponseGaTracing {const RealtimeSessionCreateResponseGaTracingInlineObject85(this._value);

final InlineObject85 _value;

@override InlineObject85 get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RealtimeSessionCreateResponseGaTracingInlineObject85 && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'RealtimeSessionCreateResponseGaTracing.inlineObject85($_value)'; } 
 }
final class RealtimeSessionCreateResponseGaTracingInlineObject86 extends RealtimeSessionCreateResponseGaTracing {const RealtimeSessionCreateResponseGaTracingInlineObject86(this._value);

final InlineObject86 _value;

@override InlineObject86 get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RealtimeSessionCreateResponseGaTracingInlineObject86 && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'RealtimeSessionCreateResponseGaTracing.inlineObject86($_value)'; } 
 }
/// An unknown variant not defined in the OpenAPI spec.
final class RealtimeSessionCreateResponseGaTracing$Unknown extends RealtimeSessionCreateResponseGaTracing {const RealtimeSessionCreateResponseGaTracing$Unknown(this._value);

final Object? _value;

@override Object get value { return _value ?? ''; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RealtimeSessionCreateResponseGaTracing$Unknown && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'RealtimeSessionCreateResponseGaTracing.unknown($_value)'; } 
 }
