//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from openai.yml
//  OpenAPI spec version: 3.1.0

import 'realtime_server_event_conversation_item_input_audio_transcription_failed_error.dart';/// The event type, must be
/// `conversation.item.input_audio_transcription.failed`.
/// 
final class RealtimeServerEventConversationItemInputAudioTranscriptionFailedType {const RealtimeServerEventConversationItemInputAudioTranscriptionFailedType._(this.value);

factory RealtimeServerEventConversationItemInputAudioTranscriptionFailedType.fromJson(String json) { return switch (json) {
  'conversation.item.input_audio_transcription.failed' => conversationItemInputAudioTranscriptionFailed,
  _ => RealtimeServerEventConversationItemInputAudioTranscriptionFailedType._(json),
}; }

static const RealtimeServerEventConversationItemInputAudioTranscriptionFailedType conversationItemInputAudioTranscriptionFailed = RealtimeServerEventConversationItemInputAudioTranscriptionFailedType._('conversation.item.input_audio_transcription.failed');

static const List<RealtimeServerEventConversationItemInputAudioTranscriptionFailedType> values = [conversationItemInputAudioTranscriptionFailed];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RealtimeServerEventConversationItemInputAudioTranscriptionFailedType && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'RealtimeServerEventConversationItemInputAudioTranscriptionFailedType($value)'; } 
 }
/// Returned when input audio transcription is configured, and a transcription
/// request for a user message failed. These events are separate from other
/// `error` events so that the client can identify the related Item.
/// 
final class RealtimeServerEventConversationItemInputAudioTranscriptionFailed {const RealtimeServerEventConversationItemInputAudioTranscriptionFailed({required this.eventId, required this.type, required this.itemId, required this.contentIndex, required this.error, });

factory RealtimeServerEventConversationItemInputAudioTranscriptionFailed.fromJson(Map<String, dynamic> json) { return RealtimeServerEventConversationItemInputAudioTranscriptionFailed(
  eventId: json['event_id'] as String,
  type: RealtimeServerEventConversationItemInputAudioTranscriptionFailedType.fromJson(json['type'] as String),
  itemId: json['item_id'] as String,
  contentIndex: (json['content_index'] as num).toInt(),
  error: RealtimeServerEventConversationItemInputAudioTranscriptionFailedError.fromJson(json['error'] as Map<String, dynamic>),
); }

/// The unique ID of the server event.
final String eventId;

/// The event type, must be
/// `conversation.item.input_audio_transcription.failed`.
/// 
final RealtimeServerEventConversationItemInputAudioTranscriptionFailedType type;

/// The ID of the user message item.
final String itemId;

/// The index of the content part containing the audio.
final int contentIndex;

/// Details of the transcription error.
final RealtimeServerEventConversationItemInputAudioTranscriptionFailedError error;

Map<String, dynamic> toJson() { return {
  'event_id': eventId,
  'type': type.toJson(),
  'item_id': itemId,
  'content_index': contentIndex,
  'error': error.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('event_id') && json['event_id'] is String &&
      json.containsKey('type') &&
      json.containsKey('item_id') && json['item_id'] is String &&
      json.containsKey('content_index') && json['content_index'] is num &&
      json.containsKey('error'); } 
RealtimeServerEventConversationItemInputAudioTranscriptionFailed copyWith({String? eventId, RealtimeServerEventConversationItemInputAudioTranscriptionFailedType? type, String? itemId, int? contentIndex, RealtimeServerEventConversationItemInputAudioTranscriptionFailedError? error, }) { return RealtimeServerEventConversationItemInputAudioTranscriptionFailed(
  eventId: eventId ?? this.eventId,
  type: type ?? this.type,
  itemId: itemId ?? this.itemId,
  contentIndex: contentIndex ?? this.contentIndex,
  error: error ?? this.error,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is RealtimeServerEventConversationItemInputAudioTranscriptionFailed &&
          eventId == other.eventId &&
          type == other.type &&
          itemId == other.itemId &&
          contentIndex == other.contentIndex &&
          error == other.error; } 
@override int get hashCode { return Object.hash(eventId, type, itemId, contentIndex, error); } 
@override String toString() { return 'RealtimeServerEventConversationItemInputAudioTranscriptionFailed(eventId: $eventId, type: $type, itemId: $itemId, contentIndex: $contentIndex, error: $error)'; } 
 }
