//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from openai.yml
//  OpenAPI spec version: 3.1.0

import 'tracing_configuration4.dart';/// Default tracing mode for the session.
/// 
final class RealtimeSessionCreateResponseTracingVariant1 {const RealtimeSessionCreateResponseTracingVariant1._(this.value);

factory RealtimeSessionCreateResponseTracingVariant1.fromJson(String json) { return switch (json) {
  'auto' => auto,
  _ => RealtimeSessionCreateResponseTracingVariant1._(json),
}; }

static const RealtimeSessionCreateResponseTracingVariant1 auto = RealtimeSessionCreateResponseTracingVariant1._('auto');

static const List<RealtimeSessionCreateResponseTracingVariant1> values = [auto];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RealtimeSessionCreateResponseTracingVariant1 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'RealtimeSessionCreateResponseTracingVariant1($value)'; } 
 }
/// A value that is one of: `RealtimeSessionCreateResponseTracingVariant1`, `TracingConfiguration4`.
sealed class RealtimeSessionCreateResponseTracing {const RealtimeSessionCreateResponseTracing();

factory RealtimeSessionCreateResponseTracing.fromJson(Map<String, dynamic> json) {   if (TracingConfiguration4.canParse(json)) {
    return RealtimeSessionCreateResponseTracingTracingConfiguration4(TracingConfiguration4.fromJson(json));
  }
  return RealtimeSessionCreateResponseTracing$Unknown(json); }

/// The underlying raw value.
Object? get value;
Object? toJson() { return value; } 
 }
final class RealtimeSessionCreateResponseTracingRealtimeSessionCreateResponseTracingVariant1 extends RealtimeSessionCreateResponseTracing {const RealtimeSessionCreateResponseTracingRealtimeSessionCreateResponseTracingVariant1(this._value);

final RealtimeSessionCreateResponseTracingVariant1 _value;

@override RealtimeSessionCreateResponseTracingVariant1 get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RealtimeSessionCreateResponseTracingRealtimeSessionCreateResponseTracingVariant1 && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'RealtimeSessionCreateResponseTracing.realtimeSessionCreateResponseTracingVariant1($_value)'; } 
 }
final class RealtimeSessionCreateResponseTracingTracingConfiguration4 extends RealtimeSessionCreateResponseTracing {const RealtimeSessionCreateResponseTracingTracingConfiguration4(this._value);

final TracingConfiguration4 _value;

@override TracingConfiguration4 get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RealtimeSessionCreateResponseTracingTracingConfiguration4 && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'RealtimeSessionCreateResponseTracing.tracingConfiguration4($_value)'; } 
 }
/// An unknown variant not defined in the OpenAPI spec.
final class RealtimeSessionCreateResponseTracing$Unknown extends RealtimeSessionCreateResponseTracing {const RealtimeSessionCreateResponseTracing$Unknown(this._value);

final Object? _value;

@override Object get value { return _value ?? ''; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RealtimeSessionCreateResponseTracing$Unknown && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'RealtimeSessionCreateResponseTracing.unknown($_value)'; } 
 }
