name: petstore_example
description: Example CLI app using generated petstore workspace client.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  degenerate_http: ^0.1.0
  degenerate_runtime: ^0.1.0
