name: petstore_example
description: Example CLI app using generated petstore client.
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  petstore_client:
    path: petstore_client
  degenerate_http:
    path: ../packages/degenerate_http
