name: petstore_example_workspace
description: Example CLI app using generated petstore workspace client.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0

workspace:
  - packages/petstore_client

dependencies:
  degenerate_http:
  petstore_client:
