name: degenerate
description: OpenAPI to Dart client code generator.
version: 0.1.1
repository: https://github.com/blopker/degenerate

executables:
  degenerate: degenerate

environment:
  sdk: ^3.11.1

dependencies:
  args: ^2.7.0
  yaml: ^3.1.0
  code_builder: ^4.10.0
  path: ^1.9.0
  collection: ^1.19.0

workspace:
  - packages/*
  - snapshots/specs/*
  - snapshots/public/*
  - test/wire/*
  - example
  - example/petstore_client

dev_dependencies:
  dart_style: ^3.0.0
  lints: ^6.0.0
  test: ^1.25.6
