//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'dart:async';import 'dart:convert';import 'package:degenerate_runtime/degenerate_runtime.dart';import '../models/access_components_schemas_email.dart';import '../models/access_identifier.dart';import '../models/access_user_id.dart';import '../models/response_common3.dart';/// AccessAuthenticationLogsApi operations.
///
/// All operations return [ApiResult] - use pattern matching to handle
/// success, error, and exception cases.
final class AccessAuthenticationLogsApi {const AccessAuthenticationLogsApi(this._config);

final ApiConfig _config;

/// Get Access authentication logs
///
/// Gets a list of Access authentication audit logs for an account.
///
/// `GET /accounts/{account_id}/access/logs/access_requests`
Future<ApiResult<ResponseCommon3, Never>> accessAuthenticationLogsGetAccessAuthenticationLogs({required AccessIdentifier accountId, int? limit, dynamic direction, DateTime? since, DateTime? until, int? page, int? perPage, AccessComponentsSchemasEmail? email, bool? emailExact, AccessUserId? userId, RequestOptions? options, }) async  { final queryParameters = <String, String>{..._config.defaultQueryParameters};
final queryParametersList = <ApiQueryParameter>[];
if (limit != null) queryParameters['limit'] = limit.toString();
if (direction != null) queryParameters['direction'] = direction.toString();
if (since != null) queryParameters['since'] = since.toString();
if (until != null) queryParameters['until'] = until.toString();
if (page != null) queryParameters['page'] = page.toString();
if (perPage != null) queryParameters['per_page'] = perPage.toString();
if (email != null) queryParameters['email'] = email.toString();
if (emailExact != null) queryParameters['email_exact'] = emailExact.toString();
if (userId != null) queryParameters['user_id'] = userId.toString();

final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/access/logs/access_requests',
  headers: headers,
  queryParameters: queryParameters,
  queryParametersList: queryParametersList,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon3.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Shared execution pipeline: interceptors -> send -> deserialize.
Future<ApiResult<T, E>> _execute<T,E>(ApiRequest request, {required T Function(ApiResponse) onSuccess, E? Function(ApiResponse)? onError, }) async  { try {
  final userCancelToken = request.options?.cancelToken;
  if (userCancelToken?.isCancelled ?? false) throw const CancelledException();

  final effectiveTimeout = request.options?.timeout ?? _config.timeout;
  final extraHeaders = request.options?.extraHeaders;

  // Merge timeout and user cancel into a single adapter-level cancel token.
  final adapterToken = (effectiveTimeout != null || userCancelToken != null)
      ? CancelToken()
      : null;
  Timer? timeoutTimer;
  bool timedOut = false;

  if (adapterToken != null) {
    if (userCancelToken != null) {
      final token = adapterToken;
      userCancelToken.whenCancelled.then((_) {
        if (!token.isCancelled) token.cancel();
      });
    }
    if (effectiveTimeout != null) {
      final token = adapterToken;
      timeoutTimer = Timer(effectiveTimeout, () {
        timedOut = true;
        if (!token.isCancelled) token.cancel();
      });
    }
  }

  final effectiveRequest = request.copyWith(
    headers: extraHeaders != null
        ? {...request.headers, ...extraHeaders}
        : null,
    options: RequestOptions(cancelToken: adapterToken),
  );

  try {
    final chain = buildInterceptorChain(
      interceptors: _config.interceptors,
      terminal: (req) => _config.client.send(req),
    );

    final response = await chain(effectiveRequest);
    timeoutTimer?.cancel();

    try {
      if (response.isSuccessful) {
        return ApiSuccess(
          onSuccess(response),
          statusCode: response.statusCode,
          headers: response.headers,
        );
      }
      return ApiError(
        statusCode: response.statusCode,
        error: onError != null ? onError(response) : null,
        rawError: response.body,
        headers: response.headers,
      );
    } catch (e, st) {
      return ApiParseException(e, st, response: response);
    }
  } on CancelledException {
    timeoutTimer?.cancel();
    if (timedOut) {
      throw TimeoutException('Request timed out', effectiveTimeout);
    }
    rethrow;
  }
} catch (e, st) {
  return ApiException(e, st);
}
 } 
 }
