//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'dart:convert';import '../client/api_client.dart';import '../client/api_config.dart';import '../client/api_result.dart';import '../models/response_common75.dart';import '../models/waf_content_scanning_add_custom_scan_expressions_request.dart';import '../models/waf_content_scanning_update_settings_request.dart';/// ContentScanningApi operations.
///
/// All operations return [ApiResult] — use pattern matching to handle
/// success, error, and exception cases.
final class ContentScanningApi {const ContentScanningApi(this._config);

final ApiConfig _config;

/// Disable Content Scanning
///
/// Disable Content Scanning.
///
/// `POST /zones/{zone_id}/content-upload-scan/disable`
Future<ApiResult<ResponseCommon75, Never>> wafContentScanningDisable({required String zoneId}) async  { final request = ApiRequest(
  method: 'POST',
  path: '/zones/${Uri.encodeComponent(zoneId)}/content-upload-scan/disable',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon75.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Enable Content Scanning
///
/// Enable Content Scanning.
///
/// `POST /zones/{zone_id}/content-upload-scan/enable`
Future<ApiResult<ResponseCommon75, Never>> wafContentScanningEnable({required String zoneId}) async  { final request = ApiRequest(
  method: 'POST',
  path: '/zones/${Uri.encodeComponent(zoneId)}/content-upload-scan/enable',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon75.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// List Existing Custom Scan Expressions
///
/// Get a list of existing custom scan expressions for Content Scanning.
///
/// `GET /zones/{zone_id}/content-upload-scan/payloads`
Future<ApiResult<ResponseCommon75, Never>> wafContentScanningListCustomScanExpressions({required String zoneId}) async  { final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId)}/content-upload-scan/payloads',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon75.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Add Custom Scan Expressions
///
/// Add custom scan expressions for Content Scanning.
///
/// `POST /zones/{zone_id}/content-upload-scan/payloads`
Future<ApiResult<ResponseCommon75, Never>> wafContentScanningAddCustomScanExpressions({required String zoneId, required List<WafContentScanningAddCustomScanExpressionsRequest> body, }) async  { final request = ApiRequest(
  method: 'POST',
  path: '/zones/${Uri.encodeComponent(zoneId)}/content-upload-scan/payloads',
  headers: {..._config.defaultHeaders
    , 'Content-Type': 'application/json'
  },
  body: jsonEncode(body),
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon75.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Delete a Custom Scan Expression
///
/// Delete a Content Scan Custom Expression.
///
/// `DELETE /zones/{zone_id}/content-upload-scan/payloads/{expression_id}`
Future<ApiResult<ResponseCommon75, Never>> wafContentScanningDeleteCustomScanExpressions({required String zoneId, required String expressionId, }) async  { final request = ApiRequest(
  method: 'DELETE',
  path: '/zones/${Uri.encodeComponent(zoneId)}/content-upload-scan/payloads/${Uri.encodeComponent(expressionId)}',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon75.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Get Content Scanning Status
///
/// Retrieve the current status of Content Scanning.
///
/// `GET /zones/{zone_id}/content-upload-scan/settings`
Future<ApiResult<ResponseCommon75, Never>> wafContentScanningGetStatus({required String zoneId}) async  { final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId)}/content-upload-scan/settings',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon75.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Update Content Scanning Status
///
/// Update the Content Scanning status.
///
/// `PUT /zones/{zone_id}/content-upload-scan/settings`
Future<ApiResult<ResponseCommon75, Never>> wafContentScanningUpdateSettings({required String zoneId, required WafContentScanningUpdateSettingsRequest body, }) async  { final request = ApiRequest(
  method: 'PUT',
  path: '/zones/${Uri.encodeComponent(zoneId)}/content-upload-scan/settings',
  headers: {..._config.defaultHeaders
    , 'Content-Type': 'application/json'
  },
  body: jsonEncode(body.toJson()),
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon75.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Shared execution pipeline: interceptors -> send -> deserialize.
Future<ApiResult<T, E>> _execute<T,E>(ApiRequest request, {required T Function(ApiResponse) onSuccess, E? Function(ApiResponse)? onError, }) async  { var req = request;
try {
  for (final interceptor in _config.interceptors) {
    req = await interceptor.onRequest(req);
  }

  var response = _config.timeout != null
      ? await _config.client.send(req).timeout(_config.timeout!)
      : await _config.client.send(req);

  for (final interceptor in _config.interceptors) {
    response = await interceptor.onResponse(response);
  }

  if (response.isSuccessful) {
    return ApiSuccess(
      onSuccess(response),
      statusCode: response.statusCode,
      headers: response.headers,
    );
  }
  return ApiError(
    statusCode: response.statusCode,
    error: onError != null ? onError(response) : null,
    rawBody: response.body,
    headers: response.headers,
  );
} catch (e, st) {
  for (final interceptor in _config.interceptors) {
    try {
      final recovered = await interceptor.onError(e, st, req);
      if (recovered.isSuccessful) {
        return ApiSuccess(onSuccess(recovered), statusCode: recovered.statusCode, headers: recovered.headers);
      }
      return ApiError(statusCode: recovered.statusCode, error: onError != null ? onError(recovered) : null, rawBody: recovered.body, headers: recovered.headers);
    } catch (_) {
      // Interceptor couldn't handle it, continue to next or fall through
    }
  }
  return ApiException(e, st);
}
 } 
 }
