//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'dart:convert';import 'package:degenerate_runtime/degenerate_runtime.dart';import '../models/rulesets_managed_transforms.dart';import '../models/rulesets_response.dart';import '../models/rulesets_zone_id.dart';/// ManagedTransformsApi operations.
///
/// All operations return [ApiResult] — use pattern matching to handle
/// success, error, and exception cases.
final class ManagedTransformsApi {const ManagedTransformsApi(this._config);

final ApiConfig _config;

/// List Managed Transforms
///
/// Fetches a list of all Managed Transforms.
///
/// `GET /zones/{zone_id}/managed_headers`
Future<ApiResult<RulesetsResponse, Never>> listManagedTransforms({required RulesetsZoneId zoneId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/managed_headers',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return RulesetsResponse.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Update Managed Transforms
///
/// Updates the status of one or more Managed Transforms.
///
/// `PATCH /zones/{zone_id}/managed_headers`
Future<ApiResult<RulesetsResponse, Never>> updateManagedTransforms({required RulesetsZoneId zoneId, required RulesetsManagedTransforms body, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'PATCH',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/managed_headers',
  headers: headers,
  body: jsonEncode(body.toJson()),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return RulesetsResponse.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Delete Managed Transforms
///
/// Disables all Managed Transforms.
///
/// `DELETE /zones/{zone_id}/managed_headers`
Future<ApiResult<void, Never>> deleteManagedTransforms({required RulesetsZoneId zoneId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'DELETE',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/managed_headers',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (_) {},
);
 } 
/// Shared execution pipeline: interceptors -> send -> deserialize.
Future<ApiResult<T, E>> _execute<T,E>(ApiRequest request, {required T Function(ApiResponse) onSuccess, E? Function(ApiResponse)? onError, }) async  { try {
  final cancelToken = request.options?.cancelToken;
  if (cancelToken?.isCancelled ?? false) throw const CancelledException();

  final effectiveTimeout = request.options?.timeout ?? _config.timeout;
  final extraHeaders = request.options?.extraHeaders;
  final effectiveRequest = extraHeaders != null
      ? request.copyWith(headers: {...request.headers, ...extraHeaders})
      : request;

  final chain = buildInterceptorChain(
    interceptors: _config.interceptors,
    terminal: (req) async {
      if (cancelToken?.isCancelled ?? false) throw const CancelledException();
      final future = _config.client.send(req);
      return effectiveTimeout != null
          ? await future.timeout(effectiveTimeout)
          : await future;
    },
  );

  final response = await chain(effectiveRequest);

  try {
    if (response.isSuccessful) {
      return ApiSuccess(
        onSuccess(response),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    return ApiError(
      statusCode: response.statusCode,
      error: onError != null ? onError(response) : null,
      rawError: response.body,
      headers: response.headers,
    );
  } catch (e, st) {
    return ApiParseException(e, st, response: response);
  }
} catch (e, st) {
  return ApiException(e, st);
}
 } 
 }
