//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'dart:convert';import 'package:degenerate_runtime/degenerate_runtime.dart';import '../models/aaa_account_id.dart';import '../models/aaa_webhook_id.dart';import '../models/notification_webhooks_create_a_webhook_request.dart';import '../models/notification_webhooks_update_a_webhook_request.dart';import '../models/response_common2.dart';/// NotificationWebhooksApi operations.
///
/// All operations return [ApiResult] — use pattern matching to handle
/// success, error, and exception cases.
final class NotificationWebhooksApi {const NotificationWebhooksApi(this._config);

final ApiConfig _config;

/// List webhooks
///
/// Gets a list of all configured webhook destinations.
///
/// `GET /accounts/{account_id}/alerting/v3/destinations/webhooks`
Future<ApiResult<ResponseCommon2, Never>> notificationWebhooksListWebhooks({required AaaAccountId accountId}) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/alerting/v3/destinations/webhooks',
  headers: headers,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon2.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Create a webhook
///
/// Creates a new webhook destination.
///
/// `POST /accounts/{account_id}/alerting/v3/destinations/webhooks`
Future<ApiResult<ResponseCommon2, Never>> notificationWebhooksCreateAWebhook({required AaaAccountId accountId, required NotificationWebhooksCreateAWebhookRequest body, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'POST',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/alerting/v3/destinations/webhooks',
  headers: headers,
  body: jsonEncode(body.toJson()),
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon2.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Get a webhook
///
/// Get details for a single webhooks destination.
///
/// `GET /accounts/{account_id}/alerting/v3/destinations/webhooks/{webhook_id}`
Future<ApiResult<ResponseCommon2, Never>> notificationWebhooksGetAWebhook({required AaaAccountId accountId, required AaaWebhookId webhookId, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/alerting/v3/destinations/webhooks/${Uri.encodeComponent(webhookId.toString())}',
  headers: headers,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon2.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Update a webhook
///
/// Update a webhook destination.
///
/// `PUT /accounts/{account_id}/alerting/v3/destinations/webhooks/{webhook_id}`
Future<ApiResult<ResponseCommon2, Never>> notificationWebhooksUpdateAWebhook({required AaaWebhookId webhookId, required AaaAccountId accountId, required NotificationWebhooksUpdateAWebhookRequest body, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'PUT',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/alerting/v3/destinations/webhooks/${Uri.encodeComponent(webhookId.toString())}',
  headers: headers,
  body: jsonEncode(body.toJson()),
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon2.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Delete a webhook
///
/// Delete a configured webhook destination.
///
/// `DELETE /accounts/{account_id}/alerting/v3/destinations/webhooks/{webhook_id}`
Future<ApiResult<ResponseCommon2, Never>> notificationWebhooksDeleteAWebhook({required AaaWebhookId webhookId, required AaaAccountId accountId, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'DELETE',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/alerting/v3/destinations/webhooks/${Uri.encodeComponent(webhookId.toString())}',
  headers: headers,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon2.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Shared execution pipeline: interceptors -> send -> deserialize.
Future<ApiResult<T, E>> _execute<T,E>(ApiRequest request, {required T Function(ApiResponse) onSuccess, E? Function(ApiResponse)? onError, }) async  { try {
  final chain = buildInterceptorChain(
    interceptors: _config.interceptors,
    terminal: (req) async {
      return _config.timeout != null
          ? await _config.client.send(req).timeout(_config.timeout!)
          : await _config.client.send(req);
    },
  );

  final response = await chain(request);

  try {
    if (response.isSuccessful) {
      return ApiSuccess(
        onSuccess(response),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    return ApiError(
      statusCode: response.statusCode,
      error: onError != null ? onError(response) : null,
      rawError: response.body,
      headers: response.headers,
    );
  } catch (e, st) {
    return ApiParseException(e, st, response: response);
  }
} catch (e, st) {
  return ApiException(e, st);
}
 } 
 }
