//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'dart:convert';import 'package:degenerate_runtime/degenerate_runtime.dart';import '../models/cache_rules_identifier.dart';import '../models/cache_rules_smart_tiered_cache_patch.dart';import '../models/response_common10.dart';/// SmartTieredCacheApi operations.
///
/// All operations return [ApiResult] — use pattern matching to handle
/// success, error, and exception cases.
final class SmartTieredCacheApi {const SmartTieredCacheApi(this._config);

final ApiConfig _config;

/// Get Smart Tiered Cache setting
///
/// Smart Tiered Cache dynamically selects the single closest upper tier for each of your website’s origins with no configuration required, using our in-house performance and routing data. Cloudflare collects latency data for each request to an origin, and uses the latency data to determine how well any upper-tier data center is connected with an origin. As a result, Cloudflare can select the data center with the lowest latency to be the upper-tier for an origin.
///
/// `GET /zones/{zone_id}/cache/tiered_cache_smart_topology_enable`
Future<ApiResult<ResponseCommon10, Never>> smartTieredCacheGetSmartTieredCacheSetting({required CacheRulesIdentifier zoneId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/tiered_cache_smart_topology_enable',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Patch Smart Tiered Cache setting
///
/// Smart Tiered Cache dynamically selects the single closest upper tier for each of your website’s origins with no configuration required, using our in-house performance and routing data. Cloudflare collects latency data for each request to an origin, and uses the latency data to determine how well any upper-tier data center is connected with an origin. As a result, Cloudflare can select the data center with the lowest latency to be the upper-tier for an origin.
///
/// `PATCH /zones/{zone_id}/cache/tiered_cache_smart_topology_enable`
Future<ApiResult<ResponseCommon10, Never>> smartTieredCachePatchSmartTieredCacheSetting({required CacheRulesIdentifier zoneId, required CacheRulesSmartTieredCachePatch body, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'PATCH',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/tiered_cache_smart_topology_enable',
  headers: headers,
  body: jsonEncode(body.toJson()),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Delete Smart Tiered Cache setting
///
/// Smart Tiered Cache dynamically selects the single closest upper tier for each of your website’s origins with no configuration required, using our in-house performance and routing data. Cloudflare collects latency data for each request to an origin, and uses the latency data to determine how well any upper-tier data center is connected with an origin. As a result, Cloudflare can select the data center with the lowest latency to be the upper-tier for an origin.
///
/// `DELETE /zones/{zone_id}/cache/tiered_cache_smart_topology_enable`
Future<ApiResult<ResponseCommon10, Never>> smartTieredCacheDeleteSmartTieredCacheSetting({required CacheRulesIdentifier zoneId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'DELETE',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/tiered_cache_smart_topology_enable',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Shared execution pipeline: interceptors -> send -> deserialize.
Future<ApiResult<T, E>> _execute<T,E>(ApiRequest request, {required T Function(ApiResponse) onSuccess, E? Function(ApiResponse)? onError, }) async  { try {
  final cancelToken = request.options?.cancelToken;
  if (cancelToken?.isCancelled ?? false) throw const CancelledException();

  final effectiveTimeout = request.options?.timeout ?? _config.timeout;
  final extraHeaders = request.options?.extraHeaders;
  final effectiveRequest = extraHeaders != null
      ? request.copyWith(headers: {...request.headers, ...extraHeaders})
      : request;

  final chain = buildInterceptorChain(
    interceptors: _config.interceptors,
    terminal: (req) async {
      if (cancelToken?.isCancelled ?? false) throw const CancelledException();
      final future = _config.client.send(req);
      return effectiveTimeout != null
          ? await future.timeout(effectiveTimeout)
          : await future;
    },
  );

  final response = await chain(effectiveRequest);

  try {
    if (response.isSuccessful) {
      return ApiSuccess(
        onSuccess(response),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    return ApiError(
      statusCode: response.statusCode,
      error: onError != null ? onError(response) : null,
      rawError: response.body,
      headers: response.headers,
    );
  } catch (e, st) {
    return ApiParseException(e, st, response: response);
  }
} catch (e, st) {
  return ApiException(e, st);
}
 } 
 }
