//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'dart:convert';import 'package:degenerate_runtime/degenerate_runtime.dart';import '../models/response_common69.dart';import '../models/tunnel_account_id.dart';import '../models/tunnel_components_schemas_tunnel_id.dart';import '../models/tunnel_existed_at.dart';import '../models/tunnel_hostname.dart';import '../models/tunnel_hostname_query_comment.dart';import '../models/tunnel_hostname_route_id.dart';import '../models/tunnel_page_number.dart';import '../models/tunnel_per_page.dart';import '../models/zero_trust_networks_route_hostname_create_request.dart';import '../models/zero_trust_networks_route_hostname_update_request.dart';/// ZeroTrustHostnameRouteApi operations.
///
/// All operations return [ApiResult] — use pattern matching to handle
/// success, error, and exception cases.
final class ZeroTrustHostnameRouteApi {const ZeroTrustHostnameRouteApi(this._config);

final ApiConfig _config;

/// List hostname routes
///
/// Lists and filters hostname routes in an account.
///
/// `GET /accounts/{account_id}/zerotrust/routes/hostname`
Future<ApiResult<ResponseCommon69, Never>> zeroTrustNetworksRouteHostnameList({required TunnelAccountId accountId, TunnelHostnameRouteId? id, TunnelHostname? hostname, TunnelComponentsSchemasTunnelId? tunnelId, TunnelHostnameQueryComment? comment, TunnelExistedAt? existedAt, bool? isDeleted, TunnelPerPage? perPage, TunnelPageNumber? page, RequestOptions? options, }) async  { final queryParameters = <String, String>{..._config.defaultQueryParameters};
final queryParametersList = <ApiQueryParameter>[];
if (id != null) queryParameters['id'] = id.toString();
if (hostname != null) queryParameters['hostname'] = hostname.toString();
if (tunnelId != null) queryParameters['tunnel_id'] = tunnelId.toString();
if (comment != null) queryParameters['comment'] = comment.toString();
if (existedAt != null) queryParameters['existed_at'] = existedAt.toString();
if (isDeleted != null) queryParameters['is_deleted'] = isDeleted.toString();
if (perPage != null) queryParameters['per_page'] = perPage.toString();
if (page != null) queryParameters['page'] = page.toString();

final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/zerotrust/routes/hostname',
  headers: headers,
  queryParameters: queryParameters,
  queryParametersList: queryParametersList,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon69.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Create hostname route
///
/// Create a hostname route.
///
/// `POST /accounts/{account_id}/zerotrust/routes/hostname`
Future<ApiResult<ResponseCommon69, Never>> zeroTrustNetworksRouteHostnameCreate({required TunnelAccountId accountId, required ZeroTrustNetworksRouteHostnameCreateRequest body, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'POST',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/zerotrust/routes/hostname',
  headers: headers,
  body: jsonEncode(body.toJson()),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon69.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Get hostname route
///
/// Get a hostname route.
///
/// `GET /accounts/{account_id}/zerotrust/routes/hostname/{hostname_route_id}`
Future<ApiResult<ResponseCommon69, Never>> zeroTrustNetworksRouteHostnameGet({required TunnelAccountId accountId, required TunnelHostnameRouteId hostnameRouteId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/zerotrust/routes/hostname/${Uri.encodeComponent(hostnameRouteId.toString())}',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon69.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Update hostname route
///
/// Updates a hostname route.
///
/// `PATCH /accounts/{account_id}/zerotrust/routes/hostname/{hostname_route_id}`
Future<ApiResult<ResponseCommon69, Never>> zeroTrustNetworksRouteHostnameUpdate({required TunnelAccountId accountId, required TunnelHostnameRouteId hostnameRouteId, required ZeroTrustNetworksRouteHostnameUpdateRequest body, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'PATCH',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/zerotrust/routes/hostname/${Uri.encodeComponent(hostnameRouteId.toString())}',
  headers: headers,
  body: jsonEncode(body.toJson()),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon69.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Delete hostname route
///
/// Delete a hostname route.
///
/// `DELETE /accounts/{account_id}/zerotrust/routes/hostname/{hostname_route_id}`
Future<ApiResult<ResponseCommon69, Never>> zeroTrustNetworksRouteHostnameDelete({required TunnelAccountId accountId, required TunnelHostnameRouteId hostnameRouteId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'DELETE',
  path: '/accounts/${Uri.encodeComponent(accountId.toString())}/zerotrust/routes/hostname/${Uri.encodeComponent(hostnameRouteId.toString())}',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon69.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Shared execution pipeline: interceptors -> send -> deserialize.
Future<ApiResult<T, E>> _execute<T,E>(ApiRequest request, {required T Function(ApiResponse) onSuccess, E? Function(ApiResponse)? onError, }) async  { try {
  final cancelToken = request.options?.cancelToken;
  if (cancelToken?.isCancelled ?? false) throw const CancelledException();

  final effectiveTimeout = request.options?.timeout ?? _config.timeout;
  final extraHeaders = request.options?.extraHeaders;
  final effectiveRequest = extraHeaders != null
      ? request.copyWith(headers: {...request.headers, ...extraHeaders})
      : request;

  final chain = buildInterceptorChain(
    interceptors: _config.interceptors,
    terminal: (req) async {
      if (cancelToken?.isCancelled ?? false) throw const CancelledException();
      final future = _config.client.send(req);
      return effectiveTimeout != null
          ? await future.timeout(effectiveTimeout)
          : await future;
    },
  );

  final response = await chain(effectiveRequest);

  try {
    if (response.isSuccessful) {
      return ApiSuccess(
        onSuccess(response),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    return ApiError(
      statusCode: response.statusCode,
      error: onError != null ? onError(response) : null,
      rawError: response.body,
      headers: response.headers,
    );
  } catch (e, st) {
    return ApiParseException(e, st, response: response);
  }
} catch (e, st) {
  return ApiException(e, st);
}
 } 
 }
