//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'dart:convert';import 'package:degenerate_runtime/degenerate_runtime.dart';import '../models/cache_rules_identifier.dart';import '../models/response_common10.dart';import '../models/zone_cache_settings_change_cache_reserve_setting_request.dart';import '../models/zone_cache_settings_change_regional_tiered_cache_setting_request.dart';import '../models/zone_cache_settings_change_variants_setting_request.dart';/// ZoneCacheSettingsApi operations.
///
/// All operations return [ApiResult] — use pattern matching to handle
/// success, error, and exception cases.
final class ZoneCacheSettingsApi {const ZoneCacheSettingsApi(this._config);

final ApiConfig _config;

/// Get Cache Reserve setting
///
/// Increase cache lifetimes by automatically storing all cacheable files into Cloudflare's persistent object storage buckets. Requires Cache Reserve subscription. Note: using Tiered Cache with Cache Reserve is highly recommended to reduce Reserve operations costs. See the [developer docs](https://developers.cloudflare.com/cache/about/cache-reserve) for more information.
///
/// `GET /zones/{zone_id}/cache/cache_reserve`
Future<ApiResult<ResponseCommon10, Never>> zoneCacheSettingsGetCacheReserveSetting({required CacheRulesIdentifier zoneId}) async  { final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/cache_reserve',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Change Cache Reserve setting
///
/// Increase cache lifetimes by automatically storing all cacheable files into Cloudflare's persistent object storage buckets. Requires Cache Reserve subscription. Note: using Tiered Cache with Cache Reserve is highly recommended to reduce Reserve operations costs. See the [developer docs](https://developers.cloudflare.com/cache/about/cache-reserve) for more information.
///
/// `PATCH /zones/{zone_id}/cache/cache_reserve`
Future<ApiResult<ResponseCommon10, Never>> zoneCacheSettingsChangeCacheReserveSetting({required CacheRulesIdentifier zoneId, required ZoneCacheSettingsChangeCacheReserveSettingRequest body, }) async  { final request = ApiRequest(
  method: 'PATCH',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/cache_reserve',
  headers: {..._config.defaultHeaders
    , 'Content-Type': 'application/json'
  },
  body: jsonEncode(body.toJson()),
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Get Cache Reserve Clear
///
/// You can use Cache Reserve Clear to clear your Cache Reserve, but you must first disable Cache Reserve. In most cases, this will be accomplished within 24 hours. You cannot re-enable Cache Reserve while this process is ongoing. Keep in mind that you cannot undo or cancel this operation.
///
/// `GET /zones/{zone_id}/cache/cache_reserve_clear`
Future<ApiResult<ResponseCommon10, Never>> zoneCacheSettingsGetCacheReserveClear({required CacheRulesIdentifier zoneId}) async  { final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/cache_reserve_clear',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Start Cache Reserve Clear
///
/// You can use Cache Reserve Clear to clear your Cache Reserve, but you must first disable Cache Reserve. In most cases, this will be accomplished within 24 hours. You cannot re-enable Cache Reserve while this process is ongoing. Keep in mind that you cannot undo or cancel this operation.
///
/// `POST /zones/{zone_id}/cache/cache_reserve_clear`
Future<ApiResult<ResponseCommon10, Never>> zoneCacheSettingsStartCacheReserveClear({required CacheRulesIdentifier zoneId}) async  { final request = ApiRequest(
  method: 'POST',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/cache_reserve_clear',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Get Regional Tiered Cache setting
///
/// Instructs Cloudflare to check a regional hub data center on the way to your upper tier. This can help improve performance for smart and custom tiered cache topologies.
///
/// `GET /zones/{zone_id}/cache/regional_tiered_cache`
Future<ApiResult<ResponseCommon10, Never>> zoneCacheSettingsGetRegionalTieredCacheSetting({required CacheRulesIdentifier zoneId}) async  { final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/regional_tiered_cache',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Change Regional Tiered Cache setting
///
/// Instructs Cloudflare to check a regional hub data center on the way to your upper tier. This can help improve performance for smart and custom tiered cache topologies.
///
/// `PATCH /zones/{zone_id}/cache/regional_tiered_cache`
Future<ApiResult<ResponseCommon10, Never>> zoneCacheSettingsChangeRegionalTieredCacheSetting({required CacheRulesIdentifier zoneId, required ZoneCacheSettingsChangeRegionalTieredCacheSettingRequest body, }) async  { final request = ApiRequest(
  method: 'PATCH',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/regional_tiered_cache',
  headers: {..._config.defaultHeaders
    , 'Content-Type': 'application/json'
  },
  body: jsonEncode(body.toJson()),
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Get variants setting
///
/// Variant support enables caching variants of images with certain file extensions in addition to the original. This only applies when the origin server sends the 'Vary: Accept' response header. If the origin server sends 'Vary: Accept' but does not serve the variant requested, the response will not be cached. This will be indicated with BYPASS cache status in the response headers.
///
/// `GET /zones/{zone_id}/cache/variants`
Future<ApiResult<ResponseCommon10, Never>> zoneCacheSettingsGetVariantsSetting({required CacheRulesIdentifier zoneId}) async  { final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/variants',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Change variants setting
///
/// Variant support enables caching variants of images with certain file extensions in addition to the original. This only applies when the origin server sends the 'Vary: Accept' response header. If the origin server sends 'Vary: Accept' but does not serve the variant requested, the response will not be cached. This will be indicated with BYPASS cache status in the response headers.
///
/// `PATCH /zones/{zone_id}/cache/variants`
Future<ApiResult<ResponseCommon10, Never>> zoneCacheSettingsChangeVariantsSetting({required CacheRulesIdentifier zoneId, required ZoneCacheSettingsChangeVariantsSettingRequest body, }) async  { final request = ApiRequest(
  method: 'PATCH',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/variants',
  headers: {..._config.defaultHeaders
    , 'Content-Type': 'application/json'
  },
  body: jsonEncode(body.toJson()),
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Delete variants setting
///
/// Variant support enables caching variants of images with certain file extensions in addition to the original. This only applies when the origin server sends the 'Vary: Accept' response header. If the origin server sends 'Vary: Accept' but does not serve the variant requested, the response will not be cached. This will be indicated with BYPASS cache status in the response headers.
///
/// `DELETE /zones/{zone_id}/cache/variants`
Future<ApiResult<ResponseCommon10, Never>> zoneCacheSettingsDeleteVariantsSetting({required CacheRulesIdentifier zoneId}) async  { final request = ApiRequest(
  method: 'DELETE',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/cache/variants',
  headers: {..._config.defaultHeaders
  },
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon10.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Shared execution pipeline: interceptors -> send -> deserialize.
Future<ApiResult<T, E>> _execute<T,E>(ApiRequest request, {required T Function(ApiResponse) onSuccess, E? Function(ApiResponse)? onError, }) async  { try {
  final chain = buildInterceptorChain(
    interceptors: _config.interceptors,
    terminal: (req) async {
      return _config.timeout != null
          ? await _config.client.send(req).timeout(_config.timeout!)
          : await _config.client.send(req);
    },
  );

  final response = await chain(request);

  if (response.isSuccessful) {
    return ApiSuccess(
      onSuccess(response),
      statusCode: response.statusCode,
      headers: response.headers,
    );
  }
  return ApiError(
    statusCode: response.statusCode,
    error: onError != null ? onError(response) : null,
    rawBody: response.body,
    headers: response.headers,
  );
} catch (e, st) {
  return ApiException(e, st);
}
 } 
 }
