//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'dart:convert';import 'package:degenerate_runtime/degenerate_runtime.dart';import '../models/access_identifier.dart';import '../models/access_uuid.dart';import '../models/response_common3.dart';import '../models/zone_level_access_mtls_authentication_add_an_mtls_certificate_request.dart';import '../models/zone_level_access_mtls_authentication_update_an_mtls_certificate_request.dart';import '../models/zone_level_access_mtls_authentication_update_an_mtls_certificate_settings_request.dart';/// ZoneLevelAccessMTlsAuthenticationApi operations.
///
/// All operations return [ApiResult] — use pattern matching to handle
/// success, error, and exception cases.
final class ZoneLevelAccessMTlsAuthenticationApi {const ZoneLevelAccessMTlsAuthenticationApi(this._config);

final ApiConfig _config;

/// List mTLS certificates
///
/// Lists all mTLS certificates.
///
/// `GET /zones/{zone_id}/access/certificates`
Future<ApiResult<ResponseCommon3, Never>> zoneLevelAccessMtlsAuthenticationListMtlsCertificates({required AccessIdentifier zoneId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/access/certificates',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon3.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Add an mTLS certificate
///
/// Adds a new mTLS root certificate to Access.
///
/// `POST /zones/{zone_id}/access/certificates`
Future<ApiResult<ResponseCommon3, Never>> zoneLevelAccessMtlsAuthenticationAddAnMtlsCertificate({required AccessIdentifier zoneId, required ZoneLevelAccessMtlsAuthenticationAddAnMtlsCertificateRequest body, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'POST',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/access/certificates',
  headers: headers,
  body: jsonEncode(body.toJson()),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon3.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Get an mTLS certificate
///
/// Fetches a single mTLS certificate.
///
/// `GET /zones/{zone_id}/access/certificates/{certificate_id}`
Future<ApiResult<ResponseCommon3, Never>> zoneLevelAccessMtlsAuthenticationGetAnMtlsCertificate({required AccessUuid certificateId, required AccessIdentifier zoneId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/access/certificates/${Uri.encodeComponent(certificateId.toString())}',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon3.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Update an mTLS certificate
///
/// Updates a configured mTLS certificate.
///
/// `PUT /zones/{zone_id}/access/certificates/{certificate_id}`
Future<ApiResult<ResponseCommon3, Never>> zoneLevelAccessMtlsAuthenticationUpdateAnMtlsCertificate({required AccessUuid certificateId, required AccessIdentifier zoneId, required ZoneLevelAccessMtlsAuthenticationUpdateAnMtlsCertificateRequest body, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'PUT',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/access/certificates/${Uri.encodeComponent(certificateId.toString())}',
  headers: headers,
  body: jsonEncode(body.toJson()),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon3.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Delete an mTLS certificate
///
/// Deletes an mTLS certificate.
///
/// `DELETE /zones/{zone_id}/access/certificates/{certificate_id}`
Future<ApiResult<ResponseCommon3, Never>> zoneLevelAccessMtlsAuthenticationDeleteAnMtlsCertificate({required AccessUuid certificateId, required AccessIdentifier zoneId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'DELETE',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/access/certificates/${Uri.encodeComponent(certificateId.toString())}',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon3.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// List all mTLS hostname settings
///
/// List all mTLS hostname settings for this zone.
///
/// `GET /zones/{zone_id}/access/certificates/settings`
Future<ApiResult<ResponseCommon3, Never>> zoneLevelAccessMtlsAuthenticationListMtlsCertificatesHostnameSettings({required AccessIdentifier zoneId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/access/certificates/settings',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon3.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Update an mTLS certificate's hostname settings
///
/// Updates an mTLS certificate's hostname settings.
///
/// `PUT /zones/{zone_id}/access/certificates/settings`
Future<ApiResult<ResponseCommon3, Never>> zoneLevelAccessMtlsAuthenticationUpdateAnMtlsCertificateSettings({required AccessIdentifier zoneId, required ZoneLevelAccessMtlsAuthenticationUpdateAnMtlsCertificateSettingsRequest body, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'PUT',
  path: '/zones/${Uri.encodeComponent(zoneId.toString())}/access/certificates/settings',
  headers: headers,
  body: jsonEncode(body.toJson()),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ResponseCommon3.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Shared execution pipeline: interceptors -> send -> deserialize.
Future<ApiResult<T, E>> _execute<T,E>(ApiRequest request, {required T Function(ApiResponse) onSuccess, E? Function(ApiResponse)? onError, }) async  { try {
  final cancelToken = request.options?.cancelToken;
  if (cancelToken?.isCancelled ?? false) throw const CancelledException();

  final effectiveTimeout = request.options?.timeout ?? _config.timeout;
  final extraHeaders = request.options?.extraHeaders;
  final effectiveRequest = extraHeaders != null
      ? request.copyWith(headers: {...request.headers, ...extraHeaders})
      : request;

  final chain = buildInterceptorChain(
    interceptors: _config.interceptors,
    terminal: (req) async {
      if (cancelToken?.isCancelled ?? false) throw const CancelledException();
      final future = _config.client.send(req);
      return effectiveTimeout != null
          ? await future.timeout(effectiveTimeout)
          : await future;
    },
  );

  final response = await chain(effectiveRequest);

  try {
    if (response.isSuccessful) {
      return ApiSuccess(
        onSuccess(response),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    return ApiError(
      statusCode: response.statusCode,
      error: onError != null ? onError(response) : null,
      rawError: response.body,
      headers: response.headers,
    );
  } catch (e, st) {
    return ApiParseException(e, st, response: response);
  }
} catch (e, st) {
  return ApiException(e, st);
}
 } 
 }
