//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from openai.yml
//  OpenAPI spec version: 3.1.0

/// Allows to set transparency for the background of the generated image(s).
/// This parameter is only supported for the GPT image models. Must be one of
/// `transparent`, `opaque` or `auto` (default value). When `auto` is used, the
/// model will automatically determine the best background for the image.
/// 
/// If `transparent`, the output format needs to support transparency, so it
/// should be set to either `png` (default value) or `webp`.
/// 
final class CreateImageRequestBackground {const CreateImageRequestBackground._(this.value);

factory CreateImageRequestBackground.fromJson(String json) { return switch (json) {
  'transparent' => transparent,
  'opaque' => opaque,
  'auto' => auto,
  _ => CreateImageRequestBackground._(json),
}; }

static const CreateImageRequestBackground transparent = CreateImageRequestBackground._('transparent');

static const CreateImageRequestBackground opaque = CreateImageRequestBackground._('opaque');

static const CreateImageRequestBackground auto = CreateImageRequestBackground._('auto');

static const List<CreateImageRequestBackground> values = [transparent, opaque, auto];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is CreateImageRequestBackground && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'CreateImageRequestBackground($value)'; } 
 }
