//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from openai.yml
//  OpenAPI spec version: 3.1.0

/// The event type, must be `response.mcp_call.completed`.
final class RealtimeBetaServerEventResponseMcpCallCompletedType {const RealtimeBetaServerEventResponseMcpCallCompletedType._(this.value);

factory RealtimeBetaServerEventResponseMcpCallCompletedType.fromJson(String json) { return switch (json) {
  'response.mcp_call.completed' => responseMcpCallCompleted,
  _ => RealtimeBetaServerEventResponseMcpCallCompletedType._(json),
}; }

static const RealtimeBetaServerEventResponseMcpCallCompletedType responseMcpCallCompleted = RealtimeBetaServerEventResponseMcpCallCompletedType._('response.mcp_call.completed');

static const List<RealtimeBetaServerEventResponseMcpCallCompletedType> values = [responseMcpCallCompleted];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RealtimeBetaServerEventResponseMcpCallCompletedType && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'RealtimeBetaServerEventResponseMcpCallCompletedType($value)'; } 
 }
