//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from openai.yml
//  OpenAPI spec version: 3.1.0

/// The event type, must be `conversation.item.retrieved`.
final class RealtimeServerEventConversationItemRetrievedType {
  const RealtimeServerEventConversationItemRetrievedType._(this.value);

  factory RealtimeServerEventConversationItemRetrievedType.fromJson(
    String json,
  ) {
    return switch (json) {
      'conversation.item.retrieved' => conversationItemRetrieved,
      _ => RealtimeServerEventConversationItemRetrievedType._(json),
    };
  }

  static const RealtimeServerEventConversationItemRetrievedType
  conversationItemRetrieved =
      RealtimeServerEventConversationItemRetrievedType._(
        'conversation.item.retrieved',
      );

  static const List<RealtimeServerEventConversationItemRetrievedType> values = [
    conversationItemRetrieved,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is RealtimeServerEventConversationItemRetrievedType &&
            other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'RealtimeServerEventConversationItemRetrievedType($value)';
  }
}
