//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// The status of the Sofort payments capability of the account, or whether the account can directly process Sofort charges.
final class AccountCapabilitiesSofortPayments {const AccountCapabilitiesSofortPayments._(this.value);

factory AccountCapabilitiesSofortPayments.fromJson(String json) { return switch (json) {
  'active' => active,
  'inactive' => inactive,
  'pending' => pending,
  _ => AccountCapabilitiesSofortPayments._(json),
}; }

static const AccountCapabilitiesSofortPayments active = AccountCapabilitiesSofortPayments._('active');

static const AccountCapabilitiesSofortPayments inactive = AccountCapabilitiesSofortPayments._('inactive');

static const AccountCapabilitiesSofortPayments pending = AccountCapabilitiesSofortPayments._('pending');

static const List<AccountCapabilitiesSofortPayments> values = [active, inactive, pending];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is AccountCapabilitiesSofortPayments && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'AccountCapabilitiesSofortPayments($value)'; } 
 }
