//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class CanceledCancellationPolicyProvidedVariant2 {const CanceledCancellationPolicyProvidedVariant2._(this.value);

factory CanceledCancellationPolicyProvidedVariant2.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => CanceledCancellationPolicyProvidedVariant2._(json),
}; }

static const CanceledCancellationPolicyProvidedVariant2 $empty = CanceledCancellationPolicyProvidedVariant2._('');

static const List<CanceledCancellationPolicyProvidedVariant2> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is CanceledCancellationPolicyProvidedVariant2 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'CanceledCancellationPolicyProvidedVariant2($value)'; } 
 }
final class CanceledCancellationPolicyProvided {const CanceledCancellationPolicyProvided({this.$bool, this.canceledCancellationPolicyProvidedVariant2, });

factory CanceledCancellationPolicyProvided.fromJson(Object? json) { return CanceledCancellationPolicyProvided(
  $bool: json is bool ? json : null,
  canceledCancellationPolicyProvidedVariant2: json is String ? CanceledCancellationPolicyProvidedVariant2.fromJson(json) : null,
); }

final bool? $bool;

final CanceledCancellationPolicyProvidedVariant2? canceledCancellationPolicyProvidedVariant2;

/// At least one variant must be present.
bool get isValid { return $bool != null || canceledCancellationPolicyProvidedVariant2 != null; } 
Map<String, dynamic> toJson() { return {
  '$bool': ?$bool,
  if (canceledCancellationPolicyProvidedVariant2 != null) 'canceledCancellationPolicyProvidedVariant2': canceledCancellationPolicyProvidedVariant2!.toJson(),
}; } 
 }
