//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'package:collection/collection.dart';final class ExternalAccountPayoutBankAccount3DocumentsBankAccountOwnershipVerification {const ExternalAccountPayoutBankAccount3DocumentsBankAccountOwnershipVerification({this.files});

factory ExternalAccountPayoutBankAccount3DocumentsBankAccountOwnershipVerification.fromJson(Map<String, dynamic> json) { return ExternalAccountPayoutBankAccount3DocumentsBankAccountOwnershipVerification(
  files: (json['files'] as List<dynamic>?)?.map((e) => e as String).toList(),
); }

final List<String>? files;

Map<String, dynamic> toJson() { return {
  'files': ?files,
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
ExternalAccountPayoutBankAccount3DocumentsBankAccountOwnershipVerification copyWith({List<String> Function()? files}) { return ExternalAccountPayoutBankAccount3DocumentsBankAccountOwnershipVerification(
  files: files != null ? files() : this.files,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ExternalAccountPayoutBankAccount3DocumentsBankAccountOwnershipVerification &&
          const ListEquality<dynamic>().equals(files, other.files); } 
@override int get hashCode { return Object.hashAll(files ?? const []).hashCode; } 
@override String toString() { return 'ExternalAccountPayoutBankAccount3DocumentsBankAccountOwnershipVerification(files: $files)'; } 
 }
