//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'package:collection/collection.dart';import 'forwarding_request_object.dart';import 'forwarding_request_replacements.dart';import 'forwarding_request_request_context.dart';import 'forwarding_request_request_details.dart';import 'forwarding_request_response_details.dart';/// Instructs Stripe to make a request on your behalf using the destination URL. The destination URL
/// is activated by Stripe at the time of onboarding. Stripe verifies requests with your credentials
/// provided during onboarding, and injects card details from the payment_method into the request.
/// 
/// Stripe redacts all sensitive fields and headers, including authentication credentials and card numbers,
/// before storing the request and response data in the forwarding Request object, which are subject to a
/// 30-day retention period.
/// 
/// You can provide a Stripe idempotency key to make sure that requests with the same key result in only one
/// outbound request. The Stripe idempotency key provided should be unique and different from any idempotency
/// keys provided on the underlying third-party request.
/// 
/// Forwarding Requests are synchronous requests that return a response or time out according to
/// Stripe’s limits.
/// 
/// Related guide: [Forward card details to third-party API endpoints](https://docs.stripe.com/payments/forwarding).
final class ForwardingRequest {const ForwardingRequest({required this.created, required this.id, required this.livemode, this.metadata, required this.object, required this.paymentMethod, required this.replacements, this.requestContext, this.requestDetails, this.responseDetails, this.url, });

factory ForwardingRequest.fromJson(Map<String, dynamic> json) { return ForwardingRequest(
  created: (json['created'] as num).toInt(),
  id: json['id'] as String,
  livemode: json['livemode'] as bool,
  metadata: (json['metadata'] as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, v as String)),
  object: ForwardingRequestObject.fromJson(json['object'] as String),
  paymentMethod: json['payment_method'] as String,
  replacements: (json['replacements'] as List<dynamic>).map((e) => ForwardingRequestReplacements.fromJson(e as String)).toList(),
  requestContext: json['request_context'] != null
        ? ForwardingRequestRequestContext.fromJson(json['request_context'] as Map<String, dynamic>)
        : null,
  requestDetails: json['request_details'] != null
        ? ForwardingRequestRequestDetails.fromJson(json['request_details'] as Map<String, dynamic>)
        : null,
  responseDetails: json['response_details'] != null
        ? ForwardingRequestResponseDetails.fromJson(json['response_details'] as Map<String, dynamic>)
        : null,
  url: json['url'] as String?,
); }

/// Time at which the object was created. Measured in seconds since the Unix epoch.
final int created;

/// Unique identifier for the object.
final String id;

/// Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
final bool livemode;

/// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
final Map<String,String>? metadata;

/// String representing the object's type. Objects of the same type share the same value.
final ForwardingRequestObject object;

/// The PaymentMethod to insert into the forwarded request. Forwarding previously consumed PaymentMethods is allowed.
final String paymentMethod;

/// The field kinds to be replaced in the forwarded request.
final List<ForwardingRequestReplacements> replacements;

/// Context about the request from Stripe's servers to the destination endpoint.
final ForwardingRequestRequestContext? requestContext;

/// The request that was sent to the destination endpoint. We redact any sensitive fields.
final ForwardingRequestRequestDetails? requestDetails;

/// The response that the destination endpoint returned to us. We redact any sensitive fields.
final ForwardingRequestResponseDetails? responseDetails;

/// The destination URL for the forwarded request. Must be supported by the config.
final String? url;

Map<String, dynamic> toJson() { return {
  'created': created,
  'id': id,
  'livemode': livemode,
  'metadata': ?metadata,
  'object': object.toJson(),
  'payment_method': paymentMethod,
  'replacements': replacements.map((e) => e.toJson()).toList(),
  if (requestContext != null) 'request_context': requestContext?.toJson(),
  if (requestDetails != null) 'request_details': requestDetails?.toJson(),
  if (responseDetails != null) 'response_details': responseDetails?.toJson(),
  'url': ?url,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('created') && json['created'] is num &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('livemode') && json['livemode'] is bool &&
      json.containsKey('object') &&
      json.containsKey('payment_method') && json['payment_method'] is String &&
      json.containsKey('replacements'); } 
ForwardingRequest copyWith({int? created, String? id, bool? livemode, Map<String, String>? Function()? metadata, ForwardingRequestObject? object, String? paymentMethod, List<ForwardingRequestReplacements>? replacements, ForwardingRequestRequestContext? Function()? requestContext, ForwardingRequestRequestDetails? Function()? requestDetails, ForwardingRequestResponseDetails? Function()? responseDetails, String? Function()? url, }) { return ForwardingRequest(
  created: created ?? this.created,
  id: id ?? this.id,
  livemode: livemode ?? this.livemode,
  metadata: metadata != null ? metadata() : this.metadata,
  object: object ?? this.object,
  paymentMethod: paymentMethod ?? this.paymentMethod,
  replacements: replacements ?? this.replacements,
  requestContext: requestContext != null ? requestContext() : this.requestContext,
  requestDetails: requestDetails != null ? requestDetails() : this.requestDetails,
  responseDetails: responseDetails != null ? responseDetails() : this.responseDetails,
  url: url != null ? url() : this.url,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ForwardingRequest &&
          created == other.created &&
          id == other.id &&
          livemode == other.livemode &&
          metadata == other.metadata &&
          object == other.object &&
          paymentMethod == other.paymentMethod &&
          const ListEquality<dynamic>().equals(replacements, other.replacements) &&
          requestContext == other.requestContext &&
          requestDetails == other.requestDetails &&
          responseDetails == other.responseDetails &&
          url == other.url; } 
@override int get hashCode { return Object.hash(created, id, livemode, metadata, object, paymentMethod, Object.hashAll(replacements), requestContext, requestDetails, responseDetails, url); } 
@override String toString() { return 'ForwardingRequest(created: $created, id: $id, livemode: $livemode, metadata: $metadata, object: $object, paymentMethod: $paymentMethod, replacements: $replacements, requestContext: $requestContext, requestDetails: $requestDetails, responseDetails: $responseDetails, url: $url)'; } 
 }
