//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject950 {const InlineObject950._(this.value);

factory InlineObject950.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => InlineObject950._(json),
}; }

static const InlineObject950 $empty = InlineObject950._('');

static const List<InlineObject950> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject950 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject950($value)'; } 
 }
final class InlineObject949Amount {const InlineObject949Amount({this.$int, this.inlineObject950, });

factory InlineObject949Amount.fromJson(Object? json) { return InlineObject949Amount(
  $int: json is num ? json.toInt() : null,
  inlineObject950: json is String ? InlineObject950.fromJson(json) : null,
); }

final int? $int;

final InlineObject950? inlineObject950;

/// At least one variant must be present.
bool get isValid { return $int != null || inlineObject950 != null; } 
Map<String, dynamic> toJson() { return {
  '$int': ?$int,
  if (inlineObject950 != null) 'inlineObject950': inlineObject950!.toJson(),
}; } 
 }
