//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'inline_object763_mandate_options.dart';final class InlineObject763SetupFutureUsage {const InlineObject763SetupFutureUsage._(this.value);

factory InlineObject763SetupFutureUsage.fromJson(String json) { return switch (json) {
  '' => $empty,
  'none' => none,
  'off_session' => offSession,
  'on_session' => onSession,
  _ => InlineObject763SetupFutureUsage._(json),
}; }

static const InlineObject763SetupFutureUsage $empty = InlineObject763SetupFutureUsage._('');

static const InlineObject763SetupFutureUsage none = InlineObject763SetupFutureUsage._('none');

static const InlineObject763SetupFutureUsage offSession = InlineObject763SetupFutureUsage._('off_session');

static const InlineObject763SetupFutureUsage onSession = InlineObject763SetupFutureUsage._('on_session');

static const List<InlineObject763SetupFutureUsage> values = [$empty, none, offSession, onSession];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject763SetupFutureUsage && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject763SetupFutureUsage($value)'; } 
 }
final class InlineObject763 {const InlineObject763({this.mandateOptions, this.setupFutureUsage, this.targetDate, });

factory InlineObject763.fromJson(Map<String, dynamic> json) { return InlineObject763(
  mandateOptions: json['mandate_options'] != null
        ? InlineObject763MandateOptions.fromJson(json['mandate_options'] as Map<String, dynamic>)
        : null,
  setupFutureUsage: json['setup_future_usage'] != null ? InlineObject763SetupFutureUsage.fromJson(json['setup_future_usage'] as String) : null,
  targetDate: json['target_date'] as String?,
); }

final InlineObject763MandateOptions? mandateOptions;

final InlineObject763SetupFutureUsage? setupFutureUsage;

final String? targetDate;

Map<String, dynamic> toJson() { return {
  if (mandateOptions != null) 'mandate_options': mandateOptions?.toJson(),
  if (setupFutureUsage != null) 'setup_future_usage': setupFutureUsage?.toJson(),
  'target_date': ?targetDate,
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
InlineObject763 copyWith({InlineObject763MandateOptions Function()? mandateOptions, InlineObject763SetupFutureUsage Function()? setupFutureUsage, String Function()? targetDate, }) { return InlineObject763(
  mandateOptions: mandateOptions != null ? mandateOptions() : this.mandateOptions,
  setupFutureUsage: setupFutureUsage != null ? setupFutureUsage() : this.setupFutureUsage,
  targetDate: targetDate != null ? targetDate() : this.targetDate,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is InlineObject763 &&
          mandateOptions == other.mandateOptions &&
          setupFutureUsage == other.setupFutureUsage &&
          targetDate == other.targetDate; } 
@override int get hashCode { return Object.hash(mandateOptions, setupFutureUsage, targetDate); } 
@override String toString() { return 'InlineObject763(mandateOptions: $mandateOptions, setupFutureUsage: $setupFutureUsage, targetDate: $targetDate)'; } 
 }
