//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// The digital wallet used for this transaction. One of `apple_pay`, `google_pay`, or `samsung_pay`.
final class IssuingTransactionWallet {const IssuingTransactionWallet._(this.value);

factory IssuingTransactionWallet.fromJson(String json) { return switch (json) {
  'apple_pay' => applePay,
  'google_pay' => googlePay,
  'samsung_pay' => samsungPay,
  _ => IssuingTransactionWallet._(json),
}; }

static const IssuingTransactionWallet applePay = IssuingTransactionWallet._('apple_pay');

static const IssuingTransactionWallet googlePay = IssuingTransactionWallet._('google_pay');

static const IssuingTransactionWallet samsungPay = IssuingTransactionWallet._('samsung_pay');

static const List<IssuingTransactionWallet> values = [applePay, googlePay, samsungPay];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is IssuingTransactionWallet && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'IssuingTransactionWallet($value)'; } 
 }
