//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'package:degenerate_runtime/degenerate_runtime.dart';final class PaymentIntentParam3StatementDescriptorSuffixKanaVariant2 {const PaymentIntentParam3StatementDescriptorSuffixKanaVariant2._(this.value);

factory PaymentIntentParam3StatementDescriptorSuffixKanaVariant2.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => PaymentIntentParam3StatementDescriptorSuffixKanaVariant2._(json),
}; }

static const PaymentIntentParam3StatementDescriptorSuffixKanaVariant2 $empty = PaymentIntentParam3StatementDescriptorSuffixKanaVariant2._('');

static const List<PaymentIntentParam3StatementDescriptorSuffixKanaVariant2> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PaymentIntentParam3StatementDescriptorSuffixKanaVariant2 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PaymentIntentParam3StatementDescriptorSuffixKanaVariant2($value)'; } 
 }
typedef PaymentIntentParam3StatementDescriptorSuffixKana = OneOf2<String,PaymentIntentParam3StatementDescriptorSuffixKanaVariant2>;