//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'payment_method_options_param98.dart';final class PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2 {const PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2._(this.value);

factory PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2._(json),
}; }

static const PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2 $empty = PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2._('');

static const List<PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2($value)'; } 
 }
final class PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxo {const PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxo({this.paymentMethodOptionsParam98, this.postPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2, });

factory PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxo.fromJson(Object? json) { final map = json is Map<String, dynamic> ? json : null;
return PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxo(
  paymentMethodOptionsParam98: map != null && PaymentMethodOptionsParam98.canParse(map) ? PaymentMethodOptionsParam98.fromJson(map) : null,
  postPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2: json is String ? PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2.fromJson(json) : null,
); }

final PaymentMethodOptionsParam98? paymentMethodOptionsParam98;

final PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2? postPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2;

/// At least one variant must be present.
bool get isValid { return paymentMethodOptionsParam98 != null || postPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2 != null; } 
Map<String, dynamic> toJson() { return {
  ...?paymentMethodOptionsParam98?.toJson(),
  if (postPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2 != null) 'postPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2': postPaymentIntentsIntentConfirmRequestPaymentMethodOptionsOxxoVariant2!.toJson(),
}; } 
 }
