//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'inline_object841.dart';final class InlineObject842 {const InlineObject842._(this.value);

factory InlineObject842.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => InlineObject842._(json),
}; }

static const InlineObject842 $empty = InlineObject842._('');

static const List<InlineObject842> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject842 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject842($value)'; } 
 }
final class PostPaymentIntentsIntentRequestPaymentMethodOptionsCrypto {const PostPaymentIntentsIntentRequestPaymentMethodOptionsCrypto({this.inlineObject841, this.inlineObject842, });

factory PostPaymentIntentsIntentRequestPaymentMethodOptionsCrypto.fromJson(Object? json) { final map = json is Map<String, dynamic> ? json : null;
return PostPaymentIntentsIntentRequestPaymentMethodOptionsCrypto(
  inlineObject841: map != null && InlineObject841.canParse(map) ? InlineObject841.fromJson(map) : null,
  inlineObject842: json is String ? InlineObject842.fromJson(json) : null,
); }

final InlineObject841? inlineObject841;

final InlineObject842? inlineObject842;

/// At least one variant must be present.
bool get isValid { return inlineObject841 != null || inlineObject842 != null; } 
Map<String, dynamic> toJson() { return {
  ...?inlineObject841?.toJson(),
  if (inlineObject842 != null) 'inlineObject842': inlineObject842!.toJson(),
}; } 
 }
