//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'post_billing_portal_configurations_configuration_request_features_customer_update_allowed_updates.dart';import 'post_billing_portal_configurations_configuration_request_features_customer_update_allowed_updates.dart';import 'post_billing_portal_configurations_configuration_request_features_customer_update_allowed_updates.dart';final class PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdate {const PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdate({this.allowedUpdates, this.enabled, });

factory PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdate.fromJson(Map<String, dynamic> json) { return PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdate(
  allowedUpdates: json['allowed_updates'] != null ? OneOf2.parse(json['allowed_updates'], fromA: (v) => (v as List<dynamic>).map((e) => PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdateAllowedUpdatesVariant1.fromJson(e as String)).toList(), fromB: (v) => PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdateAllowedUpdatesVariant2.fromJson(v as String),) : null,
  enabled: json['enabled'] as bool?,
); }

final PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdateAllowedUpdates? allowedUpdates;

final bool? enabled;

Map<String, dynamic> toJson() { return {
  if (allowedUpdates != null) 'allowed_updates': allowedUpdates?.toJson(),
  'enabled': ?enabled,
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdate copyWith({PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdateAllowedUpdates Function()? allowedUpdates, bool Function()? enabled, }) { return PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdate(
  allowedUpdates: allowedUpdates != null ? allowedUpdates() : this.allowedUpdates,
  enabled: enabled != null ? enabled() : this.enabled,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdate &&
          allowedUpdates == other.allowedUpdates &&
          enabled == other.enabled; } 
@override int get hashCode { return Object.hash(allowedUpdates, enabled); } 
@override String toString() { return 'PostBillingPortalConfigurationsConfigurationRequestFeaturesCustomerUpdate(allowedUpdates: $allowedUpdates, enabled: $enabled)'; } 
 }
