//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class PostSetupIntentsIntentRequestPaymentMethodDataOxxo {const PostSetupIntentsIntentRequestPaymentMethodDataOxxo();

factory PostSetupIntentsIntentRequestPaymentMethodDataOxxo.fromJson(Map<String, dynamic> json) { return PostSetupIntentsIntentRequestPaymentMethodDataOxxo(

); }

Map<String, dynamic> toJson() { return {

}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostSetupIntentsIntentRequestPaymentMethodDataOxxo copyWith() { return PostSetupIntentsIntentRequestPaymentMethodDataOxxo(

); } 
@override bool operator ==(Object other) { return identical(this, other) || other is PostSetupIntentsIntentRequestPaymentMethodDataOxxo; } 
@override int get hashCode { return runtimeType.hashCode; } 
@override String toString() { return 'PostSetupIntentsIntentRequestPaymentMethodDataOxxo()'; } 
 }
