//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject60 {const InlineObject60._(this.value);

factory InlineObject60.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => InlineObject60._(json),
}; }

static const InlineObject60 $empty = InlineObject60._('');

static const List<InlineObject60> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject60 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject60($value)'; } 
 }
final class PostAccountsAccountPersonsRequestDocumentsPassportFiles {const PostAccountsAccountPersonsRequestDocumentsPassportFiles({this.string, this.inlineObject60, });

factory PostAccountsAccountPersonsRequestDocumentsPassportFiles.fromJson(Object? json) { return PostAccountsAccountPersonsRequestDocumentsPassportFiles(
  string: json is String ? json : null,
  inlineObject60: json is String ? InlineObject60.fromJson(json) : null,
); }

final String? string;

final InlineObject60? inlineObject60;

/// At least one variant must be present.
bool get isValid { return string != null || inlineObject60 != null; } 
Map<String, dynamic> toJson() { return {
  'string': ?string,
  if (inlineObject60 != null) 'inlineObject60': inlineObject60!.toJson(),
}; } 
 }
