//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class PostProductsRequestDefaultPriceDataTaxBehavior {const PostProductsRequestDefaultPriceDataTaxBehavior._(this.value);

factory PostProductsRequestDefaultPriceDataTaxBehavior.fromJson(String json) { return switch (json) {
  'exclusive' => exclusive,
  'inclusive' => inclusive,
  'unspecified' => unspecified,
  _ => PostProductsRequestDefaultPriceDataTaxBehavior._(json),
}; }

static const PostProductsRequestDefaultPriceDataTaxBehavior exclusive = PostProductsRequestDefaultPriceDataTaxBehavior._('exclusive');

static const PostProductsRequestDefaultPriceDataTaxBehavior inclusive = PostProductsRequestDefaultPriceDataTaxBehavior._('inclusive');

static const PostProductsRequestDefaultPriceDataTaxBehavior unspecified = PostProductsRequestDefaultPriceDataTaxBehavior._('unspecified');

static const List<PostProductsRequestDefaultPriceDataTaxBehavior> values = [exclusive, inclusive, unspecified];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PostProductsRequestDefaultPriceDataTaxBehavior && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PostProductsRequestDefaultPriceDataTaxBehavior($value)'; } 
 }
