//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject1471 {const InlineObject1471._(this.value);

factory InlineObject1471.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => InlineObject1471._(json),
}; }

static const InlineObject1471 $empty = InlineObject1471._('');

static const List<InlineObject1471> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject1471 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject1471($value)'; } 
 }
final class PostTaxCalculationsRequestCustomerDetailsAddressState {const PostTaxCalculationsRequestCustomerDetailsAddressState({this.string, this.inlineObject1471, });

factory PostTaxCalculationsRequestCustomerDetailsAddressState.fromJson(Object? json) { return PostTaxCalculationsRequestCustomerDetailsAddressState(
  string: json is String ? json : null,
  inlineObject1471: json is String ? InlineObject1471.fromJson(json) : null,
); }

final String? string;

final InlineObject1471? inlineObject1471;

/// At least one variant must be present.
bool get isValid { return string != null || inlineObject1471 != null; } 
Map<String, dynamic> toJson() { return {
  'string': ?string,
  if (inlineObject1471 != null) 'inlineObject1471': inlineObject1471!.toJson(),
}; } 
 }
