//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'post_payment_records_report_payment_request_payment_method_details_billing_details.dart';import 'post_payment_records_report_payment_request_payment_method_details_custom.dart';final class PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType {const PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType._(this.value);

factory PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType.fromJson(String json) { return switch (json) {
  'custom' => custom,
  _ => PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType._(json),
}; }

static const PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType custom = PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType._('custom');

static const List<PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType> values = [custom];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType($value)'; } 
 }
/// Information about the Payment Method debited for this payment.
final class PostPaymentRecordsReportPaymentRequestPaymentMethodDetails {const PostPaymentRecordsReportPaymentRequestPaymentMethodDetails({this.billingDetails, this.custom, this.paymentMethod, this.type, });

factory PostPaymentRecordsReportPaymentRequestPaymentMethodDetails.fromJson(Map<String, dynamic> json) { return PostPaymentRecordsReportPaymentRequestPaymentMethodDetails(
  billingDetails: json['billing_details'] != null ? PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsBillingDetails.fromJson(json['billing_details'] as Map<String, dynamic>) : null,
  custom: json['custom'] != null ? PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsCustom.fromJson(json['custom'] as Map<String, dynamic>) : null,
  paymentMethod: json['payment_method'] as String?,
  type: json['type'] != null ? PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType.fromJson(json['type'] as String) : null,
); }

final PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsBillingDetails? billingDetails;

final PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsCustom? custom;

final String? paymentMethod;

final PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType? type;

Map<String, dynamic> toJson() { return {
  if (billingDetails != null) 'billing_details': billingDetails?.toJson(),
  if (custom != null) 'custom': custom?.toJson(),
  'payment_method': ?paymentMethod,
  if (type != null) 'type': type?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostPaymentRecordsReportPaymentRequestPaymentMethodDetails copyWith({PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsBillingDetails Function()? billingDetails, PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsCustom Function()? custom, String Function()? paymentMethod, PostPaymentRecordsReportPaymentRequestPaymentMethodDetailsType Function()? type, }) { return PostPaymentRecordsReportPaymentRequestPaymentMethodDetails(
  billingDetails: billingDetails != null ? billingDetails() : this.billingDetails,
  custom: custom != null ? custom() : this.custom,
  paymentMethod: paymentMethod != null ? paymentMethod() : this.paymentMethod,
  type: type != null ? type() : this.type,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostPaymentRecordsReportPaymentRequestPaymentMethodDetails &&
          billingDetails == other.billingDetails &&
          custom == other.custom &&
          paymentMethod == other.paymentMethod &&
          type == other.type; } 
@override int get hashCode { return Object.hash(billingDetails, custom, paymentMethod, type); } 
@override String toString() { return 'PostPaymentRecordsReportPaymentRequestPaymentMethodDetails(billingDetails: $billingDetails, custom: $custom, paymentMethod: $paymentMethod, type: $type)'; } 
 }
