//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'post_checkout_sessions_request_payment_method_options_p24_setup_future_usage.dart';final class PostCheckoutSessionsRequestPaymentMethodOptionsP24 {const PostCheckoutSessionsRequestPaymentMethodOptionsP24({this.setupFutureUsage, this.tosShownAndAccepted, });

factory PostCheckoutSessionsRequestPaymentMethodOptionsP24.fromJson(Map<String, dynamic> json) { return PostCheckoutSessionsRequestPaymentMethodOptionsP24(
  setupFutureUsage: json['setup_future_usage'] != null ? PostCheckoutSessionsRequestPaymentMethodOptionsP24SetupFutureUsage.fromJson(json['setup_future_usage'] as String) : null,
  tosShownAndAccepted: json['tos_shown_and_accepted'] as bool?,
); }

final PostCheckoutSessionsRequestPaymentMethodOptionsP24SetupFutureUsage? setupFutureUsage;

final bool? tosShownAndAccepted;

Map<String, dynamic> toJson() { return {
  if (setupFutureUsage != null) 'setup_future_usage': setupFutureUsage?.toJson(),
  'tos_shown_and_accepted': ?tosShownAndAccepted,
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostCheckoutSessionsRequestPaymentMethodOptionsP24 copyWith({PostCheckoutSessionsRequestPaymentMethodOptionsP24SetupFutureUsage Function()? setupFutureUsage, bool Function()? tosShownAndAccepted, }) { return PostCheckoutSessionsRequestPaymentMethodOptionsP24(
  setupFutureUsage: setupFutureUsage != null ? setupFutureUsage() : this.setupFutureUsage,
  tosShownAndAccepted: tosShownAndAccepted != null ? tosShownAndAccepted() : this.tosShownAndAccepted,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostCheckoutSessionsRequestPaymentMethodOptionsP24 &&
          setupFutureUsage == other.setupFutureUsage &&
          tosShownAndAccepted == other.tosShownAndAccepted; } 
@override int get hashCode { return Object.hash(setupFutureUsage, tosShownAndAccepted); } 
@override String toString() { return 'PostCheckoutSessionsRequestPaymentMethodOptionsP24(setupFutureUsage: $setupFutureUsage, tosShownAndAccepted: $tosShownAndAccepted)'; } 
 }
