//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject15 {const InlineObject15._(this.value);

factory InlineObject15.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => InlineObject15._(json),
}; }

static const InlineObject15 $empty = InlineObject15._('');

static const List<InlineObject15> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject15 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject15($value)'; } 
 }
final class PostAccountsRequestSettingsCardPaymentsStatementDescriptorPrefixKanji {const PostAccountsRequestSettingsCardPaymentsStatementDescriptorPrefixKanji({this.string, this.inlineObject15, });

factory PostAccountsRequestSettingsCardPaymentsStatementDescriptorPrefixKanji.fromJson(Object? json) { return PostAccountsRequestSettingsCardPaymentsStatementDescriptorPrefixKanji(
  string: json is String ? json : null,
  inlineObject15: json is String ? InlineObject15.fromJson(json) : null,
); }

final String? string;

final InlineObject15? inlineObject15;

/// At least one variant must be present.
bool get isValid { return string != null || inlineObject15 != null; } 
Map<String, dynamic> toJson() { return {
  'string': ?string,
  if (inlineObject15 != null) 'inlineObject15': inlineObject15!.toJson(),
}; } 
 }
