//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'post_payment_intents_request_amount_details_discount_amount.dart';import 'post_payment_intents_request_amount_details_line_items.dart';import 'post_payment_intents_request_amount_details_shipping.dart';import 'post_payment_intents_request_amount_details_tax.dart';/// Provides industry-specific information about the amount.
final class PostPaymentIntentsRequestAmountDetails {const PostPaymentIntentsRequestAmountDetails({this.discountAmount, this.enforceArithmeticValidation, this.lineItems, this.shipping, this.tax, });

factory PostPaymentIntentsRequestAmountDetails.fromJson(Map<String, dynamic> json) { return PostPaymentIntentsRequestAmountDetails(
  discountAmount: json['discount_amount'] != null ? PostPaymentIntentsRequestAmountDetailsDiscountAmount.fromJson(json['discount_amount'] as Map<String, dynamic>) : null,
  enforceArithmeticValidation: json['enforce_arithmetic_validation'] as bool?,
  lineItems: json['line_items'] != null ? PostPaymentIntentsRequestAmountDetailsLineItems.fromJson(json['line_items'] as Map<String, dynamic>) : null,
  shipping: json['shipping'] != null ? PostPaymentIntentsRequestAmountDetailsShipping.fromJson(json['shipping'] as Map<String, dynamic>) : null,
  tax: json['tax'] != null ? PostPaymentIntentsRequestAmountDetailsTax.fromJson(json['tax'] as Map<String, dynamic>) : null,
); }

final PostPaymentIntentsRequestAmountDetailsDiscountAmount? discountAmount;

final bool? enforceArithmeticValidation;

final PostPaymentIntentsRequestAmountDetailsLineItems? lineItems;

final PostPaymentIntentsRequestAmountDetailsShipping? shipping;

final PostPaymentIntentsRequestAmountDetailsTax? tax;

Map<String, dynamic> toJson() { return {
  if (discountAmount != null) 'discount_amount': discountAmount?.toJson(),
  'enforce_arithmetic_validation': ?enforceArithmeticValidation,
  if (lineItems != null) 'line_items': lineItems?.toJson(),
  if (shipping != null) 'shipping': shipping?.toJson(),
  if (tax != null) 'tax': tax?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostPaymentIntentsRequestAmountDetails copyWith({PostPaymentIntentsRequestAmountDetailsDiscountAmount Function()? discountAmount, bool Function()? enforceArithmeticValidation, PostPaymentIntentsRequestAmountDetailsLineItems Function()? lineItems, PostPaymentIntentsRequestAmountDetailsShipping Function()? shipping, PostPaymentIntentsRequestAmountDetailsTax Function()? tax, }) { return PostPaymentIntentsRequestAmountDetails(
  discountAmount: discountAmount != null ? discountAmount() : this.discountAmount,
  enforceArithmeticValidation: enforceArithmeticValidation != null ? enforceArithmeticValidation() : this.enforceArithmeticValidation,
  lineItems: lineItems != null ? lineItems() : this.lineItems,
  shipping: shipping != null ? shipping() : this.shipping,
  tax: tax != null ? tax() : this.tax,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostPaymentIntentsRequestAmountDetails &&
          discountAmount == other.discountAmount &&
          enforceArithmeticValidation == other.enforceArithmeticValidation &&
          lineItems == other.lineItems &&
          shipping == other.shipping &&
          tax == other.tax; } 
@override int get hashCode { return Object.hash(discountAmount, enforceArithmeticValidation, lineItems, shipping, tax); } 
@override String toString() { return 'PostPaymentIntentsRequestAmountDetails(discountAmount: $discountAmount, enforceArithmeticValidation: $enforceArithmeticValidation, lineItems: $lineItems, shipping: $shipping, tax: $tax)'; } 
 }
