//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// Where the user is coming from. This informs the optimizations that are applied to the session. You can't set this parameter if `ui_mode` is `custom`.
final class PostCheckoutSessionsRequestOriginContext {const PostCheckoutSessionsRequestOriginContext._(this.value);

factory PostCheckoutSessionsRequestOriginContext.fromJson(String json) { return switch (json) {
  'mobile_app' => mobileApp,
  'web' => web,
  _ => PostCheckoutSessionsRequestOriginContext._(json),
}; }

static const PostCheckoutSessionsRequestOriginContext mobileApp = PostCheckoutSessionsRequestOriginContext._('mobile_app');

static const PostCheckoutSessionsRequestOriginContext web = PostCheckoutSessionsRequestOriginContext._('web');

static const List<PostCheckoutSessionsRequestOriginContext> values = [mobileApp, web];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PostCheckoutSessionsRequestOriginContext && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PostCheckoutSessionsRequestOriginContext($value)'; } 
 }
