//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'package:collection/collection.dart';import 'post_test_helpers_issuing_authorizations_authorization_capture_request_purchase_details.dart';final class PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequest {const PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequest({this.captureAmount, this.closeAuthorization, this.expand, this.purchaseDetails, });

factory PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequest.fromJson(Map<String, dynamic> json) { return PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequest(
  captureAmount: json['capture_amount'] != null ? (json['capture_amount'] as num).toInt() : null,
  closeAuthorization: json['close_authorization'] as bool?,
  expand: (json['expand'] as List<dynamic>?)?.map((e) => e as String).toList(),
  purchaseDetails: json['purchase_details'] != null ? PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequestPurchaseDetails.fromJson(json['purchase_details'] as Map<String, dynamic>) : null,
); }

/// The amount to capture from the authorization. If not provided, the full amount of the authorization will be captured. This amount is in the authorization currency and in the [smallest currency unit](https://docs.stripe.com/currencies#zero-decimal).
final int? captureAmount;

/// Whether to close the authorization after capture. Defaults to true. Set to false to enable multi-capture flows.
final bool? closeAuthorization;

/// Specifies which fields in the response should be expanded.
final List<String>? expand;

/// Additional purchase information that is optionally provided by the merchant.
final PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequestPurchaseDetails? purchaseDetails;

Map<String, dynamic> toJson() { return {
  'capture_amount': ?captureAmount,
  'close_authorization': ?closeAuthorization,
  'expand': ?expand,
  if (purchaseDetails != null) 'purchase_details': purchaseDetails?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequest copyWith({int Function()? captureAmount, bool Function()? closeAuthorization, List<String> Function()? expand, PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequestPurchaseDetails Function()? purchaseDetails, }) { return PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequest(
  captureAmount: captureAmount != null ? captureAmount() : this.captureAmount,
  closeAuthorization: closeAuthorization != null ? closeAuthorization() : this.closeAuthorization,
  expand: expand != null ? expand() : this.expand,
  purchaseDetails: purchaseDetails != null ? purchaseDetails() : this.purchaseDetails,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequest &&
          captureAmount == other.captureAmount &&
          closeAuthorization == other.closeAuthorization &&
          const ListEquality<dynamic>().equals(expand, other.expand) &&
          purchaseDetails == other.purchaseDetails; } 
@override int get hashCode { return Object.hash(captureAmount, closeAuthorization, Object.hashAll(expand ?? const []), purchaseDetails); } 
@override String toString() { return 'PostTestHelpersIssuingAuthorizationsAuthorizationCaptureRequest(captureAmount: $captureAmount, closeAuthorization: $closeAuthorization, expand: $expand, purchaseDetails: $purchaseDetails)'; } 
 }
