//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'post_subscriptions_subscription_exposed_id_request_discounts_variant1.dart';final class PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant2 {const PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant2._(this.value);

factory PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant2.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant2._(json),
}; }

static const PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant2 $empty = PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant2._('');

static const List<PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant2> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant2 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant2($value)'; } 
 }
typedef PostSubscriptionsSubscriptionExposedIdRequestDiscounts = OneOf2<List<PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant1>,PostSubscriptionsSubscriptionExposedIdRequestDiscountsVariant2>;