//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class PostRefundsRequestMetadataVariant2 {const PostRefundsRequestMetadataVariant2._(this.value);

factory PostRefundsRequestMetadataVariant2.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => PostRefundsRequestMetadataVariant2._(json),
}; }

static const PostRefundsRequestMetadataVariant2 $empty = PostRefundsRequestMetadataVariant2._('');

static const List<PostRefundsRequestMetadataVariant2> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PostRefundsRequestMetadataVariant2 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PostRefundsRequestMetadataVariant2($value)'; } 
 }
/// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
final class PostRefundsRequestMetadata {const PostRefundsRequestMetadata({this.mapStringString, this.postRefundsRequestMetadataVariant2, });

factory PostRefundsRequestMetadata.fromJson(Object? json) { return PostRefundsRequestMetadata(
  // mapStringString: skipped (collection type in anyOf not supported)
  postRefundsRequestMetadataVariant2: json is String ? PostRefundsRequestMetadataVariant2.fromJson(json) : null,
); }

final Map<String,String>? mapStringString;

final PostRefundsRequestMetadataVariant2? postRefundsRequestMetadataVariant2;

/// At least one variant must be present.
bool get isValid { return mapStringString != null || postRefundsRequestMetadataVariant2 != null; } 
Map<String, dynamic> toJson() { return {
  'mapStringString': ?mapStringString,
  if (postRefundsRequestMetadataVariant2 != null) 'postRefundsRequestMetadataVariant2': postRefundsRequestMetadataVariant2!.toJson(),
}; } 
 }
