//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from openai.yml
//  OpenAPI spec version: 3.1.0

import 'package:collection/collection.dart';import 'create_container_body_expires_after.dart';import 'create_container_body_network_policy.dart';import 'create_container_body_skills.dart';/// Optional memory limit for the container. Defaults to "1g".
final class CreateContainerBodyMemoryLimit {const CreateContainerBodyMemoryLimit._(this.value);

factory CreateContainerBodyMemoryLimit.fromJson(String json) { return switch (json) {
  '1g' => $1g,
  '4g' => $4g,
  '16g' => $16g,
  '64g' => $64g,
  _ => CreateContainerBodyMemoryLimit._(json),
}; }

static const CreateContainerBodyMemoryLimit $1g = CreateContainerBodyMemoryLimit._('1g');

static const CreateContainerBodyMemoryLimit $4g = CreateContainerBodyMemoryLimit._('4g');

static const CreateContainerBodyMemoryLimit $16g = CreateContainerBodyMemoryLimit._('16g');

static const CreateContainerBodyMemoryLimit $64g = CreateContainerBodyMemoryLimit._('64g');

static const List<CreateContainerBodyMemoryLimit> values = [$1g, $4g, $16g, $64g];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is CreateContainerBodyMemoryLimit && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'CreateContainerBodyMemoryLimit($value)'; } 
 }
final class CreateContainerBody {const CreateContainerBody({required this.name, this.fileIds, this.expiresAfter, this.skills, this.memoryLimit, this.networkPolicy, });

factory CreateContainerBody.fromJson(Map<String, dynamic> json) { return CreateContainerBody(
  name: json['name'] as String,
  fileIds: (json['file_ids'] as List<dynamic>?)?.map((e) => e as String).toList(),
  expiresAfter: json['expires_after'] != null ? CreateContainerBodyExpiresAfter.fromJson(json['expires_after'] as Map<String, dynamic>) : null,
  skills: (json['skills'] as List<dynamic>?)?.map((e) => CreateContainerBodySkills.fromJson(e as Map<String, dynamic>)).toList(),
  memoryLimit: json['memory_limit'] != null ? CreateContainerBodyMemoryLimit.fromJson(json['memory_limit'] as String) : null,
  networkPolicy: json['network_policy'] != null ? CreateContainerBodyNetworkPolicy.fromJson(json['network_policy'] as Map<String, dynamic>) : null,
); }

/// Name of the container to create.
final String name;

/// IDs of files to copy to the container.
final List<String>? fileIds;

/// Container expiration time in seconds relative to the 'anchor' time.
final CreateContainerBodyExpiresAfter? expiresAfter;

/// An optional list of skills referenced by id or inline data.
final List<CreateContainerBodySkills>? skills;

/// Optional memory limit for the container. Defaults to "1g".
final CreateContainerBodyMemoryLimit? memoryLimit;

/// Network access policy for the container.
final CreateContainerBodyNetworkPolicy? networkPolicy;

Map<String, dynamic> toJson() { return {
  'name': name,
  'file_ids': ?fileIds,
  if (expiresAfter != null) 'expires_after': expiresAfter?.toJson(),
  if (skills != null) 'skills': skills?.map((e) => e.toJson()).toList(),
  if (memoryLimit != null) 'memory_limit': memoryLimit?.toJson(),
  if (networkPolicy != null) 'network_policy': networkPolicy?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('name') && json['name'] is String; } 
CreateContainerBody copyWith({String? name, List<String> Function()? fileIds, CreateContainerBodyExpiresAfter Function()? expiresAfter, List<CreateContainerBodySkills> Function()? skills, CreateContainerBodyMemoryLimit Function()? memoryLimit, CreateContainerBodyNetworkPolicy Function()? networkPolicy, }) { return CreateContainerBody(
  name: name ?? this.name,
  fileIds: fileIds != null ? fileIds() : this.fileIds,
  expiresAfter: expiresAfter != null ? expiresAfter() : this.expiresAfter,
  skills: skills != null ? skills() : this.skills,
  memoryLimit: memoryLimit != null ? memoryLimit() : this.memoryLimit,
  networkPolicy: networkPolicy != null ? networkPolicy() : this.networkPolicy,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is CreateContainerBody &&
          name == other.name &&
          const ListEquality<dynamic>().equals(fileIds, other.fileIds) &&
          expiresAfter == other.expiresAfter &&
          const ListEquality<dynamic>().equals(skills, other.skills) &&
          memoryLimit == other.memoryLimit &&
          networkPolicy == other.networkPolicy; } 
@override int get hashCode { return Object.hash(name, Object.hashAll(fileIds ?? const []), expiresAfter, Object.hashAll(skills ?? const []), memoryLimit, networkPolicy); } 
@override String toString() { return 'CreateContainerBody(name: $name, fileIds: $fileIds, expiresAfter: $expiresAfter, skills: $skills, memoryLimit: $memoryLimit, networkPolicy: $networkPolicy)'; } 
 }
