//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// Silence ID
extension type const AaaSilenceId(String value) {
factory AaaSilenceId.fromJson(String json) => AaaSilenceId(json);

String toJson() => value;

}
