//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// The custom URL a user is redirected to when they are denied access to the application.
extension type const AccessSchemasCustomDenyUrl(String value) {
factory AccessSchemasCustomDenyUrl.fromJson(String json) => AccessSchemasCustomDenyUrl(json);

String toJson() => value;

}
