//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// Timestamp of the moment the LOA was marked as validated.
extension type AddressingVerifiedAt(DateTime value) {
factory AddressingVerifiedAt.fromJson(String json) => AddressingVerifiedAt(DateTime.parse(json));

String toJson() => value.toIso8601String();

}
