//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'package:collection/collection.dart';final class AiSearchCreateTokensResponse400Errors {const AiSearchCreateTokensResponse400Errors({required this.code, required this.message, required this.path, });

factory AiSearchCreateTokensResponse400Errors.fromJson(Map<String, dynamic> json) { return AiSearchCreateTokensResponse400Errors(
  code: (json['code'] as num).toDouble(),
  message: json['message'] as String,
  path: (json['path'] as List<dynamic>).map((e) => e as String).toList(),
); }

final double code;

final String message;

final List<String> path;

Map<String, dynamic> toJson() { return {
  'code': code,
  'message': message,
  'path': path,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('code') && json['code'] is num &&
      json.containsKey('message') && json['message'] is String &&
      json.containsKey('path'); } 
AiSearchCreateTokensResponse400Errors copyWith({double? code, String? message, List<String>? path, }) { return AiSearchCreateTokensResponse400Errors(
  code: code ?? this.code,
  message: message ?? this.message,
  path: path ?? this.path,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is AiSearchCreateTokensResponse400Errors &&
          code == other.code &&
          message == other.message &&
          const ListEquality<dynamic>().equals(path, other.path); } 
@override int get hashCode { return Object.hash(code, message, Object.hashAll(path)); } 
@override String toString() { return 'AiSearchCreateTokensResponse400Errors(code: $code, message: $message, path: $path)'; } 
 }
