//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'ai_search_update_instances_request_retrieval_options_boost_by_direction.dart';final class AiSearchUpdateInstancesRequestRetrievalOptionsBoostBy {const AiSearchUpdateInstancesRequestRetrievalOptionsBoostBy({this.direction, required this.field, });

factory AiSearchUpdateInstancesRequestRetrievalOptionsBoostBy.fromJson(Map<String, dynamic> json) { return AiSearchUpdateInstancesRequestRetrievalOptionsBoostBy(
  direction: json['direction'] != null ? AiSearchUpdateInstancesRequestRetrievalOptionsBoostByDirection.fromJson(json['direction'] as String) : null,
  field: json['field'] as String,
); }

/// Boost direction. 'desc' = higher values rank higher (e.g. newer timestamps). 'asc' = lower values rank higher. 'exists' = boost chunks that have the field. 'not_exists' = boost chunks that lack the field. Optional ��� defaults to 'asc' for numeric fields, 'exists' for text/boolean fields.
final AiSearchUpdateInstancesRequestRetrievalOptionsBoostByDirection? direction;

/// Metadata field name to boost by. Use 'timestamp' for document freshness, or any custom_metadata field. Numeric fields support asc/desc directions; text/boolean fields support exists/not_exists.
final String field;

Map<String, dynamic> toJson() { return {
  if (direction != null) 'direction': direction?.toJson(),
  'field': field,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('field') && json['field'] is String; } 
AiSearchUpdateInstancesRequestRetrievalOptionsBoostBy copyWith({AiSearchUpdateInstancesRequestRetrievalOptionsBoostByDirection Function()? direction, String? field, }) { return AiSearchUpdateInstancesRequestRetrievalOptionsBoostBy(
  direction: direction != null ? direction() : this.direction,
  field: field ?? this.field,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is AiSearchUpdateInstancesRequestRetrievalOptionsBoostBy &&
          direction == other.direction &&
          field == other.field; } 
@override int get hashCode { return Object.hash(direction, field); } 
@override String toString() { return 'AiSearchUpdateInstancesRequestRetrievalOptionsBoostBy(direction: $direction, field: $field)'; } 
 }
