//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class AigConfigListGatewayDynamicRoutesResponseDataRoutesElementsVariant5OutputsFallback {const AigConfigListGatewayDynamicRoutesResponseDataRoutesElementsVariant5OutputsFallback({required this.elementId});

factory AigConfigListGatewayDynamicRoutesResponseDataRoutesElementsVariant5OutputsFallback.fromJson(Map<String, dynamic> json) { return AigConfigListGatewayDynamicRoutesResponseDataRoutesElementsVariant5OutputsFallback(
  elementId: json['elementId'] as String,
); }

final String elementId;

Map<String, dynamic> toJson() { return {
  'elementId': elementId,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('elementId') && json['elementId'] is String; } 
AigConfigListGatewayDynamicRoutesResponseDataRoutesElementsVariant5OutputsFallback copyWith({String? elementId}) { return AigConfigListGatewayDynamicRoutesResponseDataRoutesElementsVariant5OutputsFallback(
  elementId: elementId ?? this.elementId,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is AigConfigListGatewayDynamicRoutesResponseDataRoutesElementsVariant5OutputsFallback &&
          elementId == other.elementId; } 
@override int get hashCode { return elementId.hashCode; } 
@override String toString() { return 'AigConfigListGatewayDynamicRoutesResponseDataRoutesElementsVariant5OutputsFallback(elementId: $elementId)'; } 
 }
