//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// Returns the application creation time.
extension type const AlexandriaApplicationCreatedAt(String value) {
factory AlexandriaApplicationCreatedAt.fromJson(String json) => AlexandriaApplicationCreatedAt(json);

String toJson() => value;

}
