//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// Specifies the zone associated with the API call.
extension type const ArgoConfigIdentifier(String value) {
factory ArgoConfigIdentifier.fromJson(String json) => ArgoConfigIdentifier(json);

String toJson() => value;

}
