//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// Provide credentials for HTTP authentication.
final class BrapiPostMarkdownRequestVariant1Authenticate {const BrapiPostMarkdownRequestVariant1Authenticate({required this.password, required this.username, });

factory BrapiPostMarkdownRequestVariant1Authenticate.fromJson(Map<String, dynamic> json) { return BrapiPostMarkdownRequestVariant1Authenticate(
  password: json['password'] as String,
  username: json['username'] as String,
); }

final String password;

final String username;

Map<String, dynamic> toJson() { return {
  'password': password,
  'username': username,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('password') && json['password'] is String &&
      json.containsKey('username') && json['username'] is String; } 
BrapiPostMarkdownRequestVariant1Authenticate copyWith({String? password, String? username, }) { return BrapiPostMarkdownRequestVariant1Authenticate(
  password: password ?? this.password,
  username: username ?? this.username,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is BrapiPostMarkdownRequestVariant1Authenticate &&
          password == other.password &&
          username == other.username; } 
@override int get hashCode { return Object.hash(password, username); } 
@override String toString() { return 'BrapiPostMarkdownRequestVariant1Authenticate(password: $password, username: $username)'; } 
 }
