//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1 {const BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1._(this.value);

factory BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1.fromJson(String json) { return switch (json) {
  'load' => load,
  _ => BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1._(json),
}; }

static const BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1 load = BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1._('load');

static const List<BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1> values = [load];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1($value)'; } 
 }
final class BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2 {const BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2._(this.value);

factory BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2.fromJson(String json) { return switch (json) {
  'domcontentloaded' => domcontentloaded,
  _ => BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2._(json),
}; }

static const BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2 domcontentloaded = BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2._('domcontentloaded');

static const List<BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2> values = [domcontentloaded];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2($value)'; } 
 }
final class BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3 {const BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3._(this.value);

factory BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3.fromJson(String json) { return switch (json) {
  'networkidle0' => networkidle0,
  _ => BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3._(json),
}; }

static const BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3 networkidle0 = BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3._('networkidle0');

static const List<BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3> values = [networkidle0];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3($value)'; } 
 }
final class BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4 {const BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4._(this.value);

factory BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4.fromJson(String json) { return switch (json) {
  'networkidle2' => networkidle2,
  _ => BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4._(json),
}; }

static const BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4 networkidle2 = BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4._('networkidle2');

static const List<BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4> values = [networkidle2];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4($value)'; } 
 }
final class BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5 {const BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5({this.brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1, this.brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2, this.brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3, this.brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4, });

factory BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5.fromJson(Object? json) { return BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5(
  brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1: json is String ? BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1.fromJson(json) : null,
  brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2: json is String ? BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2.fromJson(json) : null,
  brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3: json is String ? BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3.fromJson(json) : null,
  brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4: json is String ? BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4.fromJson(json) : null,
); }

final BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1? brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1;

final BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2? brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2;

final BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3? brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3;

final BrapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4? brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4;

/// At least one variant must be present.
bool get isValid { return brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1 != null || brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2 != null || brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3 != null || brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4 != null; } 
Map<String, dynamic> toJson() { return {
  if (brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1 != null) 'brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1': brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant1!.toJson(),
  if (brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2 != null) 'brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2': brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant2!.toJson(),
  if (brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3 != null) 'brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3': brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant3!.toJson(),
  if (brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4 != null) 'brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4': brapiPostScrapeRequestVariant2GotoOptionsWaitUntilVariant5Variant4!.toJson(),
}; } 
 }
