//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// An Application ID represents an identifier of an application
extension type const CcApplicationId(String value) {
factory CcApplicationId.fromJson(String json) => CcApplicationId(json);

String toJson() => value;

}
