//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

extension type CloudforceOneRequestsTime(DateTime value) {
factory CloudforceOneRequestsTime.fromJson(String json) => CloudforceOneRequestsTime(DateTime.parse(json));

String toJson() => value.toIso8601String();

}
