//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object152_script_version.dart';import 'inline_object153.dart';final class InlineObject152EventType {const InlineObject152EventType._(this.value);

factory InlineObject152EventType.fromJson(String json) { return switch (json) {
  'fetch' => fetch,
  'scheduled' => scheduled,
  'alarm' => alarm,
  'cron' => cron,
  'queue' => queue,
  'email' => email,
  'tail' => tail,
  'rpc' => rpc,
  'websocket' => websocket,
  'unknown' => unknown,
  _ => InlineObject152EventType._(json),
}; }

static const InlineObject152EventType fetch = InlineObject152EventType._('fetch');

static const InlineObject152EventType scheduled = InlineObject152EventType._('scheduled');

static const InlineObject152EventType alarm = InlineObject152EventType._('alarm');

static const InlineObject152EventType cron = InlineObject152EventType._('cron');

static const InlineObject152EventType queue = InlineObject152EventType._('queue');

static const InlineObject152EventType email = InlineObject152EventType._('email');

static const InlineObject152EventType tail = InlineObject152EventType._('tail');

static const InlineObject152EventType rpc = InlineObject152EventType._('rpc');

static const InlineObject152EventType websocket = InlineObject152EventType._('websocket');

static const InlineObject152EventType unknown = InlineObject152EventType._('unknown');

static const List<InlineObject152EventType> values = [fetch, scheduled, alarm, cron, queue, email, tail, rpc, websocket, unknown];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject152EventType && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject152EventType($value)'; } 
 }
final class InlineObject152ExecutionModel {const InlineObject152ExecutionModel._(this.value);

factory InlineObject152ExecutionModel.fromJson(String json) { return switch (json) {
  'durableObject' => durableObject,
  'stateless' => stateless,
  _ => InlineObject152ExecutionModel._(json),
}; }

static const InlineObject152ExecutionModel durableObject = InlineObject152ExecutionModel._('durableObject');

static const InlineObject152ExecutionModel stateless = InlineObject152ExecutionModel._('stateless');

static const List<InlineObject152ExecutionModel> values = [durableObject, stateless];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject152ExecutionModel && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject152ExecutionModel($value)'; } 
 }
final class InlineObject152 {const InlineObject152({this.durableObjectId, this.entrypoint, this.event, required this.eventType, this.executionModel, this.outcome, required this.requestId, required this.scriptName, this.scriptVersion, this.truncated, });

factory InlineObject152.fromJson(Map<String, dynamic> json) { return InlineObject152(
  durableObjectId: json['durableObjectId'] as String?,
  entrypoint: json['entrypoint'] as String?,
  event: (json['event'] as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, InlineObject153.fromJson(v as Map<String, dynamic>))),
  eventType: InlineObject152EventType.fromJson(json['eventType'] as String),
  executionModel: json['executionModel'] != null ? InlineObject152ExecutionModel.fromJson(json['executionModel'] as String) : null,
  outcome: json['outcome'] as String?,
  requestId: json['requestId'] as String,
  scriptName: json['scriptName'] as String,
  scriptVersion: json['scriptVersion'] != null
        ? InlineObject152ScriptVersion.fromJson(json['scriptVersion'] as Map<String, dynamic>)
        : null,
  truncated: json['truncated'] as bool?,
); }

final String? durableObjectId;

final String? entrypoint;

final Map<String,InlineObject153>? event;

final InlineObject152EventType eventType;

final InlineObject152ExecutionModel? executionModel;

final String? outcome;

final String requestId;

final String scriptName;

final InlineObject152ScriptVersion? scriptVersion;

final bool? truncated;

Map<String, dynamic> toJson() { return {
  'durableObjectId': ?durableObjectId,
  'entrypoint': ?entrypoint,
  if (event != null) 'event': event?.map((k, v) => MapEntry(k, v.toJson())),
  'eventType': eventType.toJson(),
  if (executionModel != null) 'executionModel': executionModel?.toJson(),
  'outcome': ?outcome,
  'requestId': requestId,
  'scriptName': scriptName,
  if (scriptVersion != null) 'scriptVersion': scriptVersion?.toJson(),
  'truncated': ?truncated,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('eventType') &&
      json.containsKey('requestId') && json['requestId'] is String &&
      json.containsKey('scriptName') && json['scriptName'] is String; } 
InlineObject152 copyWith({String Function()? durableObjectId, String Function()? entrypoint, Map<String, InlineObject153> Function()? event, InlineObject152EventType? eventType, InlineObject152ExecutionModel Function()? executionModel, String Function()? outcome, String? requestId, String? scriptName, InlineObject152ScriptVersion Function()? scriptVersion, bool Function()? truncated, }) { return InlineObject152(
  durableObjectId: durableObjectId != null ? durableObjectId() : this.durableObjectId,
  entrypoint: entrypoint != null ? entrypoint() : this.entrypoint,
  event: event != null ? event() : this.event,
  eventType: eventType ?? this.eventType,
  executionModel: executionModel != null ? executionModel() : this.executionModel,
  outcome: outcome != null ? outcome() : this.outcome,
  requestId: requestId ?? this.requestId,
  scriptName: scriptName ?? this.scriptName,
  scriptVersion: scriptVersion != null ? scriptVersion() : this.scriptVersion,
  truncated: truncated != null ? truncated() : this.truncated,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is InlineObject152 &&
          durableObjectId == other.durableObjectId &&
          entrypoint == other.entrypoint &&
          event == other.event &&
          eventType == other.eventType &&
          executionModel == other.executionModel &&
          outcome == other.outcome &&
          requestId == other.requestId &&
          scriptName == other.scriptName &&
          scriptVersion == other.scriptVersion &&
          truncated == other.truncated; } 
@override int get hashCode { return Object.hash(durableObjectId, entrypoint, event, eventType, executionModel, outcome, requestId, scriptName, scriptVersion, truncated); } 
@override String toString() { return 'InlineObject152(durableObjectId: $durableObjectId, entrypoint: $entrypoint, event: $event, eventType: $eventType, executionModel: $executionModel, outcome: $outcome, requestId: $requestId, scriptName: $scriptName, scriptVersion: $scriptVersion, truncated: $truncated)'; } 
 }
