//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class InlineObject769ResponseFormatType {const InlineObject769ResponseFormatType._(this.value);

factory InlineObject769ResponseFormatType.fromJson(String json) { return switch (json) {
  'json_object' => jsonObject,
  'json_schema' => jsonSchema,
  _ => InlineObject769ResponseFormatType._(json),
}; }

static const InlineObject769ResponseFormatType jsonObject = InlineObject769ResponseFormatType._('json_object');

static const InlineObject769ResponseFormatType jsonSchema = InlineObject769ResponseFormatType._('json_schema');

static const List<InlineObject769ResponseFormatType> values = [jsonObject, jsonSchema];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject769ResponseFormatType && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject769ResponseFormatType($value)'; } 
 }
final class InlineObject769ResponseFormat {const InlineObject769ResponseFormat({this.jsonSchema, this.type, });

factory InlineObject769ResponseFormat.fromJson(Map<String, dynamic> json) { return InlineObject769ResponseFormat(
  jsonSchema: json['json_schema'] as String?,
  type: json['type'] != null ? InlineObject769ResponseFormatType.fromJson(json['type'] as String) : null,
); }

final String? jsonSchema;

final InlineObject769ResponseFormatType? type;

Map<String, dynamic> toJson() { return {
  'json_schema': ?jsonSchema,
  if (type != null) 'type': type?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
InlineObject769ResponseFormat copyWith({String Function()? jsonSchema, InlineObject769ResponseFormatType Function()? type, }) { return InlineObject769ResponseFormat(
  jsonSchema: jsonSchema != null ? jsonSchema() : this.jsonSchema,
  type: type != null ? type() : this.type,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is InlineObject769ResponseFormat &&
          jsonSchema == other.jsonSchema &&
          type == other.type; } 
@override int get hashCode { return Object.hash(jsonSchema, type); } 
@override String toString() { return 'InlineObject769ResponseFormat(jsonSchema: $jsonSchema, type: $type)'; } 
 }
