//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object243.dart';final class InlineObject242Type {const InlineObject242Type._(this.value);

factory InlineObject242Type.fromJson(String json) { return switch (json) {
  'end' => end,
  _ => InlineObject242Type._(json),
}; }

static const InlineObject242Type end = InlineObject242Type._('end');

static const List<InlineObject242Type> values = [end];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject242Type && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject242Type($value)'; } 
 }
final class InlineObject242 {const InlineObject242({required this.id, required this.outputs, required this.type, });

factory InlineObject242.fromJson(Map<String, dynamic> json) { return InlineObject242(
  id: json['id'] as String,
  outputs: (json['outputs'] as Map<String, dynamic>).map((k, v) => MapEntry(k, InlineObject243.fromJson(v as Map<String, dynamic>))),
  type: InlineObject242Type.fromJson(json['type'] as String),
); }

final String id;

final Map<String,InlineObject243> outputs;

final InlineObject242Type type;

Map<String, dynamic> toJson() { return {
  'id': id,
  'outputs': outputs.map((k, v) => MapEntry(k, v.toJson())),
  'type': type.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('id') && json['id'] is String &&
      json.containsKey('outputs') &&
      json.containsKey('type'); } 
InlineObject242 copyWith({String? id, Map<String,InlineObject243>? outputs, InlineObject242Type? type, }) { return InlineObject242(
  id: id ?? this.id,
  outputs: outputs ?? this.outputs,
  type: type ?? this.type,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is InlineObject242 &&
          id == other.id &&
          outputs == other.outputs &&
          type == other.type; } 
@override int get hashCode { return Object.hash(id, outputs, type); } 
@override String toString() { return 'InlineObject242(id: $id, outputs: $outputs, type: $type)'; } 
 }
