//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object535_image_url.dart';final class InlineObject535 {const InlineObject535({this.imageUrl, this.text, this.type, });

factory InlineObject535.fromJson(Map<String, dynamic> json) { return InlineObject535(
  imageUrl: json['image_url'] != null
        ? InlineObject535ImageUrl.fromJson(json['image_url'] as Map<String, dynamic>)
        : null,
  text: json['text'] as String?,
  type: json['type'] as String?,
); }

final InlineObject535ImageUrl? imageUrl;

final String? text;

/// Type of the content provided
final String? type;

Map<String, dynamic> toJson() { return {
  if (imageUrl != null) 'image_url': imageUrl?.toJson(),
  'text': ?text,
  'type': ?type,
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
InlineObject535 copyWith({InlineObject535ImageUrl Function()? imageUrl, String Function()? text, String Function()? type, }) { return InlineObject535(
  imageUrl: imageUrl != null ? imageUrl() : this.imageUrl,
  text: text != null ? text() : this.text,
  type: type != null ? type() : this.type,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is InlineObject535 &&
          imageUrl == other.imageUrl &&
          text == other.text &&
          type == other.type; } 
@override int get hashCode { return Object.hash(imageUrl, text, type); } 
@override String toString() { return 'InlineObject535(imageUrl: $imageUrl, text: $text, type: $type)'; } 
 }
