//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object397_pooling.dart';import 'inline_object397_text.dart';final class InlineObject397 {const InlineObject397({this.pooling = InlineObject397Pooling.mean, required this.text, });

factory InlineObject397.fromJson(Map<String, dynamic> json) { return InlineObject397(
  pooling: json.containsKey('pooling') ? InlineObject397Pooling.fromJson(json['pooling'] as String) : InlineObject397Pooling.mean,
  text: InlineObject397Text.fromJson(json['text']),
); }

/// The pooling method used in the embedding process. `cls` pooling will generate more accurate embeddings on larger inputs - however, embeddings created with cls pooling are not compatible with embeddings generated with mean pooling. The default pooling method is `mean` in order for this to not be a breaking change, but we highly suggest using the new `cls` pooling for better accuracy.
final InlineObject397Pooling pooling;

final InlineObject397Text text;

Map<String, dynamic> toJson() { return {
  'pooling': pooling.toJson(),
  'text': text.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('text'); } 
InlineObject397 copyWith({InlineObject397Pooling Function()? pooling, InlineObject397Text? text, }) { return InlineObject397(
  pooling: pooling != null ? pooling() : this.pooling,
  text: text ?? this.text,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is InlineObject397 &&
          pooling == other.pooling &&
          text == other.text; } 
@override int get hashCode { return Object.hash(pooling, text); } 
@override String toString() { return 'InlineObject397(pooling: $pooling, text: $text)'; } 
 }
