//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class InlineObject1580 {const InlineObject1580._(this.value);

factory InlineObject1580.fromJson(String json) { return switch (json) {
  'domcontentloaded' => domcontentloaded,
  _ => InlineObject1580._(json),
}; }

static const InlineObject1580 domcontentloaded = InlineObject1580._('domcontentloaded');

static const List<InlineObject1580> values = [domcontentloaded];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject1580 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject1580($value)'; } 
 }
