//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object76.dart';import 'inline_object77.dart';/// A value that is one of: `InlineObject76`, `InlineObject77`.
sealed class MagicAppConfigAddSingleRequest {const MagicAppConfigAddSingleRequest();

factory MagicAppConfigAddSingleRequest.fromJson(Map<String, dynamic> json) {   if (InlineObject76.canParse(json)) {
    return MagicAppConfigAddSingleRequestInlineObject76(InlineObject76.fromJson(json));
  }
  if (InlineObject77.canParse(json)) {
    return MagicAppConfigAddSingleRequestInlineObject77(InlineObject77.fromJson(json));
  }
  return MagicAppConfigAddSingleRequest$Unknown(json); }

/// The underlying raw value.
Object? get value;
Object? toJson() { return value; } 
 }
final class MagicAppConfigAddSingleRequestInlineObject76 extends MagicAppConfigAddSingleRequest {const MagicAppConfigAddSingleRequestInlineObject76(this._value);

final InlineObject76 _value;

@override InlineObject76 get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is MagicAppConfigAddSingleRequestInlineObject76 && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'MagicAppConfigAddSingleRequest.inlineObject76($_value)'; } 
 }
final class MagicAppConfigAddSingleRequestInlineObject77 extends MagicAppConfigAddSingleRequest {const MagicAppConfigAddSingleRequestInlineObject77(this._value);

final InlineObject77 _value;

@override InlineObject77 get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is MagicAppConfigAddSingleRequestInlineObject77 && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'MagicAppConfigAddSingleRequest.inlineObject77($_value)'; } 
 }
/// An unknown variant not defined in the OpenAPI spec.
final class MagicAppConfigAddSingleRequest$Unknown extends MagicAppConfigAddSingleRequest {const MagicAppConfigAddSingleRequest$Unknown(this._value);

final Object? _value;

@override Object get value { return _value ?? ''; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is MagicAppConfigAddSingleRequest$Unknown && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'MagicAppConfigAddSingleRequest.unknown($_value)'; } 
 }
