//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'messages33_messages_content_variant2.dart';/// A value that is one of: `String`, `List<Messages33MessagesContentVariant2>`.
sealed class Messages33MessagesContent {const Messages33MessagesContent();

factory Messages33MessagesContent.fromJson(Map<String, dynamic> json) {   return Messages33MessagesContent$Unknown(json); }

/// The underlying raw value.
Object? get value;
Object? toJson() { return value; } 
 }
final class Messages33MessagesContentString extends Messages33MessagesContent {const Messages33MessagesContentString(this._value);

final String _value;

@override String get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is Messages33MessagesContentString && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'Messages33MessagesContent.string($_value)'; } 
 }
final class Messages33MessagesContentListMessages33MessagesContentVariant2 extends Messages33MessagesContent {const Messages33MessagesContentListMessages33MessagesContentVariant2(this._value);

final List<Messages33MessagesContentVariant2> _value;

@override List<Messages33MessagesContentVariant2> get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is Messages33MessagesContentListMessages33MessagesContentVariant2 && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'Messages33MessagesContent.list<Messages33MessagesContentVariant2>($_value)'; } 
 }
/// An unknown variant not defined in the OpenAPI spec.
final class Messages33MessagesContent$Unknown extends Messages33MessagesContent {const Messages33MessagesContent$Unknown(this._value);

final Object? _value;

@override Object get value { return _value ?? ''; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is Messages33MessagesContent$Unknown && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'Messages33MessagesContent.unknown($_value)'; } 
 }
