//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'messages51_tools_variant2_custom.dart';final class Messages51ToolsVariant2Type {const Messages51ToolsVariant2Type._(this.value);

factory Messages51ToolsVariant2Type.fromJson(String json) { return switch (json) {
  'custom' => custom,
  _ => Messages51ToolsVariant2Type._(json),
}; }

static const Messages51ToolsVariant2Type custom = Messages51ToolsVariant2Type._('custom');

static const List<Messages51ToolsVariant2Type> values = [custom];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is Messages51ToolsVariant2Type && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'Messages51ToolsVariant2Type($value)'; } 
 }
final class Messages51ToolsVariant2 {const Messages51ToolsVariant2({required this.custom, required this.type, });

factory Messages51ToolsVariant2.fromJson(Map<String, dynamic> json) { return Messages51ToolsVariant2(
  custom: Messages51ToolsVariant2Custom.fromJson(json['custom'] as Map<String, dynamic>),
  type: Messages51ToolsVariant2Type.fromJson(json['type'] as String),
); }

final Messages51ToolsVariant2Custom custom;

final Messages51ToolsVariant2Type type;

Map<String, dynamic> toJson() { return {
  'custom': custom.toJson(),
  'type': type.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('custom') &&
      json.containsKey('type'); } 
Messages51ToolsVariant2 copyWith({Messages51ToolsVariant2Custom? custom, Messages51ToolsVariant2Type? type, }) { return Messages51ToolsVariant2(
  custom: custom ?? this.custom,
  type: type ?? this.type,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is Messages51ToolsVariant2 &&
          custom == other.custom &&
          type == other.type; } 
@override int get hashCode { return Object.hash(custom, type); } 
@override String toString() { return 'Messages51ToolsVariant2(custom: $custom, type: $type)'; } 
 }
