//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'radar_get_ai_inference_summary_by_task_response_result.dart';final class RadarGetAiInferenceSummaryByTaskResponse {const RadarGetAiInferenceSummaryByTaskResponse({required this.result, required this.success, });

factory RadarGetAiInferenceSummaryByTaskResponse.fromJson(Map<String, dynamic> json) { return RadarGetAiInferenceSummaryByTaskResponse(
  result: RadarGetAiInferenceSummaryByTaskResponseResult.fromJson(json['result'] as Map<String, dynamic>),
  success: json['success'] as bool,
); }

final RadarGetAiInferenceSummaryByTaskResponseResult result;

final bool success;

Map<String, dynamic> toJson() { return {
  'result': result.toJson(),
  'success': success,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('result') &&
      json.containsKey('success') && json['success'] is bool; } 
RadarGetAiInferenceSummaryByTaskResponse copyWith({RadarGetAiInferenceSummaryByTaskResponseResult? result, bool? success, }) { return RadarGetAiInferenceSummaryByTaskResponse(
  result: result ?? this.result,
  success: success ?? this.success,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is RadarGetAiInferenceSummaryByTaskResponse &&
          result == other.result &&
          success == other.success; } 
@override int get hashCode { return Object.hash(result, success); } 
@override String toString() { return 'RadarGetAiInferenceSummaryByTaskResponse(result: $result, success: $success)'; } 
 }
