//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// Cloudflare Tunnel Virtual Network ID
extension type const TlsCertificatesAndHostnamesKeylessVnetId(String value) {
factory TlsCertificatesAndHostnamesKeylessVnetId.fromJson(String json) => TlsCertificatesAndHostnamesKeylessVnetId(json);

String toJson() => value;

}
