//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// Timestamp of when the resource was deleted. If `null`, the resource has not been deleted.
extension type TunnelDeletedAt(DateTime value) {
factory TunnelDeletedAt.fromJson(String json) => TunnelDeletedAt(DateTime.parse(json));

String toJson() => value.toIso8601String();

}
