//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'package:collection/collection.dart';final class VectorizeIndexQueryResponseMatches {const VectorizeIndexQueryResponseMatches({this.id, this.metadata, this.score, this.values, });

factory VectorizeIndexQueryResponseMatches.fromJson(Map<String, dynamic> json) { return VectorizeIndexQueryResponseMatches(
  id: json['id'] as String?,
  metadata: (json['metadata'] as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, v as String)),
  score: json['score'] != null ? (json['score'] as num).toDouble() : null,
  values: (json['values'] as List<dynamic>?)?.map((e) => (e as num).toDouble()).toList(),
); }

final String? id;

final Map<String,String>? metadata;

/// The score of the vector according to the index's distance metric
final double? score;

final List<double>? values;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  'metadata': ?metadata,
  'score': ?score,
  'values': ?values,
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
VectorizeIndexQueryResponseMatches copyWith({String Function()? id, Map<String, String>? Function()? metadata, double Function()? score, List<double>? Function()? values, }) { return VectorizeIndexQueryResponseMatches(
  id: id != null ? id() : this.id,
  metadata: metadata != null ? metadata() : this.metadata,
  score: score != null ? score() : this.score,
  values: values != null ? values() : this.values,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is VectorizeIndexQueryResponseMatches &&
          id == other.id &&
          metadata == other.metadata &&
          score == other.score &&
          const ListEquality<dynamic>().equals(values, other.values); } 
@override int get hashCode { return Object.hash(id, metadata, score, Object.hashAll(values ?? const [])); } 
@override String toString() { return 'VectorizeIndexQueryResponseMatches(id: $id, metadata: $metadata, score: $score, values: $values)'; } 
 }
