//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'workers_observability_telemetry_eventworkers_variant1_event_value_variant4_value_variant4_value_variant1.dart';final class WorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4Value {const WorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4Value({this.listWorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4ValueVariant1, this.string, this.$double, this.$bool, });

factory WorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4Value.fromJson(Object? json) { return WorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4Value(
  // listWorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4ValueVariant1: skipped (collection type in anyOf not supported)
  string: json is String ? json : null,
  $double: json is num ? json.toDouble() : null,
  $bool: json is bool ? json : null,
); }

final List<WorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4ValueVariant1>? listWorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4ValueVariant1;

final String? string;

final double? $double;

final bool? $bool;

/// At least one variant must be present.
bool get isValid { return listWorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4ValueVariant1 != null || string != null || $double != null || $bool != null; } 
Map<String, dynamic> toJson() { return {
  'listWorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4ValueVariant1': ?listWorkersObservabilityTelemetryEvent$workersVariant1EventValueVariant4ValueVariant4ValueVariant1,
  'string': ?string,
  '$double': ?$double,
  '$bool': ?$bool,
}; } 
 }
