//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from openai.yml
//  OpenAPI spec version: 3.1.0

import 'dart:async';import 'dart:convert';import 'package:degenerate_runtime/degenerate_runtime.dart';import '../models/conversation_item.dart';import '../models/conversation_item_list.dart';import '../models/conversation_resource.dart';import '../models/create_conversation_body.dart';import '../models/create_conversation_items_request.dart';import '../models/deleted_conversation_resource.dart';import '../models/include_enum.dart';import '../models/list_conversation_items_order.dart';import '../models/update_conversation_body.dart';/// ConversationsApi operations.
///
/// All operations return [ApiResult] - use pattern matching to handle
/// success, error, and exception cases.
final class ConversationsApi {const ConversationsApi(this._config);

final ApiConfig _config;

/// List all items for a conversation with the given ID.
///
/// `GET /conversations/{conversation_id}/items`
Future<ApiResult<ConversationItemList, Never>> listConversationItems({required String conversationId, int? limit, ListConversationItemsOrder? order, String? after, List<IncludeEnum>? include, RequestOptions? options, }) async  { final queryParameters = <String, String>{..._config.defaultQueryParameters};
final queryParametersList = <ApiQueryParameter>[];
if (limit != null) queryParameters['limit'] = limit.toString();
if (order != null) queryParameters['order'] = order.toJson();
if (after != null) queryParameters['after'] = after;
if (include != null) {
for (final item in include) {
  queryParametersList.add(ApiQueryParameter(name: 'include', value: item.toJson(), allowReserved: false));
}
}

final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/conversations/${Uri.encodeComponent(conversationId)}/items',
  headers: headers,
  queryParameters: queryParameters,
  queryParametersList: queryParametersList,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ConversationItemList.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Create items in a conversation with the given ID.
///
/// `POST /conversations/{conversation_id}/items`
Future<ApiResult<ConversationItemList, Never>> createConversationItems({required String conversationId, List<IncludeEnum>? include, required CreateConversationItemsRequest body, RequestOptions? options, }) async  { final queryParameters = <String, String>{..._config.defaultQueryParameters};
final queryParametersList = <ApiQueryParameter>[];
if (include != null) {
for (final item in include) {
  queryParametersList.add(ApiQueryParameter(name: 'include', value: item.toJson(), allowReserved: false));
}
}

final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'POST',
  path: '/conversations/${Uri.encodeComponent(conversationId)}/items',
  headers: headers,
  queryParameters: queryParameters,
  queryParametersList: queryParametersList,
  body: jsonEncode(body.toJson()),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ConversationItemList.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Get a single item from a conversation with the given IDs.
///
/// `GET /conversations/{conversation_id}/items/{item_id}`
Future<ApiResult<ConversationItem, Never>> getConversationItem({required String conversationId, required String itemId, List<IncludeEnum>? include, RequestOptions? options, }) async  { final queryParameters = <String, String>{..._config.defaultQueryParameters};
final queryParametersList = <ApiQueryParameter>[];
if (include != null) {
for (final item in include) {
  queryParametersList.add(ApiQueryParameter(name: 'include', value: item.toJson(), allowReserved: false));
}
}

final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/conversations/${Uri.encodeComponent(conversationId)}/items/${Uri.encodeComponent(itemId)}',
  headers: headers,
  queryParameters: queryParameters,
  queryParametersList: queryParametersList,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ConversationItem.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Delete an item from a conversation with the given IDs.
///
/// `DELETE /conversations/{conversation_id}/items/{item_id}`
Future<ApiResult<ConversationResource, Never>> deleteConversationItem({required String conversationId, required String itemId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'DELETE',
  path: '/conversations/${Uri.encodeComponent(conversationId)}/items/${Uri.encodeComponent(itemId)}',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ConversationResource.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Create a conversation.
///
/// `POST /conversations`
Future<ApiResult<ConversationResource, Never>> createConversation({CreateConversationBody? body, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'POST',
  path: '/conversations',
  headers: headers,
  body: jsonEncode(body?.toJson()),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ConversationResource.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Get a conversation
///
/// `GET /conversations/{conversation_id}`
Future<ApiResult<ConversationResource, Never>> getConversation({required String conversationId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/conversations/${Uri.encodeComponent(conversationId)}',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ConversationResource.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Update a conversation
///
/// `POST /conversations/{conversation_id}`
Future<ApiResult<ConversationResource, Never>> updateConversation({required String conversationId, UpdateConversationBody? body, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/json';

final request = ApiRequest(
  method: 'POST',
  path: '/conversations/${Uri.encodeComponent(conversationId)}',
  headers: headers,
  body: jsonEncode(body?.toJson()),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ConversationResource.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Delete a conversation. Items in the conversation will not be deleted.
///
/// `DELETE /conversations/{conversation_id}`
Future<ApiResult<DeletedConversationResource, Never>> deleteConversation({required String conversationId, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'DELETE',
  path: '/conversations/${Uri.encodeComponent(conversationId)}',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return DeletedConversationResource.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Shared execution pipeline: interceptors -> send -> deserialize.
Future<ApiResult<T, E>> _execute<T,E>(ApiRequest request, {required T Function(ApiResponse) onSuccess, E? Function(ApiResponse)? onError, }) async  { try {
  final userCancelToken = request.options?.cancelToken;
  if (userCancelToken?.isCancelled ?? false) throw const CancelledException();

  final effectiveTimeout = request.options?.timeout ?? _config.timeout;
  final extraHeaders = request.options?.extraHeaders;

  // Merge timeout and user cancel into a single adapter-level cancel token.
  final adapterToken = (effectiveTimeout != null || userCancelToken != null)
      ? CancelToken()
      : null;
  Timer? timeoutTimer;
  bool timedOut = false;

  if (adapterToken != null) {
    if (userCancelToken != null) {
      final token = adapterToken;
      userCancelToken.whenCancelled.then((_) {
        if (!token.isCancelled) token.cancel();
      });
    }
    if (effectiveTimeout != null) {
      final token = adapterToken;
      timeoutTimer = Timer(effectiveTimeout, () {
        timedOut = true;
        if (!token.isCancelled) token.cancel();
      });
    }
  }

  final effectiveRequest = request.copyWith(
    headers: extraHeaders != null
        ? {...request.headers, ...extraHeaders}
        : null,
    options: RequestOptions(cancelToken: adapterToken),
  );

  try {
    final chain = buildInterceptorChain(
      interceptors: _config.interceptors,
      terminal: (req) => _config.client.send(req),
    );

    final response = await chain(effectiveRequest);
    timeoutTimer?.cancel();

    try {
      if (response.isSuccessful) {
        return ApiSuccess(
          onSuccess(response),
          statusCode: response.statusCode,
          headers: response.headers,
        );
      }
      return ApiError(
        statusCode: response.statusCode,
        error: onError != null ? onError(response) : null,
        rawError: response.body,
        headers: response.headers,
      );
    } catch (e, st) {
      return ApiParseException(e, st, response: response);
    }
  } on CancelledException {
    timeoutTimer?.cancel();
    if (timedOut) {
      throw TimeoutException('Request timed out', effectiveTimeout);
    }
    rethrow;
  }
} catch (e, st) {
  return ApiException(e, st);
}
 } 
 }
