//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

/// The enablement status of secret scanning
final class CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning {const CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning._(this.value);

factory CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning.fromJson(String json) { return switch (json) {
  'enabled' => enabled,
  'disabled' => disabled,
  'not_set' => notSet,
  _ => CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning._(json),
}; }

static const CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning enabled = CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning._('enabled');

static const CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning disabled = CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning._('disabled');

static const CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning notSet = CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning._('not_set');

static const List<CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning> values = [enabled, disabled, notSet];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'CodeSecurityUpdateEnterpriseConfigurationRequestSecretScanning($value)'; } 
 }
