//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

final class DependabotListAlertsForRepoSort {
  const DependabotListAlertsForRepoSort._(this.value);

  factory DependabotListAlertsForRepoSort.fromJson(String json) {
    return switch (json) {
      'created' => created,
      'updated' => updated,
      'epss_percentage' => epssPercentage,
      _ => DependabotListAlertsForRepoSort._(json),
    };
  }

  static const DependabotListAlertsForRepoSort created =
      DependabotListAlertsForRepoSort._('created');

  static const DependabotListAlertsForRepoSort updated =
      DependabotListAlertsForRepoSort._('updated');

  static const DependabotListAlertsForRepoSort epssPercentage =
      DependabotListAlertsForRepoSort._('epss_percentage');

  static const List<DependabotListAlertsForRepoSort> values = [
    created,
    updated,
    epssPercentage,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is DependabotListAlertsForRepoSort && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'DependabotListAlertsForRepoSort($value)';
  }
}
