//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

final class InlineObject78ParentPrivacy {const InlineObject78ParentPrivacy._(this.value);

factory InlineObject78ParentPrivacy.fromJson(String json) { return switch (json) {
  'open' => open,
  'closed' => closed,
  'secret' => secret,
  _ => InlineObject78ParentPrivacy._(json),
}; }

static const InlineObject78ParentPrivacy open = InlineObject78ParentPrivacy._('open');

static const InlineObject78ParentPrivacy closed = InlineObject78ParentPrivacy._('closed');

static const InlineObject78ParentPrivacy secret = InlineObject78ParentPrivacy._('secret');

static const List<InlineObject78ParentPrivacy> values = [open, closed, secret];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject78ParentPrivacy && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject78ParentPrivacy($value)'; } 
 }
