//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

final class InlineObject113 {
  const InlineObject113({this.status});

  factory InlineObject113.fromJson(Map<String, dynamic> json) {
    return InlineObject113(status: json['status'] as String?);
  }

  final String? status;

  Map<String, dynamic> toJson() {
    return {'status': ?status};
  }

  static bool canParse(Map<String, dynamic> json) {
    return true;
  }

  InlineObject113 copyWith({String Function()? status}) {
    return InlineObject113(status: status != null ? status() : this.status);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject113 && status == other.status;
  }

  @override
  int get hashCode {
    return status.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject113(status: $status)';
  }
}
