//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

final class InlineObject83Type {
  const InlineObject83Type._(this.value);

  factory InlineObject83Type.fromJson(String json) {
    return switch (json) {
      'Bot' => bot,
      'User' => user,
      'Organization' => organization,
      'Mannequin' => mannequin,
      _ => InlineObject83Type._(json),
    };
  }

  static const InlineObject83Type bot = InlineObject83Type._('Bot');

  static const InlineObject83Type user = InlineObject83Type._('User');

  static const InlineObject83Type organization = InlineObject83Type._(
    'Organization',
  );

  static const InlineObject83Type mannequin = InlineObject83Type._('Mannequin');

  static const List<InlineObject83Type> values = [
    bot,
    user,
    organization,
    mannequin,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject83Type && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject83Type($value)';
  }
}
