//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

final class InlineObject63PullRequestBaseRepoVisibility {const InlineObject63PullRequestBaseRepoVisibility._(this.value);

factory InlineObject63PullRequestBaseRepoVisibility.fromJson(String json) { return switch (json) {
  'public' => public,
  'private' => private,
  'internal' => internal,
  _ => InlineObject63PullRequestBaseRepoVisibility._(json),
}; }

static const InlineObject63PullRequestBaseRepoVisibility public = InlineObject63PullRequestBaseRepoVisibility._('public');

static const InlineObject63PullRequestBaseRepoVisibility private = InlineObject63PullRequestBaseRepoVisibility._('private');

static const InlineObject63PullRequestBaseRepoVisibility internal = InlineObject63PullRequestBaseRepoVisibility._('internal');

static const List<InlineObject63PullRequestBaseRepoVisibility> values = [public, private, internal];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject63PullRequestBaseRepoVisibility && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject63PullRequestBaseRepoVisibility($value)'; } 
 }
