//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

/// Whether users can pull changes from upstream when the branch is locked. Set to `true` to allow fork syncing. Set to `false` to prevent fork syncing.
final class ProtectedBranchAllowForkSyncing {
  const ProtectedBranchAllowForkSyncing({this.enabled = false});

  factory ProtectedBranchAllowForkSyncing.fromJson(Map<String, dynamic> json) {
    return ProtectedBranchAllowForkSyncing(
      enabled: json.containsKey('enabled') ? json['enabled'] as bool : false,
    );
  }

  final bool enabled;

  Map<String, dynamic> toJson() {
    return {'enabled': enabled};
  }

  static bool canParse(Map<String, dynamic> json) {
    return true;
  }

  ProtectedBranchAllowForkSyncing copyWith({bool Function()? enabled}) {
    return ProtectedBranchAllowForkSyncing(
      enabled: enabled != null ? enabled() : this.enabled,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is ProtectedBranchAllowForkSyncing && enabled == other.enabled;
  }

  @override
  int get hashCode {
    return enabled.hashCode;
  }

  @override
  String toString() {
    return 'ProtectedBranchAllowForkSyncing(enabled: $enabled)';
  }
}
