//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

import 'repos_update_request_security_and_analysis_secret_scanning_delegated_bypass_options_reviewers_reviewer_type.dart';

final class ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewers {
  const ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewers({
    required this.reviewerId,
    required this.reviewerType,
  });

  factory ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewers.fromJson(
    Map<String, dynamic> json,
  ) {
    return ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewers(
      reviewerId: (json['reviewer_id'] as num).toInt(),
      reviewerType:
          ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewersReviewerType.fromJson(
            json['reviewer_type'] as String,
          ),
    );
  }

  /// The ID of the team or role selected as a bypass reviewer
  final int reviewerId;

  /// The type of the bypass reviewer
  final ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewersReviewerType
  reviewerType;

  Map<String, dynamic> toJson() {
    return {'reviewer_id': reviewerId, 'reviewer_type': reviewerType.toJson()};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('reviewer_id') &&
        json['reviewer_id'] is num &&
        json.containsKey('reviewer_type');
  }

  ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewers
  copyWith({
    int? reviewerId,
    ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewersReviewerType?
    reviewerType,
  }) {
    return ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewers(
      reviewerId: reviewerId ?? this.reviewerId,
      reviewerType: reviewerType ?? this.reviewerType,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other
                is ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewers &&
            reviewerId == other.reviewerId &&
            reviewerType == other.reviewerType;
  }

  @override
  int get hashCode {
    return Object.hash(reviewerId, reviewerType);
  }

  @override
  String toString() {
    return 'ReposUpdateRequestSecurityAndAnalysisSecretScanningDelegatedBypassOptionsReviewers(reviewerId: $reviewerId, reviewerType: $reviewerType)';
  }
}
