//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'invoice.dart';/// String representing the object's type. Objects of the same type share the same value.
final class GetInvoicesSearchResponseObject {const GetInvoicesSearchResponseObject._(this.value);

factory GetInvoicesSearchResponseObject.fromJson(String json) { return switch (json) {
  'search_result' => searchResult,
  _ => GetInvoicesSearchResponseObject._(json),
}; }

static const GetInvoicesSearchResponseObject searchResult = GetInvoicesSearchResponseObject._('search_result');

static const List<GetInvoicesSearchResponseObject> values = [searchResult];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is GetInvoicesSearchResponseObject && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'GetInvoicesSearchResponseObject($value)'; } 
 }
/// 
final class GetInvoicesSearchResponse {const GetInvoicesSearchResponse({required this.data, required this.hasMore, this.nextPage, required this.object, this.totalCount, required this.url, });

factory GetInvoicesSearchResponse.fromJson(Map<String, dynamic> json) { return GetInvoicesSearchResponse(
  data: (json['data'] as List<dynamic>).map((e) => Invoice.fromJson(e as Map<String, dynamic>)).toList(),
  hasMore: json['has_more'] as bool,
  nextPage: json['next_page'] as String?,
  object: GetInvoicesSearchResponseObject.fromJson(json['object'] as String),
  totalCount: json['total_count'] != null ? (json['total_count'] as num).toInt() : null,
  url: json['url'] as String,
); }

final List<Invoice> data;

final bool hasMore;

final String? nextPage;

/// String representing the object's type. Objects of the same type share the same value.
final GetInvoicesSearchResponseObject object;

/// The total number of objects that match the query, only accurate up to 10,000.
final int? totalCount;

final String url;

Map<String, dynamic> toJson() { return {
  'data': data.map((e) => e.toJson()).toList(),
  'has_more': hasMore,
  'next_page': ?nextPage,
  'object': object.toJson(),
  'total_count': ?totalCount,
  'url': url,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('data') &&
      json.containsKey('has_more') && json['has_more'] is bool &&
      json.containsKey('object') &&
      json.containsKey('url') && json['url'] is String; } 
GetInvoicesSearchResponse copyWith({List<Invoice>? data, bool? hasMore, String? Function()? nextPage, GetInvoicesSearchResponseObject? object, int Function()? totalCount, String? url, }) { return GetInvoicesSearchResponse(
  data: data ?? this.data,
  hasMore: hasMore ?? this.hasMore,
  nextPage: nextPage != null ? nextPage() : this.nextPage,
  object: object ?? this.object,
  totalCount: totalCount != null ? totalCount() : this.totalCount,
  url: url ?? this.url,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is GetInvoicesSearchResponse &&
          listEquals(data, other.data) &&
          hasMore == other.hasMore &&
          nextPage == other.nextPage &&
          object == other.object &&
          totalCount == other.totalCount &&
          url == other.url; } 
@override int get hashCode { return Object.hash(Object.hashAll(data), hasMore, nextPage, object, totalCount, url); } 
@override String toString() { return 'GetInvoicesSearchResponse(data: $data, hasMore: $hasMore, nextPage: $nextPage, object: $object, totalCount: $totalCount, url: $url)'; } 
 }
