// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// Generated by degenerate from stripe-spec3.yaml
// OpenAPI spec version: 3.0.0

final class GetIdentityVerificationSessionsStatus {const GetIdentityVerificationSessionsStatus._(this.value);

factory GetIdentityVerificationSessionsStatus.fromJson(String json) { return switch (json) {
  'canceled' => canceled,
  'processing' => processing,
  'requires_input' => requiresInput,
  'verified' => verified,
  _ => GetIdentityVerificationSessionsStatus._(json),
}; }

static const GetIdentityVerificationSessionsStatus canceled = GetIdentityVerificationSessionsStatus._('canceled');

static const GetIdentityVerificationSessionsStatus processing = GetIdentityVerificationSessionsStatus._('processing');

static const GetIdentityVerificationSessionsStatus requiresInput = GetIdentityVerificationSessionsStatus._('requires_input');

static const GetIdentityVerificationSessionsStatus verified = GetIdentityVerificationSessionsStatus._('verified');

static const List<GetIdentityVerificationSessionsStatus> values = [canceled, processing, requiresInput, verified];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is GetIdentityVerificationSessionsStatus && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'GetIdentityVerificationSessionsStatus($value)'; } 
 }
