// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'payment_intent_payment_method_options_mobilepay.dart';import 'payment_intent_type_specific_payment_method_options_client.dart';typedef PaymentIntentPaymentMethodOptionsMobilepay2 = OneOf2<PaymentIntentPaymentMethodOptionsMobilepay,PaymentIntentTypeSpecificPaymentMethodOptionsClient>;
