// GENERATED CODE - DO NOT MODIFY BY HAND

import 'payments_primitives_payment_records_resource_payment_method_card_details_resource_installment_plan.dart';/// Installment plan selected for the payment.
final class PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentsPlan {const PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentsPlan({this.paymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentPlan});

factory PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentsPlan.fromJson(Map<String, dynamic> json) { return PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentsPlan(
  paymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentPlan: PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentPlan.canParse(json) ? PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentPlan.fromJson(json) : null,
); }

final PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentPlan? paymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentPlan;

/// At least one variant must be present.
bool get isValid { return paymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentPlan != null; } 
Map<String, dynamic> toJson() { return {
  ...?paymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentPlan?.toJson(),
}; } 
 }
