// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'payment_intent_payment_method_options_swish.dart';import 'payment_intent_type_specific_payment_method_options_client.dart';typedef PaymentIntentPaymentMethodOptionsSwish2 = OneOf2<PaymentIntentPaymentMethodOptionsSwish,PaymentIntentTypeSpecificPaymentMethodOptionsClient>;