//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'payment_intent_payment_method_options_param25_mandate_options.dart';final class PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage {const PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage._(this.value);

factory PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage.fromJson(String json) { return switch (json) {
  '' => $empty,
  'none' => none,
  'off_session' => offSession,
  _ => PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage._(json),
}; }

static const PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage $empty = PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage._('');

static const PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage none = PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage._('none');

static const PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage offSession = PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage._('off_session');

static const List<PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage> values = [$empty, none, offSession];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage($value)'; } 
 }
final class PaymentIntentPaymentMethodOptionsParam25 {const PaymentIntentPaymentMethodOptionsParam25({this.mandateOptions, this.setupFutureUsage, });

factory PaymentIntentPaymentMethodOptionsParam25.fromJson(Map<String, dynamic> json) { return PaymentIntentPaymentMethodOptionsParam25(
  mandateOptions: json['mandate_options'] != null ? PaymentIntentPaymentMethodOptionsParam25MandateOptions.fromJson(json['mandate_options'] as Map<String, dynamic>) : null,
  setupFutureUsage: json['setup_future_usage'] != null ? PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage.fromJson(json['setup_future_usage'] as String) : null,
); }

final PaymentIntentPaymentMethodOptionsParam25MandateOptions? mandateOptions;

final PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage? setupFutureUsage;

Map<String, dynamic> toJson() { return {
  if (mandateOptions != null) 'mandate_options': mandateOptions?.toJson(),
  if (setupFutureUsage != null) 'setup_future_usage': setupFutureUsage?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PaymentIntentPaymentMethodOptionsParam25 copyWith({PaymentIntentPaymentMethodOptionsParam25MandateOptions Function()? mandateOptions, PaymentIntentPaymentMethodOptionsParam25SetupFutureUsage Function()? setupFutureUsage, }) { return PaymentIntentPaymentMethodOptionsParam25(
  mandateOptions: mandateOptions != null ? mandateOptions() : this.mandateOptions,
  setupFutureUsage: setupFutureUsage != null ? setupFutureUsage() : this.setupFutureUsage,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PaymentIntentPaymentMethodOptionsParam25 &&
          mandateOptions == other.mandateOptions &&
          setupFutureUsage == other.setupFutureUsage; } 
@override int get hashCode { return Object.hash(mandateOptions, setupFutureUsage); } 
@override String toString() { return 'PaymentIntentPaymentMethodOptionsParam25(mandateOptions: $mandateOptions, setupFutureUsage: $setupFutureUsage)'; } 
 }
