// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'payment_intent_payment_method_options_payto.dart';import 'payment_intent_type_specific_payment_method_options_client.dart';typedef PaymentIntentPaymentMethodOptionsPayto2 = OneOf2<PaymentIntentPaymentMethodOptionsPayto,PaymentIntentTypeSpecificPaymentMethodOptionsClient>;