// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'payment_intent_type_specific_payment_method_options_client.dart';import 'payment_method_options_interac_present.dart';typedef PaymentIntentPaymentMethodOptionsInteracPresent = OneOf2<PaymentMethodOptionsInteracPresent,PaymentIntentTypeSpecificPaymentMethodOptionsClient>;