// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// Generated by degenerate from stripe-spec3.yaml
// OpenAPI spec version: 3.0.0

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'post_subscription_schedules_request_phases_add_invoice_items_discounts.dart';import 'post_subscription_schedules_request_phases_add_invoice_items_period.dart';import 'post_subscription_schedules_request_phases_add_invoice_items_price_data.dart';import 'post_subscription_schedules_request_phases_add_invoice_items_tax_rates.dart';final class PostSubscriptionSchedulesRequestPhasesAddInvoiceItems {const PostSubscriptionSchedulesRequestPhasesAddInvoiceItems({this.discounts, this.metadata, this.period, this.price, this.priceData, this.quantity, this.taxRates, });

factory PostSubscriptionSchedulesRequestPhasesAddInvoiceItems.fromJson(Map<String, dynamic> json) { return PostSubscriptionSchedulesRequestPhasesAddInvoiceItems(
  discounts: (json['discounts'] as List<dynamic>?)?.map((e) => PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsDiscounts.fromJson(e as Map<String, dynamic>)).toList(),
  metadata: (json['metadata'] as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, v as String)),
  period: json['period'] != null ? PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsPeriod.fromJson(json['period'] as Map<String, dynamic>) : null,
  price: json['price'] as String?,
  priceData: json['price_data'] != null ? PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsPriceData.fromJson(json['price_data'] as Map<String, dynamic>) : null,
  quantity: json['quantity'] != null ? (json['quantity'] as num).toInt() : null,
  taxRates: json['tax_rates'] != null ? OneOf2.parse(json['tax_rates'], fromA: (v) => (v as List<dynamic>).map((e) => e as String).toList(), fromB: (v) => PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsTaxRatesVariant2.fromJson(v as String),) : null,
); }

final List<PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsDiscounts>? discounts;

final Map<String,String>? metadata;

final PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsPeriod? period;

final String? price;

final PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsPriceData? priceData;

final int? quantity;

final PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsTaxRates? taxRates;

Map<String, dynamic> toJson() { return {
  if (discounts != null) 'discounts': discounts?.map((e) => e.toJson()).toList(),
  'metadata': ?metadata,
  if (period != null) 'period': period?.toJson(),
  'price': ?price,
  if (priceData != null) 'price_data': priceData?.toJson(),
  'quantity': ?quantity,
  if (taxRates != null) 'tax_rates': taxRates?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostSubscriptionSchedulesRequestPhasesAddInvoiceItems copyWith({List<PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsDiscounts> Function()? discounts, Map<String, String> Function()? metadata, PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsPeriod Function()? period, String Function()? price, PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsPriceData Function()? priceData, int Function()? quantity, PostSubscriptionSchedulesRequestPhasesAddInvoiceItemsTaxRates Function()? taxRates, }) { return PostSubscriptionSchedulesRequestPhasesAddInvoiceItems(
  discounts: discounts != null ? discounts() : this.discounts,
  metadata: metadata != null ? metadata() : this.metadata,
  period: period != null ? period() : this.period,
  price: price != null ? price() : this.price,
  priceData: priceData != null ? priceData() : this.priceData,
  quantity: quantity != null ? quantity() : this.quantity,
  taxRates: taxRates != null ? taxRates() : this.taxRates,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostSubscriptionSchedulesRequestPhasesAddInvoiceItems &&
          listEquals(discounts, other.discounts) &&
          metadata == other.metadata &&
          period == other.period &&
          price == other.price &&
          priceData == other.priceData &&
          quantity == other.quantity &&
          taxRates == other.taxRates; } 
@override int get hashCode { return Object.hash(Object.hashAll(discounts ?? const []), metadata, period, price, priceData, quantity, taxRates); } 
@override String toString() { return 'PostSubscriptionSchedulesRequestPhasesAddInvoiceItems(discounts: $discounts, metadata: $metadata, period: $period, price: $price, priceData: $priceData, quantity: $quantity, taxRates: $taxRates)'; } 
 }
