// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// Generated by degenerate from stripe-spec3.yaml
// OpenAPI spec version: 3.0.0

import 'package:degenerate_runtime/degenerate_runtime.dart';final class PostReviewsReviewApproveRequest {const PostReviewsReviewApproveRequest({this.expand});

factory PostReviewsReviewApproveRequest.fromJson(Map<String, dynamic> json) { return PostReviewsReviewApproveRequest(
  expand: (json['expand'] as List<dynamic>?)?.map((e) => e as String).toList(),
); }

/// Specifies which fields in the response should be expanded.
final List<String>? expand;

Map<String, dynamic> toJson() { return {
  'expand': ?expand,
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostReviewsReviewApproveRequest copyWith({List<String> Function()? expand}) { return PostReviewsReviewApproveRequest(
  expand: expand != null ? expand() : this.expand,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostReviewsReviewApproveRequest &&
          listEquals(expand, other.expand); } 
@override int get hashCode { return Object.hashAll(expand ?? const []).hashCode; } 
@override String toString() { return 'PostReviewsReviewApproveRequest(expand: $expand)'; } 
 }
