//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class PostPaymentIntentsRequestPaymentMethodDataAlma {const PostPaymentIntentsRequestPaymentMethodDataAlma();

factory PostPaymentIntentsRequestPaymentMethodDataAlma.fromJson(Map<String, dynamic> json) { return PostPaymentIntentsRequestPaymentMethodDataAlma(

); }

Map<String, dynamic> toJson() { return {

}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostPaymentIntentsRequestPaymentMethodDataAlma copyWith() { return PostPaymentIntentsRequestPaymentMethodDataAlma(

); } 
@override bool operator ==(Object other) { return identical(this, other) || other is PostPaymentIntentsRequestPaymentMethodDataAlma; } 
@override int get hashCode { return runtimeType.hashCode; } 
@override String toString() { return 'PostPaymentIntentsRequestPaymentMethodDataAlma()'; } 
 }
