// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// Generated by degenerate from stripe-spec3.yaml
// OpenAPI spec version: 3.0.0

import 'package:degenerate_runtime/degenerate_runtime.dart';final class PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhoneVariant2 {const PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhoneVariant2._(this.value);

factory PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhoneVariant2.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhoneVariant2._(json),
}; }

static const PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhoneVariant2 $empty = PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhoneVariant2._('');

static const List<PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhoneVariant2> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhoneVariant2 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhoneVariant2($value)'; } 
 }
typedef PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhone = OneOf2<String,PostTreasuryOutboundPaymentsRequestDestinationPaymentMethodDataBillingDetailsPhoneVariant2>;