// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// Generated by degenerate from stripe-spec3.yaml
// OpenAPI spec version: 3.0.0

final class PostSetupIntentsIntentRequestPaymentMethodOptionsAmazonPay {const PostSetupIntentsIntentRequestPaymentMethodOptionsAmazonPay();

factory PostSetupIntentsIntentRequestPaymentMethodOptionsAmazonPay.fromJson(Map<String, dynamic> json) { return PostSetupIntentsIntentRequestPaymentMethodOptionsAmazonPay(

); }

Map<String, dynamic> toJson() { return {

}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostSetupIntentsIntentRequestPaymentMethodOptionsAmazonPay copyWith() { return PostSetupIntentsIntentRequestPaymentMethodOptionsAmazonPay(

); } 
@override bool operator ==(Object other) { return identical(this, other) || other is PostSetupIntentsIntentRequestPaymentMethodOptionsAmazonPay; } 
@override int get hashCode { return runtimeType.hashCode; } 
@override String toString() { return 'PostSetupIntentsIntentRequestPaymentMethodOptionsAmazonPay()'; } 
 }
