// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// Generated by degenerate from stripe-spec3.yaml
// OpenAPI spec version: 3.0.0

import 'package:degenerate_runtime/degenerate_runtime.dart';final class PostSubscriptionsRequestMetadataVariant2 {const PostSubscriptionsRequestMetadataVariant2._(this.value);

factory PostSubscriptionsRequestMetadataVariant2.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => PostSubscriptionsRequestMetadataVariant2._(json),
}; }

static const PostSubscriptionsRequestMetadataVariant2 $empty = PostSubscriptionsRequestMetadataVariant2._('');

static const List<PostSubscriptionsRequestMetadataVariant2> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PostSubscriptionsRequestMetadataVariant2 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PostSubscriptionsRequestMetadataVariant2($value)'; } 
 }
typedef PostSubscriptionsRequestMetadata = OneOf2<Map<String,String>,PostSubscriptionsRequestMetadataVariant2>;