//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// Parameters required for the redirect flow. Required if the source is authenticated by a redirect (`flow` is `redirect`).
final class PostSourcesRequestRedirect {const PostSourcesRequestRedirect({required this.returnUrl});

factory PostSourcesRequestRedirect.fromJson(Map<String, dynamic> json) { return PostSourcesRequestRedirect(
  returnUrl: json['return_url'] as String,
); }

final String returnUrl;

Map<String, dynamic> toJson() { return {
  'return_url': returnUrl,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('return_url') && json['return_url'] is String; } 
PostSourcesRequestRedirect copyWith({String? returnUrl}) { return PostSourcesRequestRedirect(
  returnUrl: returnUrl ?? this.returnUrl,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostSourcesRequestRedirect &&
          returnUrl == other.returnUrl; } 
@override int get hashCode { return returnUrl.hashCode; } 
@override String toString() { return 'PostSourcesRequestRedirect(returnUrl: $returnUrl)'; } 
 }
