//  dart format off
//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class PostAccountSessionsRequestComponentsInstantPayoutsPromotionFeatures {const PostAccountSessionsRequestComponentsInstantPayoutsPromotionFeatures({this.disableStripeUserAuthentication, this.externalAccountCollection, this.instantPayouts, });

factory PostAccountSessionsRequestComponentsInstantPayoutsPromotionFeatures.fromJson(Map<String, dynamic> json) { return PostAccountSessionsRequestComponentsInstantPayoutsPromotionFeatures(
  disableStripeUserAuthentication: json['disable_stripe_user_authentication'] as bool?,
  externalAccountCollection: json['external_account_collection'] as bool?,
  instantPayouts: json['instant_payouts'] as bool?,
); }

final bool? disableStripeUserAuthentication;

final bool? externalAccountCollection;

final bool? instantPayouts;

Map<String, dynamic> toJson() { return {
  'disable_stripe_user_authentication': ?disableStripeUserAuthentication,
  'external_account_collection': ?externalAccountCollection,
  'instant_payouts': ?instantPayouts,
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostAccountSessionsRequestComponentsInstantPayoutsPromotionFeatures copyWith({bool Function()? disableStripeUserAuthentication, bool Function()? externalAccountCollection, bool Function()? instantPayouts, }) { return PostAccountSessionsRequestComponentsInstantPayoutsPromotionFeatures(
  disableStripeUserAuthentication: disableStripeUserAuthentication != null ? disableStripeUserAuthentication() : this.disableStripeUserAuthentication,
  externalAccountCollection: externalAccountCollection != null ? externalAccountCollection() : this.externalAccountCollection,
  instantPayouts: instantPayouts != null ? instantPayouts() : this.instantPayouts,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostAccountSessionsRequestComponentsInstantPayoutsPromotionFeatures &&
          disableStripeUserAuthentication == other.disableStripeUserAuthentication &&
          externalAccountCollection == other.externalAccountCollection &&
          instantPayouts == other.instantPayouts; } 
@override int get hashCode { return Object.hash(disableStripeUserAuthentication, externalAccountCollection, instantPayouts); } 
@override String toString() { return 'PostAccountSessionsRequestComponentsInstantPayoutsPromotionFeatures(disableStripeUserAuthentication: $disableStripeUserAuthentication, externalAccountCollection: $externalAccountCollection, instantPayouts: $instantPayouts)'; } 
 }
