// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'setup_intent_payment_method_options_card_present.dart';import 'setup_intent_type_specific_payment_method_options_client.dart';typedef SetupIntentPaymentMethodOptionsCardPresent2 = OneOf2<SetupIntentPaymentMethodOptionsCardPresent,SetupIntentTypeSpecificPaymentMethodOptionsClient>;
