// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'setup_intent_payment_method_options_us_bank_account.dart';import 'setup_intent_type_specific_payment_method_options_client.dart';typedef SetupIntentPaymentMethodOptionsUsBankAccount2 = OneOf2<SetupIntentPaymentMethodOptionsUsBankAccount,SetupIntentTypeSpecificPaymentMethodOptionsClient>;