// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'setup_intent_payment_method_options_bacs_debit.dart';import 'setup_intent_type_specific_payment_method_options_client.dart';typedef SetupIntentPaymentMethodOptionsBacsDebit2 = OneOf2<SetupIntentPaymentMethodOptionsBacsDebit,SetupIntentTypeSpecificPaymentMethodOptionsClient>;