//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from twilio-api-v2010.yaml
//  OpenAPI spec version: 3.0.1

import 'dart:convert';import 'package:degenerate_runtime/degenerate_runtime.dart';import '../models/account_conference.dart';import '../models/conference_enum_status.dart';import '../models/list_conference_response.dart';import '../models/update_conference_request.dart';/// Api20100401ConferenceApi operations.
///
/// All operations return [ApiResult] — use pattern matching to handle
/// success, error, and exception cases.
final class Api20100401ConferenceApi {const Api20100401ConferenceApi(this._config);

final ApiConfig _config;

/// Fetch an instance of a conference
///
/// `GET /2010-04-01/Accounts/{AccountSid}/Conferences/{Sid}.json`
Future<ApiResult<AccountConference, Never>> fetchConference({required String accountSid, required String sid, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/2010-04-01/Accounts/${Uri.encodeComponent(accountSid)}/Conferences/${Uri.encodeComponent(sid)}.json',
  headers: headers,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return AccountConference.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// 
///
/// `POST /2010-04-01/Accounts/{AccountSid}/Conferences/{Sid}.json`
Future<ApiResult<AccountConference, Never>> updateConference({required String accountSid, required String sid, UpdateConferenceRequest? body, RequestOptions? options, }) async  { final headers = <String, String>{..._config.defaultHeaders};
headers['Content-Type'] = 'application/x-www-form-urlencoded';

final request = ApiRequest(
  method: 'POST',
  path: '/2010-04-01/Accounts/${Uri.encodeComponent(accountSid)}/Conferences/${Uri.encodeComponent(sid)}.json',
  headers: headers,
  body: [
    if (body.status case final status$?)
      'Status=${Uri.encodeQueryComponent(status$.toJson())}',
    if (body.announceUrl case final announceUrl$?)
      'AnnounceUrl=${Uri.encodeQueryComponent(announceUrl$.toString())}',
    if (body.announceMethod case final announceMethod$?)
      'AnnounceMethod=${Uri.encodeQueryComponent(announceMethod$.toJson())}',
  ].join('&'),
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return AccountConference.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Retrieve a list of conferences belonging to the account used to make the request
///
/// `GET /2010-04-01/Accounts/{AccountSid}/Conferences.json`
Future<ApiResult<ListConferenceResponse, Never>> listConference({required String accountSid, String? dateCreated, String? dateCreatedBefore, String? dateCreatedAfter, String? dateUpdated, String? dateUpdatedBefore, String? dateUpdatedAfter, String? friendlyName, ConferenceEnumStatus? status, int? pageSize, int? page, String? pageToken, RequestOptions? options, }) async  { final queryParameters = <String, String>{..._config.defaultQueryParameters};
final queryParametersList = <ApiQueryParameter>[];
if (dateCreated != null) queryParameters['DateCreated'] = dateCreated;
if (dateCreatedBefore != null) queryParameters['DateCreated<'] = dateCreatedBefore;
if (dateCreatedAfter != null) queryParameters['DateCreated>'] = dateCreatedAfter;
if (dateUpdated != null) queryParameters['DateUpdated'] = dateUpdated;
if (dateUpdatedBefore != null) queryParameters['DateUpdated<'] = dateUpdatedBefore;
if (dateUpdatedAfter != null) queryParameters['DateUpdated>'] = dateUpdatedAfter;
if (friendlyName != null) queryParameters['FriendlyName'] = friendlyName;
if (status != null) queryParameters['Status'] = status.toJson();
if (pageSize != null) queryParameters['PageSize'] = pageSize.toString();
if (page != null) queryParameters['Page'] = page.toString();
if (pageToken != null) queryParameters['PageToken'] = pageToken;

final headers = <String, String>{..._config.defaultHeaders};

final request = ApiRequest(
  method: 'GET',
  path: '/2010-04-01/Accounts/${Uri.encodeComponent(accountSid)}/Conferences.json',
  headers: headers,
  queryParameters: queryParameters,
  queryParametersList: queryParametersList,
  options: options,
);

return _execute(
  request,
  onSuccess: (response) {
    return ListConferenceResponse.fromJson(jsonDecode(response.body) as Map<String, dynamic>);
  },
);
 } 
/// Shared execution pipeline: interceptors -> send -> deserialize.
Future<ApiResult<T, E>> _execute<T,E>(ApiRequest request, {required T Function(ApiResponse) onSuccess, E? Function(ApiResponse)? onError, }) async  { try {
  final cancelToken = request.options?.cancelToken;
  if (cancelToken?.isCancelled ?? false) throw const CancelledException();

  final effectiveTimeout = request.options?.timeout ?? _config.timeout;
  final extraHeaders = request.options?.extraHeaders;
  final effectiveRequest = extraHeaders != null
      ? request.copyWith(headers: {...request.headers, ...extraHeaders})
      : request;

  final chain = buildInterceptorChain(
    interceptors: _config.interceptors,
    terminal: (req) async {
      if (cancelToken?.isCancelled ?? false) throw const CancelledException();
      final future = _config.client.send(req);
      return effectiveTimeout != null
          ? await future.timeout(effectiveTimeout)
          : await future;
    },
  );

  final response = await chain(effectiveRequest);

  try {
    if (response.isSuccessful) {
      return ApiSuccess(
        onSuccess(response),
        statusCode: response.statusCode,
        headers: response.headers,
      );
    }
    return ApiError(
      statusCode: response.statusCode,
      error: onError != null ? onError(response) : null,
      rawError: response.body,
      headers: response.headers,
    );
  } catch (e, st) {
    return ApiParseException(e, st, response: response);
  }
} catch (e, st) {
  return ApiException(e, st);
}
 } 
 }
