//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

/// The enablement status of secret scanning push protection
final class CodeSecurityCreateConfigurationRequestSecretScanningPushProtection {const CodeSecurityCreateConfigurationRequestSecretScanningPushProtection._(this.value);

factory CodeSecurityCreateConfigurationRequestSecretScanningPushProtection.fromJson(String json) { return switch (json) {
  'enabled' => enabled,
  'disabled' => disabled,
  'not_set' => notSet,
  _ => CodeSecurityCreateConfigurationRequestSecretScanningPushProtection._(json),
}; }

static const CodeSecurityCreateConfigurationRequestSecretScanningPushProtection enabled = CodeSecurityCreateConfigurationRequestSecretScanningPushProtection._('enabled');

static const CodeSecurityCreateConfigurationRequestSecretScanningPushProtection disabled = CodeSecurityCreateConfigurationRequestSecretScanningPushProtection._('disabled');

static const CodeSecurityCreateConfigurationRequestSecretScanningPushProtection notSet = CodeSecurityCreateConfigurationRequestSecretScanningPushProtection._('not_set');

static const List<CodeSecurityCreateConfigurationRequestSecretScanningPushProtection> values = [enabled, disabled, notSet];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is CodeSecurityCreateConfigurationRequestSecretScanningPushProtection && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'CodeSecurityCreateConfigurationRequestSecretScanningPushProtection($value)'; } 
 }
