//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

final class InlineObject40Privacy {const InlineObject40Privacy._(this.value);

factory InlineObject40Privacy.fromJson(String json) { return switch (json) {
  'open' => open,
  'closed' => closed,
  'secret' => secret,
  _ => InlineObject40Privacy._(json),
}; }

static const InlineObject40Privacy open = InlineObject40Privacy._('open');

static const InlineObject40Privacy closed = InlineObject40Privacy._('closed');

static const InlineObject40Privacy secret = InlineObject40Privacy._('secret');

static const List<InlineObject40Privacy> values = [open, closed, secret];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject40Privacy && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject40Privacy($value)'; } 
 }
