//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

/// The policy controlling who can create pull requests: all or collaborators_only.
final class WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy {const WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy._(this.value);

factory WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy.fromJson(String json) { return switch (json) {
  'all' => all,
  'collaborators_only' => collaboratorsOnly,
  _ => WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy._(json),
}; }

static const WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy all = WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy._('all');

static const WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy collaboratorsOnly = WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy._('collaborators_only');

static const List<WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy> values = [all, collaboratorsOnly];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'WebhookPullRequestReviewSubmittedPullRequestBaseRepoPullRequestCreationPolicy($value)'; } 
 }
