//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

/// The policy controlling who can create pull requests: all or collaborators_only.
final class WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy {const WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy._(this.value);

factory WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy.fromJson(String json) { return switch (json) {
  'all' => all,
  'collaborators_only' => collaboratorsOnly,
  _ => WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy._(json),
}; }

static const WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy all = WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy._('all');

static const WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy collaboratorsOnly = WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy._('collaborators_only');

static const List<WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy> values = [all, collaboratorsOnly];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'WebhookPullRequestReviewCommentEditedPullRequestBaseRepoPullRequestCreationPolicy($value)'; } 
 }
