//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

/// A value that is one of: `int`, `DateTime`.
sealed class WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt {const WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt();

factory WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt.fromJson(Object? json) { return switch (json) {
  final int v => WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAtInt(v),
  final DateTime v => WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAtDateTime(v),
  _ => WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt$Unknown(json),
}; }

/// The underlying raw value.
Object? get value;
Object? toJson() { return value; } 
 }
final class WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAtInt extends WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt {const WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAtInt(this._value);

final int _value;

@override int get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAtInt && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt.int($_value)'; } 
 }
final class WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAtDateTime extends WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt {const WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAtDateTime(this._value);

final DateTime _value;

@override DateTime get value { return _value; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAtDateTime && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt.dateTime($_value)'; } 
 }
/// An unknown variant not defined in the OpenAPI spec.
final class WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt$Unknown extends WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt {const WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt$Unknown(this._value);

final Object? _value;

@override Object get value { return _value ?? ''; } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt$Unknown && _value == other._value; } 
@override int get hashCode { return _value.hashCode; } 
@override String toString() { return 'WebhookPullRequestSynchronizePullRequestBaseRepoCreatedAt.unknown($_value)'; } 
 }
