//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

import 'dart:convert';
import '../client/api_client.dart';
import '../client/api_config.dart';
import '../client/api_result.dart';
import '../models/campaign_state.dart';
import '../models/campaign_summary.dart';
import '../models/campaigns_create_campaign_request.dart';
import '../models/campaigns_list_org_campaigns_direction.dart';
import '../models/campaigns_list_org_campaigns_sort.dart';
import '../models/campaigns_update_campaign_request.dart';

/// CampaignsApi operations.
///
/// All operations return [ApiResult] — use pattern matching to handle
/// success, error, and exception cases.
final class CampaignsApi {
  const CampaignsApi(this._config);

  final ApiConfig _config;

  /// List campaigns for an organization
  ///
  /// Lists campaigns in an organization.
  ///
  /// The authenticated user must be an owner or security manager for the organization to use this endpoint.
  ///
  /// OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint.
  ///
  /// `GET /orgs/{org}/campaigns`
  Future<ApiResult<List<CampaignSummary>>> campaignsListOrgCampaigns({
    required String org,
    int? page,
    int? perPage,
    CampaignsListOrgCampaignsDirection? direction,
    CampaignState? state,
    CampaignsListOrgCampaignsSort? sort,
  }) async {
    final request = ApiRequest(
      method: 'GET',
      path: '/orgs/${Uri.encodeComponent(org)}/campaigns',
      headers: {..._config.defaultHeaders},
      queryParameters: {
        if (page != null) 'page': page.toString(),
        if (perPage != null) 'per_page': perPage.toString(),
        if (direction != null) 'direction': direction.toJson(),
        if (state != null) 'state': state.toJson(),
        if (sort != null) 'sort': sort.toJson(),
      },
    );

    return _execute(
      request,
      onSuccess: (response) {
        final json = jsonDecode(response.body) as List<dynamic>;
        return json
            .map((e) => CampaignSummary.fromJson(e as Map<String, dynamic>))
            .toList();
      },
    );
  }

  /// Create a campaign for an organization
  ///
  /// Create a campaign for an organization.
  ///
  /// The authenticated user must be an owner or security manager for the organization to use this endpoint.
  ///
  /// OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint.
  ///
  /// Fine-grained tokens must have the "Code scanning alerts" repository permissions (read) on all repositories included
  /// in the campaign.
  ///
  /// `POST /orgs/{org}/campaigns`
  Future<ApiResult<CampaignSummary>> campaignsCreateCampaign({
    required String org,
    required CampaignsCreateCampaignRequest body,
  }) async {
    final request = ApiRequest(
      method: 'POST',
      path: '/orgs/${Uri.encodeComponent(org)}/campaigns',
      headers: {..._config.defaultHeaders, 'Content-Type': 'application/json'},
      body: jsonEncode(body.toJson()),
    );

    return _execute(
      request,
      onSuccess: (response) {
        return CampaignSummary.fromJson(
          jsonDecode(response.body) as Map<String, dynamic>,
        );
      },
    );
  }

  /// Get a campaign for an organization
  ///
  /// Gets a campaign for an organization.
  ///
  /// The authenticated user must be an owner or security manager for the organization to use this endpoint.
  ///
  /// OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint.
  ///
  /// `GET /orgs/{org}/campaigns/{campaign_number}`
  Future<ApiResult<CampaignSummary>> campaignsGetCampaignSummary({
    required String org,
    required int campaignNumber,
  }) async {
    final request = ApiRequest(
      method: 'GET',
      path:
          '/orgs/${Uri.encodeComponent(org)}/campaigns/${Uri.encodeComponent(campaignNumber.toString())}',
      headers: {..._config.defaultHeaders},
    );

    return _execute(
      request,
      onSuccess: (response) {
        return CampaignSummary.fromJson(
          jsonDecode(response.body) as Map<String, dynamic>,
        );
      },
    );
  }

  /// Update a campaign
  ///
  /// Updates a campaign in an organization.
  ///
  /// The authenticated user must be an owner or security manager for the organization to use this endpoint.
  ///
  /// OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint.
  ///
  /// `PATCH /orgs/{org}/campaigns/{campaign_number}`
  Future<ApiResult<CampaignSummary>> campaignsUpdateCampaign({
    required String org,
    required int campaignNumber,
    required CampaignsUpdateCampaignRequest body,
  }) async {
    final request = ApiRequest(
      method: 'PATCH',
      path:
          '/orgs/${Uri.encodeComponent(org)}/campaigns/${Uri.encodeComponent(campaignNumber.toString())}',
      headers: {..._config.defaultHeaders, 'Content-Type': 'application/json'},
      body: jsonEncode(body.toJson()),
    );

    return _execute(
      request,
      onSuccess: (response) {
        return CampaignSummary.fromJson(
          jsonDecode(response.body) as Map<String, dynamic>,
        );
      },
    );
  }

  /// Delete a campaign for an organization
  ///
  /// Deletes a campaign in an organization.
  ///
  /// The authenticated user must be an owner or security manager for the organization to use this endpoint.
  ///
  /// OAuth app tokens and personal access tokens (classic) need the `security_events` scope to use this endpoint.
  ///
  /// `DELETE /orgs/{org}/campaigns/{campaign_number}`
  Future<ApiResult<void>> campaignsDeleteCampaign({
    required String org,
    required int campaignNumber,
  }) async {
    final request = ApiRequest(
      method: 'DELETE',
      path:
          '/orgs/${Uri.encodeComponent(org)}/campaigns/${Uri.encodeComponent(campaignNumber.toString())}',
      headers: {..._config.defaultHeaders},
    );

    return _execute(request, onSuccess: (_) {});
  }

  /// Shared execution pipeline: interceptors -> send -> deserialize.
  Future<ApiResult<T>> _execute<T>(
    ApiRequest request, {
    required T Function(ApiResponse) onSuccess,
  }) async {
    var req = request;
    try {
      for (final interceptor in _config.interceptors) {
        req = await interceptor.onRequest(req);
      }

      var response = _config.timeout != null
          ? await _config.client.send(req).timeout(_config.timeout!)
          : await _config.client.send(req);

      for (final interceptor in _config.interceptors) {
        response = await interceptor.onResponse(response);
      }

      if (response.isSuccessful) {
        return ApiSuccess(
          onSuccess(response),
          statusCode: response.statusCode,
          headers: response.headers,
        );
      }
      return ApiError(
        statusCode: response.statusCode,
        rawBody: response.body,
        headers: response.headers,
      );
    } catch (e, st) {
      for (final interceptor in _config.interceptors) {
        try {
          final recovered = await interceptor.onError(e, st, req);
          if (recovered.isSuccessful) {
            return ApiSuccess(
              onSuccess(recovered),
              statusCode: recovered.statusCode,
              headers: recovered.headers,
            );
          }
          return ApiError(
            statusCode: recovered.statusCode,
            rawBody: recovered.body,
            headers: recovered.headers,
          );
        } catch (_) {
          // Interceptor couldn't handle it, continue to next or fall through
        }
      }
      return ApiException(e, st);
    }
  }
}
