//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'async_batch4_requests.dart';import 'messages46.dart';import 'prompt38.dart';final class AsyncBatch4 {const AsyncBatch4({required this.requests});

factory AsyncBatch4.fromJson(Map<String, dynamic> json) { return AsyncBatch4(
  requests: (json['requests'] as List<dynamic>).map((e) => OneOf2.parse(e, fromA: (v) => Prompt38.fromJson(v as Map<String, dynamic>), fromB: (v) => Messages46.fromJson(v as Map<String, dynamic>),)).toList(),
); }

final List<AsyncBatch4Requests> requests;

Map<String, dynamic> toJson() { return {
  'requests': requests.map((e) => e.toJson()).toList(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('requests'); } 
AsyncBatch4 copyWith({List<AsyncBatch4Requests>? requests}) { return AsyncBatch4(
  requests: requests ?? this.requests,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is AsyncBatch4 &&
          listEquals(requests, other.requests); } 
@override int get hashCode { return Object.hashAll(requests).hashCode; } 
@override String toString() { return 'AsyncBatch4(requests: $requests)'; } 
 }
