// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// Generated by degenerate from cloudflare.yaml
// OpenAPI spec version: 3.0.3

/// Automatically update to the newest bot detection models created by Cloudflare as they are released. [Learn more.](https://developers.cloudflare.com/bots/reference/machine-learning-models#model-versions-and-release-notes)
extension type const BotManagementAutoUpdateModel(bool value) {
factory BotManagementAutoUpdateModel.fromJson(bool json) => BotManagementAutoUpdateModel(json);

bool toJson() => value;

}
