// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'delete_presets_preset_id_response_data_permissions_plugins_config_variant2.dart';typedef DeletePresetsPresetIdResponseDataPermissionsPluginsConfig = OneOf2<String,DeletePresetsPresetIdResponseDataPermissionsPluginsConfigVariant2>;
