// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'patch_presets_preset_id_response_data_permissions_plugins_config_variant2.dart';typedef PatchPresetsPresetIdResponseDataPermissionsPluginsConfig = OneOf2<String,PatchPresetsPresetIdResponseDataPermissionsPluginsConfigVariant2>;
