//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class RadarGetHttpTopAsesByDeviceTypeBrowserFamily {const RadarGetHttpTopAsesByDeviceTypeBrowserFamily._(this.value);

factory RadarGetHttpTopAsesByDeviceTypeBrowserFamily.fromJson(String json) { return switch (json) {
  'CHROME' => chrome,
  'EDGE' => edge,
  'FIREFOX' => firefox,
  'SAFARI' => safari,
  _ => RadarGetHttpTopAsesByDeviceTypeBrowserFamily._(json),
}; }

static const RadarGetHttpTopAsesByDeviceTypeBrowserFamily chrome = RadarGetHttpTopAsesByDeviceTypeBrowserFamily._('CHROME');

static const RadarGetHttpTopAsesByDeviceTypeBrowserFamily edge = RadarGetHttpTopAsesByDeviceTypeBrowserFamily._('EDGE');

static const RadarGetHttpTopAsesByDeviceTypeBrowserFamily firefox = RadarGetHttpTopAsesByDeviceTypeBrowserFamily._('FIREFOX');

static const RadarGetHttpTopAsesByDeviceTypeBrowserFamily safari = RadarGetHttpTopAsesByDeviceTypeBrowserFamily._('SAFARI');

static const List<RadarGetHttpTopAsesByDeviceTypeBrowserFamily> values = [chrome, edge, firefox, safari];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is RadarGetHttpTopAsesByDeviceTypeBrowserFamily && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'RadarGetHttpTopAsesByDeviceTypeBrowserFamily($value)'; } 
 }
