//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// String representing the object's type. Objects of the same type share the same value.
final class BalanceSettingsObject {
  const BalanceSettingsObject._(this.value);

  factory BalanceSettingsObject.fromJson(String json) {
    return switch (json) {
      'balance_settings' => balanceSettings,
      _ => BalanceSettingsObject._(json),
    };
  }

  static const BalanceSettingsObject balanceSettings = BalanceSettingsObject._(
    'balance_settings',
  );

  static const List<BalanceSettingsObject> values = [balanceSettings];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is BalanceSettingsObject && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'BalanceSettingsObject($value)';
  }
}
