//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'bank_connections_resource_balance_refresh_status.dart';

///
final class BankConnectionsResourceBalanceRefresh {
  const BankConnectionsResourceBalanceRefresh({
    required this.lastAttemptedAt,
    this.nextRefreshAvailableAt,
    required this.status,
  });

  factory BankConnectionsResourceBalanceRefresh.fromJson(
    Map<String, dynamic> json,
  ) {
    return BankConnectionsResourceBalanceRefresh(
      lastAttemptedAt: (json['last_attempted_at'] as num).toInt(),
      nextRefreshAvailableAt: json['next_refresh_available_at'] != null
          ? (json['next_refresh_available_at'] as num).toInt()
          : null,
      status: BankConnectionsResourceBalanceRefreshStatus.fromJson(
        json['status'] as String,
      ),
    );
  }

  /// The time at which the last refresh attempt was initiated. Measured in seconds since the Unix epoch.
  final int lastAttemptedAt;

  /// Time at which the next balance refresh can be initiated. This value will be `null` when `status` is `pending`. Measured in seconds since the Unix epoch.
  final int? nextRefreshAvailableAt;

  /// The status of the last refresh attempt.
  final BankConnectionsResourceBalanceRefreshStatus status;

  Map<String, dynamic> toJson() {
    return {
      'last_attempted_at': lastAttemptedAt,
      'next_refresh_available_at': ?nextRefreshAvailableAt,
      'status': status.toJson(),
    };
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('last_attempted_at') &&
        json['last_attempted_at'] is num &&
        json.containsKey('status');
  }

  BankConnectionsResourceBalanceRefresh copyWith({
    int? lastAttemptedAt,
    int? Function()? nextRefreshAvailableAt,
    BankConnectionsResourceBalanceRefreshStatus? status,
  }) {
    return BankConnectionsResourceBalanceRefresh(
      lastAttemptedAt: lastAttemptedAt ?? this.lastAttemptedAt,
      nextRefreshAvailableAt: nextRefreshAvailableAt != null
          ? nextRefreshAvailableAt()
          : this.nextRefreshAvailableAt,
      status: status ?? this.status,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is BankConnectionsResourceBalanceRefresh &&
            lastAttemptedAt == other.lastAttemptedAt &&
            nextRefreshAvailableAt == other.nextRefreshAvailableAt &&
            status == other.status;
  }

  @override
  int get hashCode {
    return Object.hash(lastAttemptedAt, nextRefreshAvailableAt, status);
  }

  @override
  String toString() {
    return 'BankConnectionsResourceBalanceRefresh(lastAttemptedAt: $lastAttemptedAt, nextRefreshAvailableAt: $nextRefreshAvailableAt, status: $status)';
  }
}
