//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'customer.dart';

/// The ID of the customer the transaction belongs to.
final class CustomerBalanceTransactionCustomer {
  const CustomerBalanceTransactionCustomer({this.string, this.customer});

  factory CustomerBalanceTransactionCustomer.fromJson(Object? json) {
    final map = json is Map<String, dynamic> ? json : null;
    return CustomerBalanceTransactionCustomer(
      string: json is String ? json : null,
      customer: map != null && Customer.canParse(map)
          ? Customer.fromJson(map)
          : null,
    );
  }

  final String? string;

  final Customer? customer;

  /// At least one variant must be present.
  bool get isValid {
    return string != null || customer != null;
  }

  Map<String, dynamic> toJson() {
    return {'string': ?string, ...?customer?.toJson()};
  }
}
