//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
final class GetIssuingTransactionsResponseObject {
  const GetIssuingTransactionsResponseObject._(this.value);

  factory GetIssuingTransactionsResponseObject.fromJson(String json) {
    return switch (json) {
      'list' => list,
      _ => GetIssuingTransactionsResponseObject._(json),
    };
  }

  static const GetIssuingTransactionsResponseObject list =
      GetIssuingTransactionsResponseObject._('list');

  static const List<GetIssuingTransactionsResponseObject> values = [list];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is GetIssuingTransactionsResponseObject && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'GetIssuingTransactionsResponseObject($value)';
  }
}
