//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject929 {
  const InlineObject929._(this.value);

  factory InlineObject929.fromJson(String json) {
    return switch (json) {
      '' => $empty,
      _ => InlineObject929._(json),
    };
  }

  static const InlineObject929 $empty = InlineObject929._('');

  static const List<InlineObject929> values = [$empty];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject929 && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject929($value)';
  }
}
