//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject307FinancialConnectionsPermissions {
  const InlineObject307FinancialConnectionsPermissions._(this.value);

  factory InlineObject307FinancialConnectionsPermissions.fromJson(String json) {
    return switch (json) {
      'balances' => balances,
      'ownership' => ownership,
      'payment_method' => paymentMethod,
      'transactions' => transactions,
      _ => InlineObject307FinancialConnectionsPermissions._(json),
    };
  }

  static const InlineObject307FinancialConnectionsPermissions balances =
      InlineObject307FinancialConnectionsPermissions._('balances');

  static const InlineObject307FinancialConnectionsPermissions ownership =
      InlineObject307FinancialConnectionsPermissions._('ownership');

  static const InlineObject307FinancialConnectionsPermissions paymentMethod =
      InlineObject307FinancialConnectionsPermissions._('payment_method');

  static const InlineObject307FinancialConnectionsPermissions transactions =
      InlineObject307FinancialConnectionsPermissions._('transactions');

  static const List<InlineObject307FinancialConnectionsPermissions> values = [
    balances,
    ownership,
    paymentMethod,
    transactions,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject307FinancialConnectionsPermissions &&
            other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject307FinancialConnectionsPermissions($value)';
  }
}
