//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject1295CustomerAcceptanceType {const InlineObject1295CustomerAcceptanceType._(this.value);

factory InlineObject1295CustomerAcceptanceType.fromJson(String json) { return switch (json) {
  'offline' => offline,
  'online' => online,
  _ => InlineObject1295CustomerAcceptanceType._(json),
}; }

static const InlineObject1295CustomerAcceptanceType offline = InlineObject1295CustomerAcceptanceType._('offline');

static const InlineObject1295CustomerAcceptanceType online = InlineObject1295CustomerAcceptanceType._('online');

static const List<InlineObject1295CustomerAcceptanceType> values = [offline, online];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject1295CustomerAcceptanceType && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject1295CustomerAcceptanceType($value)'; } 
 }
