//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject577 {const InlineObject577._(this.value);

factory InlineObject577.fromJson(String json) { return switch (json) {
  '' => $empty,
  _ => InlineObject577._(json),
}; }

static const InlineObject577 $empty = InlineObject577._('');

static const List<InlineObject577> values = [$empty];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject577 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject577($value)'; } 
 }
