//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject1063MandateOptionsPaymentSchedule {const InlineObject1063MandateOptionsPaymentSchedule._(this.value);

factory InlineObject1063MandateOptionsPaymentSchedule.fromJson(String json) { return switch (json) {
  '' => $empty,
  'adhoc' => adhoc,
  'annual' => annual,
  'daily' => daily,
  'fortnightly' => fortnightly,
  'monthly' => monthly,
  'quarterly' => quarterly,
  'semi_annual' => semiAnnual,
  'weekly' => weekly,
  _ => InlineObject1063MandateOptionsPaymentSchedule._(json),
}; }

static const InlineObject1063MandateOptionsPaymentSchedule $empty = InlineObject1063MandateOptionsPaymentSchedule._('');

static const InlineObject1063MandateOptionsPaymentSchedule adhoc = InlineObject1063MandateOptionsPaymentSchedule._('adhoc');

static const InlineObject1063MandateOptionsPaymentSchedule annual = InlineObject1063MandateOptionsPaymentSchedule._('annual');

static const InlineObject1063MandateOptionsPaymentSchedule daily = InlineObject1063MandateOptionsPaymentSchedule._('daily');

static const InlineObject1063MandateOptionsPaymentSchedule fortnightly = InlineObject1063MandateOptionsPaymentSchedule._('fortnightly');

static const InlineObject1063MandateOptionsPaymentSchedule monthly = InlineObject1063MandateOptionsPaymentSchedule._('monthly');

static const InlineObject1063MandateOptionsPaymentSchedule quarterly = InlineObject1063MandateOptionsPaymentSchedule._('quarterly');

static const InlineObject1063MandateOptionsPaymentSchedule semiAnnual = InlineObject1063MandateOptionsPaymentSchedule._('semi_annual');

static const InlineObject1063MandateOptionsPaymentSchedule weekly = InlineObject1063MandateOptionsPaymentSchedule._('weekly');

static const List<InlineObject1063MandateOptionsPaymentSchedule> values = [$empty, adhoc, annual, daily, fortnightly, monthly, quarterly, semiAnnual, weekly];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject1063MandateOptionsPaymentSchedule && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject1063MandateOptionsPaymentSchedule($value)'; } 
 }
