//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject997SetupFutureUsage {const InlineObject997SetupFutureUsage._(this.value);

factory InlineObject997SetupFutureUsage.fromJson(String json) { return switch (json) {
  '' => $empty,
  'none' => none,
  'off_session' => offSession,
  'on_session' => onSession,
  _ => InlineObject997SetupFutureUsage._(json),
}; }

static const InlineObject997SetupFutureUsage $empty = InlineObject997SetupFutureUsage._('');

static const InlineObject997SetupFutureUsage none = InlineObject997SetupFutureUsage._('none');

static const InlineObject997SetupFutureUsage offSession = InlineObject997SetupFutureUsage._('off_session');

static const InlineObject997SetupFutureUsage onSession = InlineObject997SetupFutureUsage._('on_session');

static const List<InlineObject997SetupFutureUsage> values = [$empty, none, offSession, onSession];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject997SetupFutureUsage && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject997SetupFutureUsage($value)'; } 
 }
