//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject1027OnDemandPurchaseInterval {
  const InlineObject1027OnDemandPurchaseInterval._(this.value);

  factory InlineObject1027OnDemandPurchaseInterval.fromJson(String json) {
    return switch (json) {
      'day' => day,
      'month' => month,
      'week' => week,
      'year' => year,
      _ => InlineObject1027OnDemandPurchaseInterval._(json),
    };
  }

  static const InlineObject1027OnDemandPurchaseInterval day =
      InlineObject1027OnDemandPurchaseInterval._('day');

  static const InlineObject1027OnDemandPurchaseInterval month =
      InlineObject1027OnDemandPurchaseInterval._('month');

  static const InlineObject1027OnDemandPurchaseInterval week =
      InlineObject1027OnDemandPurchaseInterval._('week');

  static const InlineObject1027OnDemandPurchaseInterval year =
      InlineObject1027OnDemandPurchaseInterval._('year');

  static const List<InlineObject1027OnDemandPurchaseInterval> values = [
    day,
    month,
    week,
    year,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject1027OnDemandPurchaseInterval &&
            other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject1027OnDemandPurchaseInterval($value)';
  }
}
