//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class InlineObject317VisaCompliance {const InlineObject317VisaCompliance({this.feeAcknowledged});

factory InlineObject317VisaCompliance.fromJson(Map<String, dynamic> json) { return InlineObject317VisaCompliance(
  feeAcknowledged: json['fee_acknowledged'] as bool?,
); }

final bool? feeAcknowledged;

Map<String, dynamic> toJson() { return {
  'fee_acknowledged': ?feeAcknowledged,
}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
InlineObject317VisaCompliance copyWith({bool Function()? feeAcknowledged}) { return InlineObject317VisaCompliance(
  feeAcknowledged: feeAcknowledged != null ? feeAcknowledged() : this.feeAcknowledged,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is InlineObject317VisaCompliance &&
          feeAcknowledged == other.feeAcknowledged; } 
@override int get hashCode { return feeAcknowledged.hashCode; } 
@override String toString() { return 'InlineObject317VisaCompliance(feeAcknowledged: $feeAcknowledged)'; } 
 }
