//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'inline_object749.dart';

final class InlineObject748MandateOptionsAmount {
  const InlineObject748MandateOptionsAmount({this.$int, this.inlineObject749});

  factory InlineObject748MandateOptionsAmount.fromJson(Object? json) {
    return InlineObject748MandateOptionsAmount(
      $int: json is num ? json.toInt() : null,
      inlineObject749: json is String ? InlineObject749.fromJson(json) : null,
    );
  }

  final int? $int;

  final InlineObject749? inlineObject749;

  /// At least one variant must be present.
  bool get isValid {
    return $int != null || inlineObject749 != null;
  }

  Map<String, dynamic> toJson() {
    return {
      '$int': ?$int,
      if (inlineObject749 != null) 'inlineObject749': inlineObject749!.toJson(),
    };
  }
}
