//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// Bank account verification method.
final class InvoicePaymentMethodOptionsUsBankAccountVerificationMethod {
  const InvoicePaymentMethodOptionsUsBankAccountVerificationMethod._(
    this.value,
  );

  factory InvoicePaymentMethodOptionsUsBankAccountVerificationMethod.fromJson(
    String json,
  ) {
    return switch (json) {
      'automatic' => automatic,
      'instant' => instant,
      'microdeposits' => microdeposits,
      _ => InvoicePaymentMethodOptionsUsBankAccountVerificationMethod._(json),
    };
  }

  static const InvoicePaymentMethodOptionsUsBankAccountVerificationMethod
  automatic = InvoicePaymentMethodOptionsUsBankAccountVerificationMethod._(
    'automatic',
  );

  static const InvoicePaymentMethodOptionsUsBankAccountVerificationMethod
  instant = InvoicePaymentMethodOptionsUsBankAccountVerificationMethod._(
    'instant',
  );

  static const InvoicePaymentMethodOptionsUsBankAccountVerificationMethod
  microdeposits = InvoicePaymentMethodOptionsUsBankAccountVerificationMethod._(
    'microdeposits',
  );

  static const List<InvoicePaymentMethodOptionsUsBankAccountVerificationMethod>
  values = [automatic, instant, microdeposits];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InvoicePaymentMethodOptionsUsBankAccountVerificationMethod &&
            other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'InvoicePaymentMethodOptionsUsBankAccountVerificationMethod($value)';
  }
}
