//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// The reason why the card was canceled.
final class IssuingCardCancellationReason {
  const IssuingCardCancellationReason._(this.value);

  factory IssuingCardCancellationReason.fromJson(String json) {
    return switch (json) {
      'design_rejected' => designRejected,
      'lost' => lost,
      'stolen' => stolen,
      _ => IssuingCardCancellationReason._(json),
    };
  }

  static const IssuingCardCancellationReason designRejected =
      IssuingCardCancellationReason._('design_rejected');

  static const IssuingCardCancellationReason lost =
      IssuingCardCancellationReason._('lost');

  static const IssuingCardCancellationReason stolen =
      IssuingCardCancellationReason._('stolen');

  static const List<IssuingCardCancellationReason> values = [
    designRejected,
    lost,
    stolen,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is IssuingCardCancellationReason && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'IssuingCardCancellationReason($value)';
  }
}
