//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'issuing_authorization.dart';

/// The `Authorization` object that led to this transaction.
final class IssuingTransactionAuthorization {
  const IssuingTransactionAuthorization({
    this.string,
    this.issuingAuthorization,
  });

  factory IssuingTransactionAuthorization.fromJson(Object? json) {
    final map = json is Map<String, dynamic> ? json : null;
    return IssuingTransactionAuthorization(
      string: json is String ? json : null,
      issuingAuthorization: map != null && IssuingAuthorization.canParse(map)
          ? IssuingAuthorization.fromJson(map)
          : null,
    );
  }

  final String? string;

  final IssuingAuthorization? issuingAuthorization;

  /// At least one variant must be present.
  bool get isValid {
    return string != null || issuingAuthorization != null;
  }

  Map<String, dynamic> toJson() {
    return {'string': ?string, ...?issuingAuthorization?.toJson()};
  }
}
