//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'outbound_transfers_payment_method_details_financial_account_network.dart';

///
final class OutboundTransfersPaymentMethodDetailsFinancialAccount {
  const OutboundTransfersPaymentMethodDetailsFinancialAccount({
    required this.id,
    required this.network,
  });

  factory OutboundTransfersPaymentMethodDetailsFinancialAccount.fromJson(
    Map<String, dynamic> json,
  ) {
    return OutboundTransfersPaymentMethodDetailsFinancialAccount(
      id: json['id'] as String,
      network:
          OutboundTransfersPaymentMethodDetailsFinancialAccountNetwork.fromJson(
            json['network'] as String,
          ),
    );
  }

  /// Token of the FinancialAccount.
  final String id;

  /// The rails used to send funds.
  final OutboundTransfersPaymentMethodDetailsFinancialAccountNetwork network;

  Map<String, dynamic> toJson() {
    return {'id': id, 'network': network.toJson()};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('id') &&
        json['id'] is String &&
        json.containsKey('network');
  }

  OutboundTransfersPaymentMethodDetailsFinancialAccount copyWith({
    String? id,
    OutboundTransfersPaymentMethodDetailsFinancialAccountNetwork? network,
  }) {
    return OutboundTransfersPaymentMethodDetailsFinancialAccount(
      id: id ?? this.id,
      network: network ?? this.network,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is OutboundTransfersPaymentMethodDetailsFinancialAccount &&
            id == other.id &&
            network == other.network;
  }

  @override
  int get hashCode {
    return Object.hash(id, network);
  }

  @override
  String toString() {
    return 'OutboundTransfersPaymentMethodDetailsFinancialAccount(id: $id, network: $network)';
  }
}
