//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'payment_intent_payment_method_options_blik.dart';
import 'payment_intent_type_specific_payment_method_options_client.dart';

final class PaymentIntentPaymentMethodOptionsBlik2 {
  const PaymentIntentPaymentMethodOptionsBlik2({
    this.paymentIntentPaymentMethodOptionsBlik,
    this.paymentIntentTypeSpecificPaymentMethodOptionsClient,
  });

  factory PaymentIntentPaymentMethodOptionsBlik2.fromJson(
    Map<String, dynamic> json,
  ) {
    return PaymentIntentPaymentMethodOptionsBlik2(
      paymentIntentPaymentMethodOptionsBlik:
          PaymentIntentPaymentMethodOptionsBlik.canParse(json)
          ? PaymentIntentPaymentMethodOptionsBlik.fromJson(json)
          : null,
      paymentIntentTypeSpecificPaymentMethodOptionsClient:
          PaymentIntentTypeSpecificPaymentMethodOptionsClient.canParse(json)
          ? PaymentIntentTypeSpecificPaymentMethodOptionsClient.fromJson(json)
          : null,
    );
  }

  final PaymentIntentPaymentMethodOptionsBlik?
  paymentIntentPaymentMethodOptionsBlik;

  final PaymentIntentTypeSpecificPaymentMethodOptionsClient?
  paymentIntentTypeSpecificPaymentMethodOptionsClient;

  /// At least one variant must be present.
  bool get isValid {
    return paymentIntentPaymentMethodOptionsBlik != null ||
        paymentIntentTypeSpecificPaymentMethodOptionsClient != null;
  }

  Map<String, dynamic> toJson() {
    return {
      ...?paymentIntentPaymentMethodOptionsBlik?.toJson(),
      ...?paymentIntentTypeSpecificPaymentMethodOptionsClient?.toJson(),
    };
  }
}
