//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// The processor used for this payment attempt.
final class PaymentsPrimitivesPaymentRecordsResourceProcessorDetailsType {
  const PaymentsPrimitivesPaymentRecordsResourceProcessorDetailsType._(
    this.value,
  );

  factory PaymentsPrimitivesPaymentRecordsResourceProcessorDetailsType.fromJson(
    String json,
  ) {
    return switch (json) {
      'custom' => custom,
      _ => PaymentsPrimitivesPaymentRecordsResourceProcessorDetailsType._(json),
    };
  }

  static const PaymentsPrimitivesPaymentRecordsResourceProcessorDetailsType
  custom = PaymentsPrimitivesPaymentRecordsResourceProcessorDetailsType._(
    'custom',
  );

  static const List<
    PaymentsPrimitivesPaymentRecordsResourceProcessorDetailsType
  >
  values = [custom];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is PaymentsPrimitivesPaymentRecordsResourceProcessorDetailsType &&
            other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'PaymentsPrimitivesPaymentRecordsResourceProcessorDetailsType($value)';
  }
}
