//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// Can be `bank_account` or `card`.
final class PayoutType {
  const PayoutType._(this.value);

  factory PayoutType.fromJson(String json) {
    return switch (json) {
      'bank_account' => bankAccount,
      'card' => card,
      _ => PayoutType._(json),
    };
  }

  static const PayoutType bankAccount = PayoutType._('bank_account');

  static const PayoutType card = PayoutType._('card');

  static const List<PayoutType> values = [bankAccount, card];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is PayoutType && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'PayoutType($value)';
  }
}
