//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'post_promotion_codes_request_promotion_type.dart';

/// The promotion referenced by this promotion code.
final class PostPromotionCodesRequestPromotion {
  const PostPromotionCodesRequestPromotion({this.coupon, required this.type});

  factory PostPromotionCodesRequestPromotion.fromJson(
    Map<String, dynamic> json,
  ) {
    return PostPromotionCodesRequestPromotion(
      coupon: json['coupon'] as String?,
      type: PostPromotionCodesRequestPromotionType.fromJson(
        json['type'] as String,
      ),
    );
  }

  final String? coupon;

  final PostPromotionCodesRequestPromotionType type;

  Map<String, dynamic> toJson() {
    return {'coupon': ?coupon, 'type': type.toJson()};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('type');
  }

  PostPromotionCodesRequestPromotion copyWith({
    String Function()? coupon,
    PostPromotionCodesRequestPromotionType? type,
  }) {
    return PostPromotionCodesRequestPromotion(
      coupon: coupon != null ? coupon() : this.coupon,
      type: type ?? this.type,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is PostPromotionCodesRequestPromotion &&
            coupon == other.coupon &&
            type == other.type;
  }

  @override
  int get hashCode {
    return Object.hash(coupon, type);
  }

  @override
  String toString() {
    return 'PostPromotionCodesRequestPromotion(coupon: $coupon, type: $type)';
  }
}
