//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'post_checkout_sessions_request_shipping_options_shipping_rate_data_delivery_estimate_maximum_unit.dart';final class PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximum {const PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximum({required this.unit, required this.value, });

factory PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximum.fromJson(Map<String, dynamic> json) { return PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximum(
  unit: PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximumUnit.fromJson(json['unit'] as String),
  value: (json['value'] as num).toInt(),
); }

final PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximumUnit unit;

final int value;

Map<String, dynamic> toJson() { return {
  'unit': unit.toJson(),
  'value': value,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('unit') &&
      json.containsKey('value') && json['value'] is num; } 
PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximum copyWith({PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximumUnit? unit, int? value, }) { return PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximum(
  unit: unit ?? this.unit,
  value: value ?? this.value,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximum &&
          unit == other.unit &&
          value == other.value; } 
@override int get hashCode { return Object.hash(unit, value); } 
@override String toString() { return 'PostCheckoutSessionsRequestShippingOptionsShippingRateDataDeliveryEstimateMaximum(unit: $unit, value: $value)'; } 
 }
