//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class PostPaymentIntentsIntentRequestPaymentMethodDataCrypto {const PostPaymentIntentsIntentRequestPaymentMethodDataCrypto();

factory PostPaymentIntentsIntentRequestPaymentMethodDataCrypto.fromJson(Map<String, dynamic> json) { return PostPaymentIntentsIntentRequestPaymentMethodDataCrypto(

); }

Map<String, dynamic> toJson() { return {

}; } 
static bool canParse(Map<String, dynamic> json) { return true; } 
PostPaymentIntentsIntentRequestPaymentMethodDataCrypto copyWith() { return PostPaymentIntentsIntentRequestPaymentMethodDataCrypto(

); } 
@override bool operator ==(Object other) { return identical(this, other) || other is PostPaymentIntentsIntentRequestPaymentMethodDataCrypto; } 
@override int get hashCode { return runtimeType.hashCode; } 
@override String toString() { return 'PostPaymentIntentsIntentRequestPaymentMethodDataCrypto()'; } 
 }
