//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class PostFinancialConnectionsSessionsRequestPermissions {
  const PostFinancialConnectionsSessionsRequestPermissions._(this.value);

  factory PostFinancialConnectionsSessionsRequestPermissions.fromJson(
    String json,
  ) {
    return switch (json) {
      'balances' => balances,
      'ownership' => ownership,
      'payment_method' => paymentMethod,
      'transactions' => transactions,
      _ => PostFinancialConnectionsSessionsRequestPermissions._(json),
    };
  }

  static const PostFinancialConnectionsSessionsRequestPermissions balances =
      PostFinancialConnectionsSessionsRequestPermissions._('balances');

  static const PostFinancialConnectionsSessionsRequestPermissions ownership =
      PostFinancialConnectionsSessionsRequestPermissions._('ownership');

  static const PostFinancialConnectionsSessionsRequestPermissions
  paymentMethod = PostFinancialConnectionsSessionsRequestPermissions._(
    'payment_method',
  );

  static const PostFinancialConnectionsSessionsRequestPermissions transactions =
      PostFinancialConnectionsSessionsRequestPermissions._('transactions');

  static const List<PostFinancialConnectionsSessionsRequestPermissions> values =
      [balances, ownership, paymentMethod, transactions];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is PostFinancialConnectionsSessionsRequestPermissions &&
            other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'PostFinancialConnectionsSessionsRequestPermissions($value)';
  }
}
