//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'post_setup_intents_intent_request_payment_method_data_sofort_country.dart';

final class PostSetupIntentsIntentRequestPaymentMethodDataSofort {
  const PostSetupIntentsIntentRequestPaymentMethodDataSofort({
    required this.country,
  });

  factory PostSetupIntentsIntentRequestPaymentMethodDataSofort.fromJson(
    Map<String, dynamic> json,
  ) {
    return PostSetupIntentsIntentRequestPaymentMethodDataSofort(
      country:
          PostSetupIntentsIntentRequestPaymentMethodDataSofortCountry.fromJson(
            json['country'] as String,
          ),
    );
  }

  final PostSetupIntentsIntentRequestPaymentMethodDataSofortCountry country;

  Map<String, dynamic> toJson() {
    return {'country': country.toJson()};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('country');
  }

  PostSetupIntentsIntentRequestPaymentMethodDataSofort copyWith({
    PostSetupIntentsIntentRequestPaymentMethodDataSofortCountry? country,
  }) {
    return PostSetupIntentsIntentRequestPaymentMethodDataSofort(
      country: country ?? this.country,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is PostSetupIntentsIntentRequestPaymentMethodDataSofort &&
            country == other.country;
  }

  @override
  int get hashCode {
    return country.hashCode;
  }

  @override
  String toString() {
    return 'PostSetupIntentsIntentRequestPaymentMethodDataSofort(country: $country)';
  }
}
