//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

/// Specifies whether to cancel a single event or a range of events for a time period. Time period cancellation is not supported yet.
final class PostBillingMeterEventAdjustmentsRequestType {
  const PostBillingMeterEventAdjustmentsRequestType._(this.value);

  factory PostBillingMeterEventAdjustmentsRequestType.fromJson(String json) {
    return switch (json) {
      'cancel' => cancel,
      _ => PostBillingMeterEventAdjustmentsRequestType._(json),
    };
  }

  static const PostBillingMeterEventAdjustmentsRequestType cancel =
      PostBillingMeterEventAdjustmentsRequestType._('cancel');

  static const List<PostBillingMeterEventAdjustmentsRequestType> values = [
    cancel,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is PostBillingMeterEventAdjustmentsRequestType &&
            other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'PostBillingMeterEventAdjustmentsRequestType($value)';
  }
}
