//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

final class PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes {const PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes._(this.value);

factory PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes.fromJson(String json) { return switch (json) {
  'iban' => iban,
  'sort_code' => sortCode,
  'spei' => spei,
  'zengin' => zengin,
  _ => PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes._(json),
}; }

static const PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes iban = PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes._('iban');

static const PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes sortCode = PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes._('sort_code');

static const PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes spei = PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes._('spei');

static const PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes zengin = PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes._('zengin');

static const List<PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes> values = [iban, sortCode, spei, zengin];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'PostCustomersCustomerFundingInstructionsRequestBankTransferRequestedAddressTypes($value)'; } 
 }
