//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'inline_object1461.dart';
import 'inline_object1462.dart';

/// Specifies an interval for how often to bill for any pending invoice items. It is analogous to calling [Create an invoice](https://docs.stripe.com/api#create_invoice) for the given subscription at the specified interval.
final class PostSubscriptionsSubscriptionExposedIdRequestPendingInvoiceItemInterval {
  const PostSubscriptionsSubscriptionExposedIdRequestPendingInvoiceItemInterval({
    this.inlineObject1461,
    this.inlineObject1462,
  });

  factory PostSubscriptionsSubscriptionExposedIdRequestPendingInvoiceItemInterval.fromJson(
    Object? json,
  ) {
    final map = json is Map<String, dynamic> ? json : null;
    return PostSubscriptionsSubscriptionExposedIdRequestPendingInvoiceItemInterval(
      inlineObject1461: map != null && InlineObject1461.canParse(map)
          ? InlineObject1461.fromJson(map)
          : null,
      inlineObject1462: json is String ? InlineObject1462.fromJson(json) : null,
    );
  }

  final InlineObject1461? inlineObject1461;

  final InlineObject1462? inlineObject1462;

  /// At least one variant must be present.
  bool get isValid {
    return inlineObject1461 != null || inlineObject1462 != null;
  }

  Map<String, dynamic> toJson() {
    return {
      ...?inlineObject1461?.toJson(),
      if (inlineObject1462 != null)
        'inlineObject1462': inlineObject1462!.toJson(),
    };
  }
}
