//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'inline_object290.dart';

/// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
final class PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestMetadata {
  const PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestMetadata({
    this.mapStringString,
    this.inlineObject290,
  });

  factory PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestMetadata.fromJson(
    Object? json,
  ) {
    return PostCustomersCustomerSubscriptionsSubscriptionExposedIdRequestMetadata(
      // mapStringString: skipped (collection type in anyOf not supported)
      inlineObject290: json is String ? InlineObject290.fromJson(json) : null,
    );
  }

  final Map<String, String>? mapStringString;

  final InlineObject290? inlineObject290;

  /// At least one variant must be present.
  bool get isValid {
    return mapStringString != null || inlineObject290 != null;
  }

  Map<String, dynamic> toJson() {
    return {
      'mapStringString': ?mapStringString,
      if (inlineObject290 != null) 'inlineObject290': inlineObject290!.toJson(),
    };
  }
}
