//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'inline_object1232.dart';import 'inline_object1233.dart';/// The data with which to automatically create a Transfer for each of the invoices.
final class PostQuotesRequestTransferData {const PostQuotesRequestTransferData({this.inlineObject1232, this.inlineObject1233, });

factory PostQuotesRequestTransferData.fromJson(Object? json) { final map = json is Map<String, dynamic> ? json : null;
return PostQuotesRequestTransferData(
  inlineObject1232: map != null && InlineObject1232.canParse(map) ? InlineObject1232.fromJson(map) : null,
  inlineObject1233: json is String ? InlineObject1233.fromJson(json) : null,
); }

final InlineObject1232? inlineObject1232;

final InlineObject1233? inlineObject1233;

/// At least one variant must be present.
bool get isValid { return inlineObject1232 != null || inlineObject1233 != null; } 
Map<String, dynamic> toJson() { return {
  ...?inlineObject1232?.toJson(),
  if (inlineObject1233 != null) 'inlineObject1233': inlineObject1233!.toJson(),
}; } 
 }
