//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from stripe-spec3.yaml
//  OpenAPI spec version: 3.0.0

import 'deleted_terminal_reader.dart';
import 'terminal_reader.dart';

final class PostTerminalReadersReaderResponse {
  const PostTerminalReadersReaderResponse({
    this.terminalReader,
    this.deletedTerminalReader,
  });

  factory PostTerminalReadersReaderResponse.fromJson(
    Map<String, dynamic> json,
  ) {
    return PostTerminalReadersReaderResponse(
      terminalReader: TerminalReader.canParse(json)
          ? TerminalReader.fromJson(json)
          : null,
      deletedTerminalReader: DeletedTerminalReader.canParse(json)
          ? DeletedTerminalReader.fromJson(json)
          : null,
    );
  }

  final TerminalReader? terminalReader;

  final DeletedTerminalReader? deletedTerminalReader;

  /// At least one variant must be present.
  bool get isValid {
    return terminalReader != null || deletedTerminalReader != null;
  }

  Map<String, dynamic> toJson() {
    return {...?terminalReader?.toJson(), ...?deletedTerminalReader?.toJson()};
  }
}
