name: pub_github_rest_3_1
description: Generated API client.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.18.0
  degenerate_runtime:
    path: ../../../packages/degenerate_runtime
