//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class DeleteEventDeleteResponse400Errors {
  const DeleteEventDeleteResponse400Errors({required this.message});

  factory DeleteEventDeleteResponse400Errors.fromJson(
    Map<String, dynamic> json,
  ) {
    return DeleteEventDeleteResponse400Errors(
      message: json['message'] as String,
    );
  }

  final String message;

  Map<String, dynamic> toJson() {
    return {'message': message};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('message') && json['message'] is String;
  }

  DeleteEventDeleteResponse400Errors copyWith({String? message}) {
    return DeleteEventDeleteResponse400Errors(message: message ?? this.message);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is DeleteEventDeleteResponse400Errors && message == other.message;
  }

  @override
  int get hashCode {
    return message.hashCode;
  }

  @override
  String toString() {
    return 'DeleteEventDeleteResponse400Errors(message: $message)';
  }
}
