//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'destination_list_response500_errors_message.dart';

final class DestinationListResponse500Errors {
  const DestinationListResponse500Errors({this.detail, required this.message});

  factory DestinationListResponse500Errors.fromJson(Map<String, dynamic> json) {
    return DestinationListResponse500Errors(
      detail: json['detail'] as String?,
      message: DestinationListResponse500ErrorsMessage.fromJson(
        json['message'] as String,
      ),
    );
  }

  final String? detail;

  final DestinationListResponse500ErrorsMessage message;

  Map<String, dynamic> toJson() {
    return {'detail': ?detail, 'message': message.toJson()};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('message');
  }

  DestinationListResponse500Errors copyWith({
    String Function()? detail,
    DestinationListResponse500ErrorsMessage? message,
  }) {
    return DestinationListResponse500Errors(
      detail: detail != null ? detail() : this.detail,
      message: message ?? this.message,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is DestinationListResponse500Errors &&
            detail == other.detail &&
            message == other.message;
  }

  @override
  int get hashCode {
    return Object.hash(detail, message);
  }

  @override
  String toString() {
    return 'DestinationListResponse500Errors(detail: $detail, message: $message)';
  }
}
