//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'destination_create_response401_errors_message.dart';

final class DestinationCreateResponse401Errors {
  const DestinationCreateResponse401Errors({
    this.detail,
    required this.message,
  });

  factory DestinationCreateResponse401Errors.fromJson(
    Map<String, dynamic> json,
  ) {
    return DestinationCreateResponse401Errors(
      detail: json['detail'] as String?,
      message: DestinationCreateResponse401ErrorsMessage.fromJson(
        json['message'] as String,
      ),
    );
  }

  final String? detail;

  final DestinationCreateResponse401ErrorsMessage message;

  Map<String, dynamic> toJson() {
    return {'detail': ?detail, 'message': message.toJson()};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('message');
  }

  DestinationCreateResponse401Errors copyWith({
    String Function()? detail,
    DestinationCreateResponse401ErrorsMessage? message,
  }) {
    return DestinationCreateResponse401Errors(
      detail: detail != null ? detail() : this.detail,
      message: message ?? this.message,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is DestinationCreateResponse401Errors &&
            detail == other.detail &&
            message == other.message;
  }

  @override
  int get hashCode {
    return Object.hash(detail, message);
  }

  @override
  String toString() {
    return 'DestinationCreateResponse401Errors(detail: $detail, message: $message)';
  }
}
