//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object559.dart';
import 'inline_object560.dart';

/// A value that is one of: `String`, `List<InlineObject559>`, `InlineObject560`.
sealed class InlineObject558MessagesContent {
  const InlineObject558MessagesContent();

  factory InlineObject558MessagesContent.fromJson(Map<String, dynamic> json) {
    if (InlineObject560.canParse(json)) {
      return InlineObject558MessagesContentInlineObject560(
        InlineObject560.fromJson(json),
      );
    }
    return InlineObject558MessagesContent$Unknown(json);
  }

  /// The underlying raw value.
  Object? get value;
  Object? toJson() {
    return value;
  }
}

final class InlineObject558MessagesContentString
    extends InlineObject558MessagesContent {
  const InlineObject558MessagesContentString(this._value);

  final String _value;

  @override
  String get value {
    return _value;
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject558MessagesContentString && _value == other._value;
  }

  @override
  int get hashCode {
    return _value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject558MessagesContent.string($_value)';
  }
}

final class InlineObject558MessagesContentListInlineObject559
    extends InlineObject558MessagesContent {
  const InlineObject558MessagesContentListInlineObject559(this._value);

  final List<InlineObject559> _value;

  @override
  List<InlineObject559> get value {
    return _value;
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject558MessagesContentListInlineObject559 &&
            _value == other._value;
  }

  @override
  int get hashCode {
    return _value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject558MessagesContent.list<InlineObject559>($_value)';
  }
}

final class InlineObject558MessagesContentInlineObject560
    extends InlineObject558MessagesContent {
  const InlineObject558MessagesContentInlineObject560(this._value);

  final InlineObject560 _value;

  @override
  InlineObject560 get value {
    return _value;
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject558MessagesContentInlineObject560 &&
            _value == other._value;
  }

  @override
  int get hashCode {
    return _value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject558MessagesContent.inlineObject560($_value)';
  }
}

/// An unknown variant not defined in the OpenAPI spec.
final class InlineObject558MessagesContent$Unknown
    extends InlineObject558MessagesContent {
  const InlineObject558MessagesContent$Unknown(this._value);

  final Object? _value;

  @override
  Object get value {
    return _value ?? '';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject558MessagesContent$Unknown &&
            _value == other._value;
  }

  @override
  int get hashCode {
    return _value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject558MessagesContent.unknown($_value)';
  }
}
