//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object534.dart';
import 'inline_object535.dart';

/// A value that is one of: `String`, `List<InlineObject534>`, `InlineObject535`.
sealed class InlineObject533MessagesContent {
  const InlineObject533MessagesContent();

  factory InlineObject533MessagesContent.fromJson(Map<String, dynamic> json) {
    if (InlineObject535.canParse(json)) {
      return InlineObject533MessagesContentInlineObject535(
        InlineObject535.fromJson(json),
      );
    }
    return InlineObject533MessagesContent$Unknown(json);
  }

  /// The underlying raw value.
  Object? get value;
  Object? toJson() {
    return value;
  }
}

final class InlineObject533MessagesContentString
    extends InlineObject533MessagesContent {
  const InlineObject533MessagesContentString(this._value);

  final String _value;

  @override
  String get value {
    return _value;
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject533MessagesContentString && _value == other._value;
  }

  @override
  int get hashCode {
    return _value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject533MessagesContent.string($_value)';
  }
}

final class InlineObject533MessagesContentListInlineObject534
    extends InlineObject533MessagesContent {
  const InlineObject533MessagesContentListInlineObject534(this._value);

  final List<InlineObject534> _value;

  @override
  List<InlineObject534> get value {
    return _value;
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject533MessagesContentListInlineObject534 &&
            _value == other._value;
  }

  @override
  int get hashCode {
    return _value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject533MessagesContent.list<InlineObject534>($_value)';
  }
}

final class InlineObject533MessagesContentInlineObject535
    extends InlineObject533MessagesContent {
  const InlineObject533MessagesContentInlineObject535(this._value);

  final InlineObject535 _value;

  @override
  InlineObject535 get value {
    return _value;
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject533MessagesContentInlineObject535 &&
            _value == other._value;
  }

  @override
  int get hashCode {
    return _value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject533MessagesContent.inlineObject535($_value)';
  }
}

/// An unknown variant not defined in the OpenAPI spec.
final class InlineObject533MessagesContent$Unknown
    extends InlineObject533MessagesContent {
  const InlineObject533MessagesContent$Unknown(this._value);

  final Object? _value;

  @override
  Object get value {
    return _value ?? '';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject533MessagesContent$Unknown &&
            _value == other._value;
  }

  @override
  int get hashCode {
    return _value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject533MessagesContent.unknown($_value)';
  }
}
