//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class InlineObject1095 {
  const InlineObject1095._(this.value);

  factory InlineObject1095.fromJson(String json) {
    return switch (json) {
      'media' => media,
      _ => InlineObject1095._(json),
    };
  }

  static const InlineObject1095 media = InlineObject1095._('media');

  static const List<InlineObject1095> values = [media];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject1095 && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject1095($value)';
  }
}
