//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object414_messages_content.dart';final class InlineObject414Messages {const InlineObject414Messages({required this.content, required this.role, });

factory InlineObject414Messages.fromJson(Map<String, dynamic> json) { return InlineObject414Messages(
  content: InlineObject414MessagesContent.fromJson(json['content']),
  role: json['role'] as String,
); }

final InlineObject414MessagesContent content;

/// The role of the message sender (e.g., 'user', 'assistant', 'system', 'tool').
final String role;

Map<String, dynamic> toJson() { return {
  'content': content.toJson(),
  'role': role,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('content') &&
      json.containsKey('role') && json['role'] is String; } 
InlineObject414Messages copyWith({InlineObject414MessagesContent? content, String? role, }) { return InlineObject414Messages(
  content: content ?? this.content,
  role: role ?? this.role,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is InlineObject414Messages &&
          content == other.content &&
          role == other.role; } 
@override int get hashCode { return Object.hash(content, role); } 
@override String toString() { return 'InlineObject414Messages(content: $content, role: $role)'; } 
 }
