//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'package:collection/collection.dart';
import 'inline_object385_requests.dart';

final class InlineObject385 {
  const InlineObject385({required this.requests});

  factory InlineObject385.fromJson(Map<String, dynamic> json) {
    return InlineObject385(
      requests: (json['requests'] as List<dynamic>)
          .map(
            (e) => InlineObject385Requests.fromJson(e as Map<String, dynamic>),
          )
          .toList(),
    );
  }

  /// Batch of the embeddings requests to run using async-queue
  final List<InlineObject385Requests> requests;

  Map<String, dynamic> toJson() {
    return {'requests': requests.map((e) => e.toJson()).toList()};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('requests');
  }

  InlineObject385 copyWith({List<InlineObject385Requests>? requests}) {
    return InlineObject385(requests: requests ?? this.requests);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject385 &&
            const ListEquality<dynamic>().equals(requests, other.requests);
  }

  @override
  int get hashCode {
    return Object.hashAll(requests).hashCode;
  }

  @override
  String toString() {
    return 'InlineObject385(requests: $requests)';
  }
}
