//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class InlineObject264OutputsFallback {
  const InlineObject264OutputsFallback({required this.elementId});

  factory InlineObject264OutputsFallback.fromJson(Map<String, dynamic> json) {
    return InlineObject264OutputsFallback(
      elementId: json['elementId'] as String,
    );
  }

  final String elementId;

  Map<String, dynamic> toJson() {
    return {'elementId': elementId};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('elementId') && json['elementId'] is String;
  }

  InlineObject264OutputsFallback copyWith({String? elementId}) {
    return InlineObject264OutputsFallback(
      elementId: elementId ?? this.elementId,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject264OutputsFallback && elementId == other.elementId;
  }

  @override
  int get hashCode {
    return elementId.hashCode;
  }

  @override
  String toString() {
    return 'InlineObject264OutputsFallback(elementId: $elementId)';
  }
}
