//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class InlineObject1076 {const InlineObject1076._(this.value);

factory InlineObject1076.fromJson(String json) { return switch (json) {
  'High' => high,
  _ => InlineObject1076._(json),
}; }

static const InlineObject1076 high = InlineObject1076._('High');

static const List<InlineObject1076> values = [high];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is InlineObject1076 && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'InlineObject1076($value)'; } 
 }
