//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object824_response_format_type.dart';

final class InlineObject824ResponseFormat {
  const InlineObject824ResponseFormat({this.jsonSchema, this.type});

  factory InlineObject824ResponseFormat.fromJson(Map<String, dynamic> json) {
    return InlineObject824ResponseFormat(
      jsonSchema: json['json_schema'] as String?,
      type: json['type'] != null
          ? InlineObject824ResponseFormatType.fromJson(json['type'] as String)
          : null,
    );
  }

  final String? jsonSchema;

  final InlineObject824ResponseFormatType? type;

  Map<String, dynamic> toJson() {
    return {
      'json_schema': ?jsonSchema,
      if (type != null) 'type': type?.toJson(),
    };
  }

  static bool canParse(Map<String, dynamic> json) {
    return true;
  }

  InlineObject824ResponseFormat copyWith({
    String Function()? jsonSchema,
    InlineObject824ResponseFormatType Function()? type,
  }) {
    return InlineObject824ResponseFormat(
      jsonSchema: jsonSchema != null ? jsonSchema() : this.jsonSchema,
      type: type != null ? type() : this.type,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is InlineObject824ResponseFormat &&
            jsonSchema == other.jsonSchema &&
            type == other.type;
  }

  @override
  int get hashCode {
    return Object.hash(jsonSchema, type);
  }

  @override
  String toString() {
    return 'InlineObject824ResponseFormat(jsonSchema: $jsonSchema, type: $type)';
  }
}
