//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object926.dart';import 'inline_object927.dart';import 'inline_object928.dart';import 'inline_object929.dart';import 'inline_object930.dart';import 'inline_object931.dart';import 'inline_object932.dart';import 'inline_object933.dart';import 'inline_object934.dart';import 'inline_object935.dart';import 'inline_object936.dart';import 'inline_object937.dart';import 'inline_object938.dart';import 'inline_object939.dart';import 'inline_object940.dart';import 'inline_object941.dart';import 'inline_object942.dart';import 'inline_object943.dart';final class InlineObject889RejectResourceTypes {const InlineObject889RejectResourceTypes({this.inlineObject926, this.inlineObject927, this.inlineObject928, this.inlineObject929, this.inlineObject930, this.inlineObject931, this.inlineObject932, this.inlineObject933, this.inlineObject934, this.inlineObject935, this.inlineObject936, this.inlineObject937, this.inlineObject938, this.inlineObject939, this.inlineObject940, this.inlineObject941, this.inlineObject942, this.inlineObject943, });

factory InlineObject889RejectResourceTypes.fromJson(Object? json) { return InlineObject889RejectResourceTypes(
  inlineObject926: json is String ? InlineObject926.fromJson(json) : null,
  inlineObject927: json is String ? InlineObject927.fromJson(json) : null,
  inlineObject928: json is String ? InlineObject928.fromJson(json) : null,
  inlineObject929: json is String ? InlineObject929.fromJson(json) : null,
  inlineObject930: json is String ? InlineObject930.fromJson(json) : null,
  inlineObject931: json is String ? InlineObject931.fromJson(json) : null,
  inlineObject932: json is String ? InlineObject932.fromJson(json) : null,
  inlineObject933: json is String ? InlineObject933.fromJson(json) : null,
  inlineObject934: json is String ? InlineObject934.fromJson(json) : null,
  inlineObject935: json is String ? InlineObject935.fromJson(json) : null,
  inlineObject936: json is String ? InlineObject936.fromJson(json) : null,
  inlineObject937: json is String ? InlineObject937.fromJson(json) : null,
  inlineObject938: json is String ? InlineObject938.fromJson(json) : null,
  inlineObject939: json is String ? InlineObject939.fromJson(json) : null,
  inlineObject940: json is String ? InlineObject940.fromJson(json) : null,
  inlineObject941: json is String ? InlineObject941.fromJson(json) : null,
  inlineObject942: json is String ? InlineObject942.fromJson(json) : null,
  inlineObject943: json is String ? InlineObject943.fromJson(json) : null,
); }

final InlineObject926? inlineObject926;

final InlineObject927? inlineObject927;

final InlineObject928? inlineObject928;

final InlineObject929? inlineObject929;

final InlineObject930? inlineObject930;

final InlineObject931? inlineObject931;

final InlineObject932? inlineObject932;

final InlineObject933? inlineObject933;

final InlineObject934? inlineObject934;

final InlineObject935? inlineObject935;

final InlineObject936? inlineObject936;

final InlineObject937? inlineObject937;

final InlineObject938? inlineObject938;

final InlineObject939? inlineObject939;

final InlineObject940? inlineObject940;

final InlineObject941? inlineObject941;

final InlineObject942? inlineObject942;

final InlineObject943? inlineObject943;

/// At least one variant must be present.
bool get isValid { return inlineObject926 != null || inlineObject927 != null || inlineObject928 != null || inlineObject929 != null || inlineObject930 != null || inlineObject931 != null || inlineObject932 != null || inlineObject933 != null || inlineObject934 != null || inlineObject935 != null || inlineObject936 != null || inlineObject937 != null || inlineObject938 != null || inlineObject939 != null || inlineObject940 != null || inlineObject941 != null || inlineObject942 != null || inlineObject943 != null; } 
Map<String, dynamic> toJson() { return {
  if (inlineObject926 != null) 'inlineObject926': inlineObject926!.toJson(),
  if (inlineObject927 != null) 'inlineObject927': inlineObject927!.toJson(),
  if (inlineObject928 != null) 'inlineObject928': inlineObject928!.toJson(),
  if (inlineObject929 != null) 'inlineObject929': inlineObject929!.toJson(),
  if (inlineObject930 != null) 'inlineObject930': inlineObject930!.toJson(),
  if (inlineObject931 != null) 'inlineObject931': inlineObject931!.toJson(),
  if (inlineObject932 != null) 'inlineObject932': inlineObject932!.toJson(),
  if (inlineObject933 != null) 'inlineObject933': inlineObject933!.toJson(),
  if (inlineObject934 != null) 'inlineObject934': inlineObject934!.toJson(),
  if (inlineObject935 != null) 'inlineObject935': inlineObject935!.toJson(),
  if (inlineObject936 != null) 'inlineObject936': inlineObject936!.toJson(),
  if (inlineObject937 != null) 'inlineObject937': inlineObject937!.toJson(),
  if (inlineObject938 != null) 'inlineObject938': inlineObject938!.toJson(),
  if (inlineObject939 != null) 'inlineObject939': inlineObject939!.toJson(),
  if (inlineObject940 != null) 'inlineObject940': inlineObject940!.toJson(),
  if (inlineObject941 != null) 'inlineObject941': inlineObject941!.toJson(),
  if (inlineObject942 != null) 'inlineObject942': inlineObject942!.toJson(),
  if (inlineObject943 != null) 'inlineObject943': inlineObject943!.toJson(),
}; } 
 }
