//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

import 'inline_object1811.dart';

final class OrganizationListOrganizationsParentId {
  const OrganizationListOrganizationsParentId({
    this.string,
    this.inlineObject1811,
  });

  factory OrganizationListOrganizationsParentId.fromJson(Object? json) {
    return OrganizationListOrganizationsParentId(
      string: json is String ? json : null,
      inlineObject1811: json is String ? InlineObject1811.fromJson(json) : null,
    );
  }

  final String? string;

  final InlineObject1811? inlineObject1811;

  /// At least one variant must be present.
  bool get isValid {
    return string != null || inlineObject1811 != null;
  }

  Map<String, dynamic> toJson() {
    return {
      'string': ?string,
      if (inlineObject1811 != null)
        'inlineObject1811': inlineObject1811!.toJson(),
    };
  }
}
