//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// Location of the bucket.
final class R2BucketLocation {const R2BucketLocation._(this.value);

factory R2BucketLocation.fromJson(String json) { return switch (json) {
  'apac' => apac,
  'eeur' => eeur,
  'enam' => enam,
  'weur' => weur,
  'wnam' => wnam,
  'oc' => oc,
  _ => R2BucketLocation._(json),
}; }

static const R2BucketLocation apac = R2BucketLocation._('apac');

static const R2BucketLocation eeur = R2BucketLocation._('eeur');

static const R2BucketLocation enam = R2BucketLocation._('enam');

static const R2BucketLocation weur = R2BucketLocation._('weur');

static const R2BucketLocation wnam = R2BucketLocation._('wnam');

static const R2BucketLocation oc = R2BucketLocation._('oc');

static const List<R2BucketLocation> values = [apac, eeur, enam, weur, wnam, oc];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is R2BucketLocation && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'R2BucketLocation($value)'; } 
 }
