//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// Waiting room type
final class RealtimekitPresetPermissionsWaitingRoomType {
  const RealtimekitPresetPermissionsWaitingRoomType._(this.value);

  factory RealtimekitPresetPermissionsWaitingRoomType.fromJson(String json) {
    return switch (json) {
      'SKIP' => skip,
      'ON_PRIVILEGED_USER_ENTRY' => onPrivilegedUserEntry,
      'SKIP_ON_ACCEPT' => skipOnAccept,
      _ => RealtimekitPresetPermissionsWaitingRoomType._(json),
    };
  }

  static const RealtimekitPresetPermissionsWaitingRoomType skip =
      RealtimekitPresetPermissionsWaitingRoomType._('SKIP');

  static const RealtimekitPresetPermissionsWaitingRoomType
  onPrivilegedUserEntry = RealtimekitPresetPermissionsWaitingRoomType._(
    'ON_PRIVILEGED_USER_ENTRY',
  );

  static const RealtimekitPresetPermissionsWaitingRoomType skipOnAccept =
      RealtimekitPresetPermissionsWaitingRoomType._('SKIP_ON_ACCEPT');

  static const List<RealtimekitPresetPermissionsWaitingRoomType> values = [
    skip,
    onPrivilegedUserEntry,
    skipOnAccept,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is RealtimekitPresetPermissionsWaitingRoomType &&
            other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'RealtimekitPresetPermissionsWaitingRoomType($value)';
  }
}
