//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// The edge TTL mode.
final class RulesetsSetCacheSettingsEdgeTtlMode {
  const RulesetsSetCacheSettingsEdgeTtlMode._(this.value);

  factory RulesetsSetCacheSettingsEdgeTtlMode.fromJson(String json) {
    return switch (json) {
      'respect_origin' => respectOrigin,
      'bypass_by_default' => bypassByDefault,
      'override_origin' => overrideOrigin,
      _ => RulesetsSetCacheSettingsEdgeTtlMode._(json),
    };
  }

  static const RulesetsSetCacheSettingsEdgeTtlMode respectOrigin =
      RulesetsSetCacheSettingsEdgeTtlMode._('respect_origin');

  static const RulesetsSetCacheSettingsEdgeTtlMode bypassByDefault =
      RulesetsSetCacheSettingsEdgeTtlMode._('bypass_by_default');

  static const RulesetsSetCacheSettingsEdgeTtlMode overrideOrigin =
      RulesetsSetCacheSettingsEdgeTtlMode._('override_origin');

  static const List<RulesetsSetCacheSettingsEdgeTtlMode> values = [
    respectOrigin,
    bypassByDefault,
    overrideOrigin,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is RulesetsSetCacheSettingsEdgeTtlMode && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'RulesetsSetCacheSettingsEdgeTtlMode($value)';
  }
}
