//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// The type of URL normalization performed by Cloudflare.
final class RulesetsUrlNormalizationType {
  const RulesetsUrlNormalizationType._(this.value);

  factory RulesetsUrlNormalizationType.fromJson(String json) {
    return switch (json) {
      'cloudflare' => cloudflare,
      'rfc3986' => rfc3986,
      _ => RulesetsUrlNormalizationType._(json),
    };
  }

  static const RulesetsUrlNormalizationType cloudflare =
      RulesetsUrlNormalizationType._('cloudflare');

  static const RulesetsUrlNormalizationType rfc3986 =
      RulesetsUrlNormalizationType._('rfc3986');

  static const List<RulesetsUrlNormalizationType> values = [
    cloudflare,
    rfc3986,
  ];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is RulesetsUrlNormalizationType && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'RulesetsUrlNormalizationType($value)';
  }
}
