//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

/// The HTTP method to use for the health check.
final class SmartshieldHttpConfigMethod {
  const SmartshieldHttpConfigMethod._(this.value);

  factory SmartshieldHttpConfigMethod.fromJson(String json) {
    return switch (json) {
      'GET' => $get,
      'HEAD' => head,
      _ => SmartshieldHttpConfigMethod._(json),
    };
  }

  static const SmartshieldHttpConfigMethod $get = SmartshieldHttpConfigMethod._(
    'GET',
  );

  static const SmartshieldHttpConfigMethod head = SmartshieldHttpConfigMethod._(
    'HEAD',
  );

  static const List<SmartshieldHttpConfigMethod> values = [$get, head];

  final String value;

  String toJson() {
    return value;
  }

  /// Whether this value is unknown (not defined in the OpenAPI spec).
  bool get isUnknown {
    return !values.contains(this);
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is SmartshieldHttpConfigMethod && other.value == value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

  @override
  String toString() {
    return 'SmartshieldHttpConfigMethod($value)';
  }
}
