//  GENERATED CODE — DO NOT MODIFY BY HAND
//
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class UrlscannerSearchScansResponseErrors {
  const UrlscannerSearchScansResponseErrors({required this.message});

  factory UrlscannerSearchScansResponseErrors.fromJson(
    Map<String, dynamic> json,
  ) {
    return UrlscannerSearchScansResponseErrors(
      message: json['message'] as String,
    );
  }

  final String message;

  Map<String, dynamic> toJson() {
    return {'message': message};
  }

  static bool canParse(Map<String, dynamic> json) {
    return json.containsKey('message') && json['message'] is String;
  }

  UrlscannerSearchScansResponseErrors copyWith({String? message}) {
    return UrlscannerSearchScansResponseErrors(
      message: message ?? this.message,
    );
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is UrlscannerSearchScansResponseErrors &&
            message == other.message;
  }

  @override
  int get hashCode {
    return message.hashCode;
  }

  @override
  String toString() {
    return 'UrlscannerSearchScansResponseErrors(message: $message)';
  }
}
