//  dart format off
//  GENERATED CODE — DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from cloudflare.yaml
//  OpenAPI spec version: 3.0.3

final class ZeroTrustGatewayProxyEndpointIdentity {const ZeroTrustGatewayProxyEndpointIdentity({this.createdAt, this.id, required this.kind, required this.name, this.subdomain, this.updatedAt, });

factory ZeroTrustGatewayProxyEndpointIdentity.fromJson(Map<String, dynamic> json) { return ZeroTrustGatewayProxyEndpointIdentity(
  createdAt: json['created_at'] != null ? DateTime.parse(json['created_at'] as String) : null,
  id: json['id'] as String?,
  kind: json['kind'] as String,
  name: json['name'] as String,
  subdomain: json['subdomain'] as String?,
  updatedAt: json['updated_at'] != null ? DateTime.parse(json['updated_at'] as String) : null,
); }

final DateTime? createdAt;

final String? id;

/// The proxy endpoint kind
final String kind;

final String name;

final String? subdomain;

final DateTime? updatedAt;

Map<String, dynamic> toJson() { return {
  if (createdAt != null) 'created_at': createdAt?.toIso8601String(),
  'id': ?id,
  'kind': kind,
  'name': name,
  'subdomain': ?subdomain,
  if (updatedAt != null) 'updated_at': updatedAt?.toIso8601String(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('kind') && json['kind'] is String &&
      json.containsKey('name') && json['name'] is String; } 
ZeroTrustGatewayProxyEndpointIdentity copyWith({DateTime Function()? createdAt, String Function()? id, String? kind, String? name, String Function()? subdomain, DateTime Function()? updatedAt, }) { return ZeroTrustGatewayProxyEndpointIdentity(
  createdAt: createdAt != null ? createdAt() : this.createdAt,
  id: id != null ? id() : this.id,
  kind: kind ?? this.kind,
  name: name ?? this.name,
  subdomain: subdomain != null ? subdomain() : this.subdomain,
  updatedAt: updatedAt != null ? updatedAt() : this.updatedAt,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ZeroTrustGatewayProxyEndpointIdentity &&
          createdAt == other.createdAt &&
          id == other.id &&
          kind == other.kind &&
          name == other.name &&
          subdomain == other.subdomain &&
          updatedAt == other.updatedAt; } 
@override int get hashCode { return Object.hash(createdAt, id, kind, name, subdomain, updatedAt); } 
@override String toString() { return 'ZeroTrustGatewayProxyEndpointIdentity(createdAt: $createdAt, id: $id, kind: $kind, name: $name, subdomain: $subdomain, updatedAt: $updatedAt)'; } 
 }
