//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

final class BillingGetAllBudgetsOrgScope {const BillingGetAllBudgetsOrgScope._(this.value);

factory BillingGetAllBudgetsOrgScope.fromJson(String json) { return switch (json) {
  'enterprise' => enterprise,
  'organization' => organization,
  'repository' => repository,
  'cost_center' => costCenter,
  _ => BillingGetAllBudgetsOrgScope._(json),
}; }

static const BillingGetAllBudgetsOrgScope enterprise = BillingGetAllBudgetsOrgScope._('enterprise');

static const BillingGetAllBudgetsOrgScope organization = BillingGetAllBudgetsOrgScope._('organization');

static const BillingGetAllBudgetsOrgScope repository = BillingGetAllBudgetsOrgScope._('repository');

static const BillingGetAllBudgetsOrgScope costCenter = BillingGetAllBudgetsOrgScope._('cost_center');

static const List<BillingGetAllBudgetsOrgScope> values = [enterprise, organization, repository, costCenter];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is BillingGetAllBudgetsOrgScope && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'BillingGetAllBudgetsOrgScope($value)'; } 
 }
