// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'codespaces_create_for_authenticated_user_request_variant1.dart';import 'codespaces_create_for_authenticated_user_request_variant2.dart';typedef CodespacesCreateForAuthenticatedUserRequest = OneOf2<CodespacesCreateForAuthenticatedUserRequestVariant1,CodespacesCreateForAuthenticatedUserRequestVariant2>;
