// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// Generated by degenerate from github-rest-3.1.yaml
// OpenAPI spec version: 3.1.0

import 'package:degenerate_runtime/degenerate_runtime.dart';final class ReposSetTeamAccessRestrictionsRequestVariant1 {const ReposSetTeamAccessRestrictionsRequestVariant1({required this.teams});

factory ReposSetTeamAccessRestrictionsRequestVariant1.fromJson(Map<String, dynamic> json) { return ReposSetTeamAccessRestrictionsRequestVariant1(
  teams: (json['teams'] as List<dynamic>).map((e) => e as String).toList(),
); }

/// The slug values for teams
final List<String> teams;

Map<String, dynamic> toJson() { return {
  'teams': teams,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('teams'); } 
ReposSetTeamAccessRestrictionsRequestVariant1 copyWith({List<String>? teams}) { return ReposSetTeamAccessRestrictionsRequestVariant1(
  teams: teams ?? this.teams,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ReposSetTeamAccessRestrictionsRequestVariant1 &&
          listEquals(teams, other.teams); } 
@override int get hashCode { return Object.hashAll(teams).hashCode; } 
@override String toString() { return 'ReposSetTeamAccessRestrictionsRequestVariant1(teams: $teams)'; } 
 }
