// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'webhook_package_published_package_package_version_nuget_metadata_value_variant4.dart';typedef WebhookPackagePublishedPackagePackageVersionNugetMetadataValue = OneOf4<bool,String,int,WebhookPackagePublishedPackagePackageVersionNugetMetadataValueVariant4>;
