//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

import 'enterprise_webhooks.dart';import 'organization_simple_webhooks.dart';import 'repository_webhooks.dart';import 'simple_installation.dart';import 'simple_user.dart';import 'webhook_label_edited_changes.dart';import 'webhooks_label.dart';final class WebhookLabelEditedAction {const WebhookLabelEditedAction._(this.value);

factory WebhookLabelEditedAction.fromJson(String json) { return switch (json) {
  'edited' => edited,
  _ => WebhookLabelEditedAction._(json),
}; }

static const WebhookLabelEditedAction edited = WebhookLabelEditedAction._('edited');

static const List<WebhookLabelEditedAction> values = [edited];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is WebhookLabelEditedAction && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'WebhookLabelEditedAction($value)'; } 
 }
final class WebhookLabelEdited {const WebhookLabelEdited({required this.action, this.changes, this.enterprise, this.installation, required this.label, this.organization, required this.repository, required this.sender, });

factory WebhookLabelEdited.fromJson(Map<String, dynamic> json) { return WebhookLabelEdited(
  action: WebhookLabelEditedAction.fromJson(json['action'] as String),
  changes: json['changes'] != null ? WebhookLabelEditedChanges.fromJson(json['changes'] as Map<String, dynamic>) : null,
  enterprise: json['enterprise'] != null ? EnterpriseWebhooks.fromJson(json['enterprise'] as Map<String, dynamic>) : null,
  installation: json['installation'] != null ? SimpleInstallation.fromJson(json['installation'] as Map<String, dynamic>) : null,
  label: WebhooksLabel.fromJson(json['label'] as Map<String, dynamic>),
  organization: json['organization'] != null ? OrganizationSimpleWebhooks.fromJson(json['organization'] as Map<String, dynamic>) : null,
  repository: RepositoryWebhooks.fromJson(json['repository'] as Map<String, dynamic>),
  sender: SimpleUser.fromJson(json['sender'] as Map<String, dynamic>),
); }

final WebhookLabelEditedAction action;

/// The changes to the label if the action was `edited`.
final WebhookLabelEditedChanges? changes;

final EnterpriseWebhooks? enterprise;

final SimpleInstallation? installation;

final WebhooksLabel label;

final OrganizationSimpleWebhooks? organization;

final RepositoryWebhooks repository;

final SimpleUser sender;

Map<String, dynamic> toJson() { return {
  'action': action.toJson(),
  if (changes != null) 'changes': changes?.toJson(),
  if (enterprise != null) 'enterprise': enterprise?.toJson(),
  if (installation != null) 'installation': installation?.toJson(),
  'label': label.toJson(),
  if (organization != null) 'organization': organization?.toJson(),
  'repository': repository.toJson(),
  'sender': sender.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('action') &&
      json.containsKey('label') &&
      json.containsKey('repository') &&
      json.containsKey('sender'); } 
WebhookLabelEdited copyWith({WebhookLabelEditedAction? action, WebhookLabelEditedChanges Function()? changes, EnterpriseWebhooks Function()? enterprise, SimpleInstallation Function()? installation, WebhooksLabel? label, OrganizationSimpleWebhooks Function()? organization, RepositoryWebhooks? repository, SimpleUser? sender, }) { return WebhookLabelEdited(
  action: action ?? this.action,
  changes: changes != null ? changes() : this.changes,
  enterprise: enterprise != null ? enterprise() : this.enterprise,
  installation: installation != null ? installation() : this.installation,
  label: label ?? this.label,
  organization: organization != null ? organization() : this.organization,
  repository: repository ?? this.repository,
  sender: sender ?? this.sender,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is WebhookLabelEdited &&
          action == other.action &&
          changes == other.changes &&
          enterprise == other.enterprise &&
          installation == other.installation &&
          label == other.label &&
          organization == other.organization &&
          repository == other.repository &&
          sender == other.sender; } 
@override int get hashCode { return Object.hash(action, changes, enterprise, installation, label, organization, repository, sender); } 
@override String toString() { return 'WebhookLabelEdited(action: $action, changes: $changes, enterprise: $enterprise, installation: $installation, label: $label, organization: $organization, repository: $repository, sender: $sender)'; } 
 }
