//  GENERATED CODE - DO NOT MODIFY BY HAND
// 
//  Generated by degenerate from github-rest-3.1.yaml
//  OpenAPI spec version: 3.1.0

import 'webhook_pull_request_review_request_removed_review_request_removed_pull_request_auto_merge_enabled_by.dart';/// The merge method to use.
final class WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod {const WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod._(this.value);

factory WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod.fromJson(String json) { return switch (json) {
  'merge' => merge,
  'squash' => squash,
  'rebase' => rebase,
  _ => WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod._(json),
}; }

static const WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod merge = WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod._('merge');

static const WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod squash = WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod._('squash');

static const WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod rebase = WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod._('rebase');

static const List<WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod> values = [merge, squash, rebase];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod($value)'; } 
 }
/// The status of auto merging a pull request.
final class WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMerge {const WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMerge({required this.commitMessage, required this.commitTitle, required this.enabledBy, required this.mergeMethod, });

factory WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMerge.fromJson(Map<String, dynamic> json) { return WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMerge(
  commitMessage: json['commit_message'] as String?,
  commitTitle: json['commit_title'] as String?,
  enabledBy: json['enabled_by'] != null ? WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeEnabledBy.fromJson(json['enabled_by'] as Map<String, dynamic>) : null,
  mergeMethod: WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod.fromJson(json['merge_method'] as String),
); }

/// Commit message for the merge commit.
final String? commitMessage;

/// Title for the merge commit message.
final String? commitTitle;

final WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeEnabledBy? enabledBy;

/// The merge method to use.
final WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod mergeMethod;

Map<String, dynamic> toJson() { return {
  'commit_message': ?commitMessage,
  'commit_title': ?commitTitle,
  if (enabledBy != null) 'enabled_by': enabledBy?.toJson(),
  'merge_method': mergeMethod.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('commit_message') && json['commit_message'] is String &&
      json.containsKey('commit_title') && json['commit_title'] is String &&
      json.containsKey('enabled_by') &&
      json.containsKey('merge_method'); } 
WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMerge copyWith({String? Function()? commitMessage, String? Function()? commitTitle, WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeEnabledBy? Function()? enabledBy, WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMergeMergeMethod? mergeMethod, }) { return WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMerge(
  commitMessage: commitMessage != null ? commitMessage() : this.commitMessage,
  commitTitle: commitTitle != null ? commitTitle() : this.commitTitle,
  enabledBy: enabledBy != null ? enabledBy() : this.enabledBy,
  mergeMethod: mergeMethod ?? this.mergeMethod,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMerge &&
          commitMessage == other.commitMessage &&
          commitTitle == other.commitTitle &&
          enabledBy == other.enabledBy &&
          mergeMethod == other.mergeMethod; } 
@override int get hashCode { return Object.hash(commitMessage, commitTitle, enabledBy, mergeMethod); } 
@override String toString() { return 'WebhookPullRequestReviewRequestRemovedReviewRequestRemovedPullRequestAutoMerge(commitMessage: $commitMessage, commitTitle: $commitTitle, enabledBy: $enabledBy, mergeMethod: $mergeMethod)'; } 
 }
